// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                     pgtype.UUID
	Email                  interface{}
	Plan                   string
	Status                 string
	ProviderCustomerID     pgtype.Text
	CreatedAt              pgtype.Timestamptz
	DeletionRequestedAt    pgtype.Timestamptz
	StripeSubscriptionItem pgtype.Text
	LastQuotaWarningAt     pgtype.Timestamptz
	PastDueAt              pgtype.Timestamptz
	MfaEnrolledAt          pgtype.Timestamptz
	MfaSecretEncrypted     []byte
	MfaRecoveryCodesHash   [][]byte
	MfaRequired            bool
	OverageCapCents        pgtype.Int8
}

type AccountCredit struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	CentsRemaining int64
	Reason         string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type AccountPassword struct {
	AccountID pgtype.UUID
	Hash      string
	UpdatedAt pgtype.Timestamptz
}

type AlertDelivery struct {
	ID             pgtype.UUID
	RuleID         pgtype.UUID
	AccountID      pgtype.UUID
	AppID          pgtype.UUID
	IdempotencyKey string
	Payload        []byte
	Status         string
	AttemptCount   int32
	LastStatusCode pgtype.Int4
	LastError      pgtype.Text
	ObservedValue  float64
	FiredAt        pgtype.Timestamptz
	DeliveredAt    pgtype.Timestamptz
}

type AlertRule struct {
	ID                  pgtype.UUID
	AccountID           pgtype.UUID
	AppID               pgtype.UUID
	Name                string
	Enabled             bool
	Metric              string
	Comparison          string
	Threshold           float64
	WindowSpec          string
	FailureSource       pgtype.Text
	WebhookUrl          string
	WebhookSecretSealed []byte
	CooldownMinutes     int32
	State               string
	LastFiredAt         pgtype.Timestamptz
	LastEvaluatedAt     pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ApiKey struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	KeySha256  []byte
	Label      pgtype.Text
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	Scopes     []string
}

type App struct {
	ID                     pgtype.UUID
	AccountID              pgtype.UUID
	Slug                   string
	Type                   string
	Runtime                pgtype.Text
	RamMb                  int32
	IdleTimeoutS           pgtype.Int4
	MaxConcurrency         int32
	Status                 string
	CreatedAt              pgtype.Timestamptz
	Manifest               []byte
	GithubInstallID        pgtype.Int8
	GithubRepoFullName     pgtype.Text
	GithubProductionBranch pgtype.Text
	MinInstances           int32
	EgressAllowlist        []netip.Prefix
	// Per-instance RPS target. When live_request_count / live_instance_count exceeds this, schedd admits another instance (up to plan max_concurrency). Hobby/Pro/Scale only (plan gate). 0 / NULL = disabled (the trigger skips the app).
	AutoscaleTargetRps pgtype.Int4
	// Per-instance CPU% target (1..100). Pro/Scale only (plan gate). 0 / NULL = disabled (the trigger skips the app). CPU target is unbounded above 100 inside the DB; the apid handler enforces [1, 100] via 422.
	AutoscaleTargetCpuPct  pgtype.Int4
	GithubInstallBindingID pgtype.Text
	GithubInstallAccountID pgtype.UUID
	GithubInstallLinkedAt  pgtype.Timestamptz
}

type AppEnv struct {
	AccountID pgtype.UUID
	AppID     pgtype.UUID
	Key       string
	Value     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppSecret struct {
	AccountID  pgtype.UUID
	AppID      pgtype.UUID
	Key        string
	Ciphertext []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Build struct {
	ID           pgtype.UUID
	DeploymentID pgtype.UUID
	Kind         string
	SourceBytes  int64
	Status       string
	FailureClass pgtype.Text
	LogPath      pgtype.Text
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	EnqueuedAt   pgtype.Timestamptz
}

type BuildProvenance struct {
	ID              pgtype.UUID
	BuildID         pgtype.UUID
	BuildkitVersion pgtype.Text
	RailpackVersion pgtype.Text
	BaseDigest      pgtype.Text
	SourceSha256    string
	SourceUrl       pgtype.Text
	CommitSha       pgtype.Text
	Plan            pgtype.Text
	RunnerDigest    pgtype.Text
	BuilderNodeID   pgtype.Text
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	SbomStorageKey  pgtype.Text
}

type CliAuthCode struct {
	TokenHash  []byte
	AccountID  pgtype.UUID
	Status     string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type ComputeNode struct {
	ID                 pgtype.UUID
	Name               string
	TargetUrl          string
	Vpcpus             int32
	MemMb              int32
	MaxConcurrency     int32
	AdmissionCeilingMb int32
	Active             bool
	LastHeartbeatAt    pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type ComputeNodeHeartbeat struct {
	ID              int64
	NodeID          pgtype.UUID
	ReceivedAt      pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	Source          string
}

type CreditLedger struct {
	ID                pgtype.UUID
	AccountID         pgtype.UUID
	CreditID          pgtype.UUID
	DeltaCents        int64
	Reason            string
	Actor             string
	CreatedAt         pgtype.Timestamptz
	ProviderInvoiceID pgtype.Text
}

type Cron struct {
	ID          pgtype.UUID
	AppID       pgtype.UUID
	Schedule    string
	Path        string
	Enabled     bool
	LastFiredAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type CustomDomain struct {
	Domain         interface{}
	AppID          pgtype.UUID
	VerifiedAt     pgtype.Timestamptz
	ChallengeToken string
	AppIDRedirect  pgtype.UUID
}

type Deployment struct {
	ID          pgtype.UUID
	AppID       pgtype.UUID
	BuildID     pgtype.UUID
	ImageDigest string
	RootfsPath  pgtype.Text
	RootfsBytes pgtype.Int8
	Status      string
	Error       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	Kind        string
	SourcePath  pgtype.Text
	SourceBytes pgtype.Int8
	Handler     pgtype.Text
	LogPath     pgtype.Text
	ErrorCode   pgtype.Text
	RootfsKey   string
	SourceUrl   pgtype.Text
	CommitSha   pgtype.Text
}

type DeploymentLog struct {
	DeploymentID pgtype.UUID
	Seq          int64
	Stream       string
	Line         string
	WrittenAt    pgtype.Timestamptz
}

type Event struct {
	ID      int64
	At      pgtype.Timestamptz
	Actor   string
	Kind    string
	Subject pgtype.UUID
	Data    []byte
}

type GdprRequest struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	AccountEmail string
	Action       string
	RequestedAt  pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type GithubInstallation struct {
	AccountID          pgtype.UUID
	InstallationID     int64
	DefaultBranch      string
	SealedInstallToken []byte
	TokenExpiresAt     pgtype.Timestamptz
	SealedAt           pgtype.Timestamptz
	AuditGithubLogin   string
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type IdempotencyKey struct {
	Key            string
	AccountID      pgtype.UUID
	ResponseStatus int32
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
}

type Instance struct {
	ID            pgtype.UUID
	AppID         pgtype.UUID
	DeploymentID  pgtype.UUID
	State         string
	Netns         pgtype.Text
	GuestUid      pgtype.Int4
	HostIp        *netip.Addr
	RamMb         int32
	StartedAt     pgtype.Timestamptz
	LastRequestAt pgtype.Timestamptz
	ParkedAt      pgtype.Timestamptz
	TerminalAt    pgtype.Timestamptz
	NodeID        pgtype.UUID
	WakeID        pgtype.UUID
}

type Invocation struct {
	ID             pgtype.UUID
	AppID          pgtype.UUID
	AccountID      pgtype.UUID
	Source         string
	State          string
	Payload        []byte
	Headers        []byte
	DueAt          pgtype.Timestamptz
	Method         string
	Path           string
	CronID         pgtype.UUID
	ScheduledAt    pgtype.Timestamptz
	AckUrl         pgtype.Text
	Result         []byte
	LeaseExpiresAt pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	InstanceID     pgtype.Text
	Attempts       int32
	LastError      pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type InvocationsPendingPerApp struct {
	AppID   pgtype.UUID
	Source  string
	Pending int64
}

type Invoice struct {
	ID                pgtype.UUID
	AccountID         pgtype.UUID
	Provider          string
	ProviderInvoiceID string
	Number            string
	Status            string
	PeriodStart       pgtype.Timestamptz
	PeriodEnd         pgtype.Timestamptz
	SubtotalCents     int64
	TaxCents          int64
	TotalCents        int64
	AmountPaidCents   int64
	Currency          string
	PdfAvailable      bool
	HostedUrl         string
	Raw               []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type LoginToken struct {
	TokenHash  []byte
	AccountID  pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

type OauthLink struct {
	Provider        string
	ProviderSubject string
	AccountID       pgtype.UUID
	Email           string
	EmailVerified   bool
	CreatedAt       pgtype.Timestamptz
}

type PaddleOverageDedupe struct {
	AccountID   pgtype.UUID
	Month       pgtype.Timestamptz
	PushedAt    pgtype.Timestamptz
	WindowStart pgtype.Timestamptz
	State       string
	ClaimedAt   pgtype.Timestamptz
	ClaimedBy   pgtype.Text
}

type RecentBuildClaim struct {
	AccountID pgtype.UUID
	ClaimedAt pgtype.Timestamptz
	BuildID   pgtype.UUID
}

type Session struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	IssuedIp   *netip.Addr
	IssuedUa   pgtype.Text
	IssuedAt   pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Snapshot struct {
	ID           pgtype.UUID
	DeploymentID pgtype.UUID
	FcVersion    string
	MemBytes     int64
	DiskBytes    int64
	Stale        bool
	CreatedAt    pgtype.Timestamptz
	StorageKey   string
}

type StripePushDedupe struct {
	AccountID pgtype.UUID
	Hour      pgtype.Timestamptz
	PushedAt  pgtype.Timestamptz
}

type UsageMinute struct {
	AccountID  pgtype.UUID
	AppID      pgtype.UUID
	InstanceID pgtype.UUID
	Minute     pgtype.Timestamptz
	MbSeconds  int64
	Requests   int32
	// Cumulative host cgroup CPU-µs consumed by the instance during this minute. Source: vmmd cpustats.Cache (cpu.stat usage_usec delta) → schedd instancestats.Poller → meterd Sampler. Measurement only — billing is on plan RAM. issue #279 / PR-B.
	CpuUsec int64
}

type UsageMonthly struct {
	AccountID pgtype.UUID
	AppID     pgtype.UUID
	Month     pgtype.Interval
	MbSeconds int64
	CpuUsec   int64
	Requests  int64
}
