// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aPIKeyByHash = `-- name: APIKeyByHash :one
select id, account_id, key_sha256, coalesce(label, ''), scopes, created_at, coalesce(last_used_at, 'epoch'::timestamptz)
from api_keys where key_sha256 = $1
`

type APIKeyByHashRow struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	KeySha256  []byte
	Label      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

// Used by handlers_auth.go so an operator investigating "who signed in
// as alice?" can identify the key that authenticated. See ADR-034 rev2.
func (q *Queries) APIKeyByHash(ctx context.Context, db DBTX, keySha256 []byte) (APIKeyByHashRow, error) {
	row := db.QueryRow(ctx, aPIKeyByHash, keySha256)
	var i APIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.KeySha256,
		&i.Label,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const accountByEmail = `-- name: AccountByEmail :one
select id, email, plan, status, coalesce(provider_customer_id, ''), created_at
from accounts where email = $1
`

type AccountByEmailRow struct {
	ID                 pgtype.UUID
	Email              interface{}
	Plan               string
	Status             string
	ProviderCustomerID string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) AccountByEmail(ctx context.Context, db DBTX, email interface{}) (AccountByEmailRow, error) {
	row := db.QueryRow(ctx, accountByEmail, email)
	var i AccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const accountByID = `-- name: AccountByID :one
select id, email, plan, status, coalesce(provider_customer_id, ''), created_at
from accounts where id = $1
`

type AccountByIDRow struct {
	ID                 pgtype.UUID
	Email              interface{}
	Plan               string
	Status             string
	ProviderCustomerID string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) AccountByID(ctx context.Context, db DBTX, id pgtype.UUID) (AccountByIDRow, error) {
	row := db.QueryRow(ctx, accountByID, id)
	var i AccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const accountByKeyHash = `-- name: AccountByKeyHash :one
select a.id, a.email, a.plan, a.status, coalesce(a.provider_customer_id, ''), a.created_at
from accounts a
join api_keys k on k.account_id = a.id
where k.key_sha256 = $1
`

type AccountByKeyHashRow struct {
	ID                 pgtype.UUID
	Email              interface{}
	Plan               string
	Status             string
	ProviderCustomerID string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) AccountByKeyHash(ctx context.Context, db DBTX, keySha256 []byte) (AccountByKeyHashRow, error) {
	row := db.QueryRow(ctx, accountByKeyHash, keySha256)
	var i AccountByKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const appByID = `-- name: AppByID :one
select id, account_id, slug, type, coalesce(runtime, ''), ram_mb, coalesce(idle_timeout_s, 0),
       max_concurrency, status, manifest, created_at
from apps where id = $1
`

type AppByIDRow struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	Slug           string
	Type           string
	Runtime        string
	RamMb          int32
	IdleTimeoutS   int32
	MaxConcurrency int32
	Status         string
	Manifest       []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) AppByID(ctx context.Context, db DBTX, id pgtype.UUID) (AppByIDRow, error) {
	row := db.QueryRow(ctx, appByID, id)
	var i AppByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Type,
		&i.Runtime,
		&i.RamMb,
		&i.IdleTimeoutS,
		&i.MaxConcurrency,
		&i.Status,
		&i.Manifest,
		&i.CreatedAt,
	)
	return i, err
}

const appBySlug = `-- name: AppBySlug :one
select id, account_id, slug, type, coalesce(runtime, ''), ram_mb, coalesce(idle_timeout_s, 0),
       max_concurrency, status, manifest, created_at
from apps where slug = $1
`

type AppBySlugRow struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	Slug           string
	Type           string
	Runtime        string
	RamMb          int32
	IdleTimeoutS   int32
	MaxConcurrency int32
	Status         string
	Manifest       []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) AppBySlug(ctx context.Context, db DBTX, slug string) (AppBySlugRow, error) {
	row := db.QueryRow(ctx, appBySlug, slug)
	var i AppBySlugRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Type,
		&i.Runtime,
		&i.RamMb,
		&i.IdleTimeoutS,
		&i.MaxConcurrency,
		&i.Status,
		&i.Manifest,
		&i.CreatedAt,
	)
	return i, err
}

const appendEvent = `-- name: AppendEvent :exec
insert into events (actor, kind, subject, data)
values ($1, $2, $3, $4)
`

type AppendEventParams struct {
	Actor   string
	Kind    string
	Subject pgtype.UUID
	Data    []byte
}

func (q *Queries) AppendEvent(ctx context.Context, db DBTX, arg AppendEventParams) error {
	_, err := db.Exec(ctx, appendEvent,
		arg.Actor,
		arg.Kind,
		arg.Subject,
		arg.Data,
	)
	return err
}

const appendUsage = `-- name: AppendUsage :exec
insert into usage_minutes (account_id, app_id, instance_id, minute, mb_seconds, requests, cpu_usec, tx_bytes, net_tx_bytes)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (instance_id, minute) do update
   set cpu_usec     = usage_minutes.cpu_usec     + EXCLUDED.cpu_usec,
       tx_bytes     = usage_minutes.tx_bytes     + EXCLUDED.tx_bytes,
       net_tx_bytes = usage_minutes.net_tx_bytes + EXCLUDED.net_tx_bytes
`

type AppendUsageParams struct {
	AccountID  pgtype.UUID
	AppID      pgtype.UUID
	InstanceID pgtype.UUID
	Minute     pgtype.Timestamptz
	MbSeconds  int64
	Requests   int32
	CpuUsec    int64
	TxBytes    int64
	NetTxBytes int64
}

// Idempotent on (instance_id, minute) for mb_seconds / requests
// (M7 hardening, PR feat/m7-beta-hardening): a redelivered
// minute is a no-op for the billing-floor columns so a meterd
// restart / network blip / two meterd instances cannot inflate
// billing. cpu_usec, tx_bytes, and net_tx_bytes are ADDITIVE on
// the same conflict key — the schedd / meterd accumulators can
// each call AppendUsage many times within the same minute; the
// columns are the sum of all per-tick deltas.
//
//	cpu_usec     — issue #279 / PR-B / ADR-039
//	tx_bytes     — ADR-046 (gateway HTTP response body bytes)
//	net_tx_bytes — ADR-046 (root-side vethHost.rx_bytes delta)
func (q *Queries) AppendUsage(ctx context.Context, db DBTX, arg AppendUsageParams) error {
	_, err := db.Exec(ctx, appendUsage,
		arg.AccountID,
		arg.AppID,
		arg.InstanceID,
		arg.Minute,
		arg.MbSeconds,
		arg.Requests,
		arg.CpuUsec,
		arg.TxBytes,
		arg.NetTxBytes,
	)
	return err
}

const buildByDeployment = `-- name: BuildByDeployment :one
select id, deployment_id, kind, source_bytes, status, failure_class, log_path, started_at, finished_at, enqueued_at
from builds where deployment_id = $1 order by started_at desc nulls last limit 1
`

func (q *Queries) BuildByDeployment(ctx context.Context, db DBTX, deploymentID pgtype.UUID) (Build, error) {
	row := db.QueryRow(ctx, buildByDeployment, deploymentID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Kind,
		&i.SourceBytes,
		&i.Status,
		&i.FailureClass,
		&i.LogPath,
		&i.StartedAt,
		&i.FinishedAt,
		&i.EnqueuedAt,
	)
	return i, err
}

const buildByID = `-- name: BuildByID :one
select id, deployment_id, kind, source_bytes, status, failure_class, log_path, started_at, finished_at, enqueued_at
from builds where id = $1
`

func (q *Queries) BuildByID(ctx context.Context, db DBTX, id pgtype.UUID) (Build, error) {
	row := db.QueryRow(ctx, buildByID, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Kind,
		&i.SourceBytes,
		&i.Status,
		&i.FailureClass,
		&i.LogPath,
		&i.StartedAt,
		&i.FinishedAt,
		&i.EnqueuedAt,
	)
	return i, err
}

const countDeployedApps = `-- name: CountDeployedApps :one
select count(*) from apps where account_id = $1 and status in ('active', 'evicted_cold')
`

func (q *Queries) CountDeployedApps(ctx context.Context, db DBTX, accountID pgtype.UUID) (int64, error) {
	row := db.QueryRow(ctx, countDeployedApps, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
insert into api_keys (account_id, key_sha256, label, scopes)
values ($1, $2, $3, $4)
returning id, account_id, key_sha256, coalesce(label, ''), scopes, created_at, coalesce(last_used_at, 'epoch'::timestamptz)
`

type CreateAPIKeyParams struct {
	AccountID pgtype.UUID
	KeySha256 []byte
	Label     pgtype.Text
	Scopes    []string
}

type CreateAPIKeyRow struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	KeySha256  []byte
	Label      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

// scopes is $4 (text[]). The handler is responsible for validating the
// scope vocabulary; the store does not. See ADR-034 rev2.
func (q *Queries) CreateAPIKey(ctx context.Context, db DBTX, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := db.QueryRow(ctx, createAPIKey,
		arg.AccountID,
		arg.KeySha256,
		arg.Label,
		arg.Scopes,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.KeySha256,
		&i.Label,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
insert into accounts (id, email, plan, status, provider_customer_id)
values (gen_random_uuid(), $1, $2, $3, null)
returning id, email, plan, status, coalesce(provider_customer_id, ''), created_at
`

type CreateAccountParams struct {
	Email  interface{}
	Plan   string
	Status string
}

type CreateAccountRow struct {
	ID                 pgtype.UUID
	Email              interface{}
	Plan               string
	Status             string
	ProviderCustomerID string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) (CreateAccountRow, error) {
	row := db.QueryRow(ctx, createAccount, arg.Email, arg.Plan, arg.Status)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Plan,
		&i.Status,
		&i.ProviderCustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const createApp = `-- name: CreateApp :one
insert into apps (id, account_id, slug, type, runtime, ram_mb, idle_timeout_s, max_concurrency, status, manifest)
values (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, 'active', coalesce($8, '{}'::jsonb))
returning id, account_id, slug, type, coalesce(runtime, ''), ram_mb, coalesce(idle_timeout_s, 0),
          max_concurrency, status, manifest, created_at
`

type CreateAppParams struct {
	AccountID      pgtype.UUID
	Slug           string
	Type           string
	Runtime        pgtype.Text
	RamMb          int32
	IdleTimeoutS   pgtype.Int4
	MaxConcurrency int32
	Column8        interface{}
}

type CreateAppRow struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	Slug           string
	Type           string
	Runtime        string
	RamMb          int32
	IdleTimeoutS   int32
	MaxConcurrency int32
	Status         string
	Manifest       []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateApp(ctx context.Context, db DBTX, arg CreateAppParams) (CreateAppRow, error) {
	row := db.QueryRow(ctx, createApp,
		arg.AccountID,
		arg.Slug,
		arg.Type,
		arg.Runtime,
		arg.RamMb,
		arg.IdleTimeoutS,
		arg.MaxConcurrency,
		arg.Column8,
	)
	var i CreateAppRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Type,
		&i.Runtime,
		&i.RamMb,
		&i.IdleTimeoutS,
		&i.MaxConcurrency,
		&i.Status,
		&i.Manifest,
		&i.CreatedAt,
	)
	return i, err
}

const createBuild = `-- name: CreateBuild :one
insert into builds (id, deployment_id, kind, source_bytes, status, log_path)
values (gen_random_uuid(), $1, $2, $3, 'queued', $4)
returning id, deployment_id, kind, source_bytes, status, failure_class, log_path, started_at, finished_at, enqueued_at
`

type CreateBuildParams struct {
	DeploymentID pgtype.UUID
	Kind         string
	SourceBytes  int64
	LogPath      pgtype.Text
}

func (q *Queries) CreateBuild(ctx context.Context, db DBTX, arg CreateBuildParams) (Build, error) {
	row := db.QueryRow(ctx, createBuild,
		arg.DeploymentID,
		arg.Kind,
		arg.SourceBytes,
		arg.LogPath,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Kind,
		&i.SourceBytes,
		&i.Status,
		&i.FailureClass,
		&i.LogPath,
		&i.StartedAt,
		&i.FinishedAt,
		&i.EnqueuedAt,
	)
	return i, err
}

const createCron = `-- name: CreateCron :one
insert into crons (id, app_id, schedule, path, enabled)
values (gen_random_uuid(), $1, $2, $3, $4)
returning id, app_id, schedule, path, enabled, created_at
`

type CreateCronParams struct {
	AppID    pgtype.UUID
	Schedule string
	Path     string
	Enabled  bool
}

type CreateCronRow struct {
	ID        pgtype.UUID
	AppID     pgtype.UUID
	Schedule  string
	Path      string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateCron(ctx context.Context, db DBTX, arg CreateCronParams) (CreateCronRow, error) {
	row := db.QueryRow(ctx, createCron,
		arg.AppID,
		arg.Schedule,
		arg.Path,
		arg.Enabled,
	)
	var i CreateCronRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Schedule,
		&i.Path,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomDomain = `-- name: CreateCustomDomain :one
insert into custom_domains (domain, app_id, challenge_token)
values ($1, $2, $3)
returning domain, app_id, challenge_token, verified_at
`

type CreateCustomDomainParams struct {
	Domain         interface{}
	AppID          pgtype.UUID
	ChallengeToken string
}

type CreateCustomDomainRow struct {
	Domain         interface{}
	AppID          pgtype.UUID
	ChallengeToken string
	VerifiedAt     pgtype.Timestamptz
}

func (q *Queries) CreateCustomDomain(ctx context.Context, db DBTX, arg CreateCustomDomainParams) (CreateCustomDomainRow, error) {
	row := db.QueryRow(ctx, createCustomDomain, arg.Domain, arg.AppID, arg.ChallengeToken)
	var i CreateCustomDomainRow
	err := row.Scan(
		&i.Domain,
		&i.AppID,
		&i.ChallengeToken,
		&i.VerifiedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
insert into deployments (id, app_id, build_id, image_digest, kind, source_path, source_bytes, handler, log_path, status)
values (gen_random_uuid(), $1, null, $2, $3, $4, $5, $6, $7, 'pending')
returning id, app_id, coalesce(build_id::text, ''), image_digest, kind,
          coalesce(source_path, ''), coalesce(source_bytes, 0),
          coalesce(handler, ''), coalesce(log_path, ''),
          status, coalesce(error, ''), created_at
`

type CreateDeploymentParams struct {
	AppID       pgtype.UUID
	ImageDigest string
	Kind        string
	SourcePath  pgtype.Text
	SourceBytes pgtype.Int8
	Handler     pgtype.Text
	LogPath     pgtype.Text
}

type CreateDeploymentRow struct {
	ID          pgtype.UUID
	AppID       pgtype.UUID
	Coalesce    interface{}
	ImageDigest string
	Kind        string
	SourcePath  string
	SourceBytes int64
	Handler     string
	LogPath     string
	Status      string
	Error       string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateDeployment(ctx context.Context, db DBTX, arg CreateDeploymentParams) (CreateDeploymentRow, error) {
	row := db.QueryRow(ctx, createDeployment,
		arg.AppID,
		arg.ImageDigest,
		arg.Kind,
		arg.SourcePath,
		arg.SourceBytes,
		arg.Handler,
		arg.LogPath,
	)
	var i CreateDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Coalesce,
		&i.ImageDigest,
		&i.Kind,
		&i.SourcePath,
		&i.SourceBytes,
		&i.Handler,
		&i.LogPath,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createInstance = `-- name: CreateInstance :one
insert into instances (id, app_id, deployment_id, state, ram_mb)
values (gen_random_uuid(), $1, $2, $3, $4)
returning id, app_id, deployment_id, state, coalesce(netns, ''), coalesce(guest_uid, 0),
          coalesce(host_ip::text, ''), ram_mb, started_at, last_request_at, parked_at
`

type CreateInstanceParams struct {
	AppID        pgtype.UUID
	DeploymentID pgtype.UUID
	State        string
	RamMb        int32
}

type CreateInstanceRow struct {
	ID            pgtype.UUID
	AppID         pgtype.UUID
	DeploymentID  pgtype.UUID
	State         string
	Netns         string
	GuestUid      int32
	Coalesce      interface{}
	RamMb         int32
	StartedAt     pgtype.Timestamptz
	LastRequestAt pgtype.Timestamptz
	ParkedAt      pgtype.Timestamptz
}

func (q *Queries) CreateInstance(ctx context.Context, db DBTX, arg CreateInstanceParams) (CreateInstanceRow, error) {
	row := db.QueryRow(ctx, createInstance,
		arg.AppID,
		arg.DeploymentID,
		arg.State,
		arg.RamMb,
	)
	var i CreateInstanceRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.State,
		&i.Netns,
		&i.GuestUid,
		&i.Coalesce,
		&i.RamMb,
		&i.StartedAt,
		&i.LastRequestAt,
		&i.ParkedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
insert into sessions (id, account_id, issued_ip, issued_ua)
values ($1, $2, nullif($3, '')::inet, nullif($4, ''))
returning id, account_id,
          coalesce(host(issued_ip), '') as issued_ip,
          coalesce(issued_ua, '') as issued_ua,
          issued_at, last_seen_at, revoked_at
`

type CreateSessionParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Column3   interface{}
	Column4   interface{}
}

type CreateSessionRow struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	IssuedIp   interface{}
	IssuedUa   string
	IssuedAt   pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

// IAM-3 (ADR-039, issue #187 + #244 merged). One row per dashboard login.
// Caller has already generated the uuid (the envelope seal needs the same
// value). issued_ip is an inet (” cast to NULL means "RemoteAddr
// unparseable" — surfaced as "" on read by coalesce(host(...))).
func (q *Queries) CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (CreateSessionRow, error) {
	row := db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.Column3,
		arg.Column4,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IssuedIp,
		&i.IssuedUa,
		&i.IssuedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const cronByID = `-- name: CronByID :one
select id, app_id, schedule, path, enabled, created_at
from crons where id = $1
`

type CronByIDRow struct {
	ID        pgtype.UUID
	AppID     pgtype.UUID
	Schedule  string
	Path      string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CronByID(ctx context.Context, db DBTX, id pgtype.UUID) (CronByIDRow, error) {
	row := db.QueryRow(ctx, cronByID, id)
	var i CronByIDRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Schedule,
		&i.Path,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
delete from api_keys where id = $1 and account_id = $2
`

type DeleteAPIKeyParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) DeleteAPIKey(ctx context.Context, db DBTX, arg DeleteAPIKeyParams) error {
	_, err := db.Exec(ctx, deleteAPIKey, arg.ID, arg.AccountID)
	return err
}

const deleteAPIKeyReturning = `-- name: DeleteAPIKeyReturning :one
delete from api_keys where id = $1 and account_id = $2
returning id, account_id, key_sha256, coalesce(label, ''), scopes, created_at, coalesce(last_used_at, 'epoch'::timestamptz)
`

type DeleteAPIKeyReturningParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

type DeleteAPIKeyReturningRow struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	KeySha256  []byte
	Label      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

// IAM-1 (ADR-034 rev2): delete a key and return the row in one
// statement so the handler can emit `key.deleted` audit with the
// dismissed scopes. list_secrets-shaped variant of DeleteAPIKey.
func (q *Queries) DeleteAPIKeyReturning(ctx context.Context, db DBTX, arg DeleteAPIKeyReturningParams) (DeleteAPIKeyReturningRow, error) {
	row := db.QueryRow(ctx, deleteAPIKeyReturning, arg.ID, arg.AccountID)
	var i DeleteAPIKeyReturningRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.KeySha256,
		&i.Label,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
update apps set status = 'deleted' where id = $1
`

func (q *Queries) DeleteApp(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, deleteApp, id)
	return err
}

const deleteCron = `-- name: DeleteCron :exec
delete from crons where id = $1 and app_id = $2
`

type DeleteCronParams struct {
	ID    pgtype.UUID
	AppID pgtype.UUID
}

func (q *Queries) DeleteCron(ctx context.Context, db DBTX, arg DeleteCronParams) error {
	_, err := db.Exec(ctx, deleteCron, arg.ID, arg.AppID)
	return err
}

const deleteCustomDomain = `-- name: DeleteCustomDomain :exec
delete from custom_domains where domain = $1
`

func (q *Queries) DeleteCustomDomain(ctx context.Context, db DBTX, domain interface{}) error {
	_, err := db.Exec(ctx, deleteCustomDomain, domain)
	return err
}

const deploymentByID = `-- name: DeploymentByID :one
select id, app_id, coalesce(build_id::text, ''), image_digest, kind,
       coalesce(source_path, ''), coalesce(source_bytes, 0),
       coalesce(handler, ''), coalesce(log_path, ''),
       status, coalesce(error, ''), created_at
from deployments where id = $1
`

type DeploymentByIDRow struct {
	ID          pgtype.UUID
	AppID       pgtype.UUID
	Coalesce    interface{}
	ImageDigest string
	Kind        string
	SourcePath  string
	SourceBytes int64
	Handler     string
	LogPath     string
	Status      string
	Error       string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) DeploymentByID(ctx context.Context, db DBTX, id pgtype.UUID) (DeploymentByIDRow, error) {
	row := db.QueryRow(ctx, deploymentByID, id)
	var i DeploymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Coalesce,
		&i.ImageDigest,
		&i.Kind,
		&i.SourcePath,
		&i.SourceBytes,
		&i.Handler,
		&i.LogPath,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const domainByName = `-- name: DomainByName :one
select domain, app_id, challenge_token, verified_at
from custom_domains where domain = $1
`

type DomainByNameRow struct {
	Domain         interface{}
	AppID          pgtype.UUID
	ChallengeToken string
	VerifiedAt     pgtype.Timestamptz
}

func (q *Queries) DomainByName(ctx context.Context, db DBTX, domain interface{}) (DomainByNameRow, error) {
	row := db.QueryRow(ctx, domainByName, domain)
	var i DomainByNameRow
	err := row.Scan(
		&i.Domain,
		&i.AppID,
		&i.ChallengeToken,
		&i.VerifiedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
select id, account_id,
       coalesce(host(issued_ip), '') as issued_ip,
       coalesce(issued_ua, '') as issued_ua,
       issued_at, last_seen_at, revoked_at
from sessions where id = $1
`

type GetSessionRow struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	IssuedIp   interface{}
	IssuedUa   string
	IssuedAt   pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

// Primary-key lookup; called on every authenticated dashboard request.
// sql.ErrNoRows from pgx maps to state.ErrNotFound in pgstore.
func (q *Queries) GetSession(ctx context.Context, db DBTX, id pgtype.UUID) (GetSessionRow, error) {
	row := db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IssuedIp,
		&i.IssuedUa,
		&i.IssuedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertComputeNodeHeartbeat = `-- name: InsertComputeNodeHeartbeat :exec
insert into compute_node_heartbeats (node_id, received_at, last_heartbeat_at, source)
values ($1, $2, $3, $4)
`

type InsertComputeNodeHeartbeatParams struct {
	NodeID          pgtype.UUID
	ReceivedAt      pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	Source          string
}

// CP-1 (operator observability): append one row to the heartbeat
// history. The schedd Heartbeat.Tick goroutine is the only writer.
// We deliberately do NOT use ON CONFLICT DO NOTHING — a duplicate
// (node_id, received_at) is observable as a SQLSTATE 23505 unique-
// violation, which the writer logs as a warning. A silently-deduped
// stamp would mask a future bug where the scheduler tick fires twice.
// received_at and last_heartbeat_at are passed by the caller; the
// column default now() is intentionally NOT used so the writer
// controls the wall-clock pair (the property test depends on
// caller-supplied timestamps for deterministic gap classification).
func (q *Queries) InsertComputeNodeHeartbeat(ctx context.Context, db DBTX, arg InsertComputeNodeHeartbeatParams) error {
	_, err := db.Exec(ctx, insertComputeNodeHeartbeat,
		arg.NodeID,
		arg.ReceivedAt,
		arg.LastHeartbeatAt,
		arg.Source,
	)
	return err
}

const instanceByID = `-- name: InstanceByID :one
select id, app_id, deployment_id, state, coalesce(netns, ''), coalesce(guest_uid, 0),
       coalesce(host_ip::text, ''), ram_mb, started_at, last_request_at, parked_at
from instances where id = $1
`

type InstanceByIDRow struct {
	ID            pgtype.UUID
	AppID         pgtype.UUID
	DeploymentID  pgtype.UUID
	State         string
	Netns         string
	GuestUid      int32
	Coalesce      interface{}
	RamMb         int32
	StartedAt     pgtype.Timestamptz
	LastRequestAt pgtype.Timestamptz
	ParkedAt      pgtype.Timestamptz
}

func (q *Queries) InstanceByID(ctx context.Context, db DBTX, id pgtype.UUID) (InstanceByIDRow, error) {
	row := db.QueryRow(ctx, instanceByID, id)
	var i InstanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DeploymentID,
		&i.State,
		&i.Netns,
		&i.GuestUid,
		&i.Coalesce,
		&i.RamMb,
		&i.StartedAt,
		&i.LastRequestAt,
		&i.ParkedAt,
	)
	return i, err
}

const latestDeployment = `-- name: LatestDeployment :one
select id, app_id, coalesce(build_id::text, ''), image_digest, kind,
       coalesce(source_path, ''), coalesce(source_bytes, 0),
       coalesce(handler, ''), coalesce(log_path, ''),
       status, coalesce(error, ''), created_at
from deployments where app_id = $1 order by created_at desc limit 1
`

type LatestDeploymentRow struct {
	ID          pgtype.UUID
	AppID       pgtype.UUID
	Coalesce    interface{}
	ImageDigest string
	Kind        string
	SourcePath  string
	SourceBytes int64
	Handler     string
	LogPath     string
	Status      string
	Error       string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) LatestDeployment(ctx context.Context, db DBTX, appID pgtype.UUID) (LatestDeploymentRow, error) {
	row := db.QueryRow(ctx, latestDeployment, appID)
	var i LatestDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Coalesce,
		&i.ImageDigest,
		&i.Kind,
		&i.SourcePath,
		&i.SourceBytes,
		&i.Handler,
		&i.LogPath,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const latestSupersededDeployment = `-- name: LatestSupersededDeployment :one
select id, app_id, coalesce(build_id::text, ''), image_digest, kind,
       coalesce(source_path, ''), coalesce(source_bytes, 0),
       coalesce(handler, ''), coalesce(log_path, ''),
       status, coalesce(error, ''), created_at
from deployments
where app_id = $1 and status = 'superseded'
order by created_at desc limit 1
`

type LatestSupersededDeploymentRow struct {
	ID          pgtype.UUID
	AppID       pgtype.UUID
	Coalesce    interface{}
	ImageDigest string
	Kind        string
	SourcePath  string
	SourceBytes int64
	Handler     string
	LogPath     string
	Status      string
	Error       string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) LatestSupersededDeployment(ctx context.Context, db DBTX, appID pgtype.UUID) (LatestSupersededDeploymentRow, error) {
	row := db.QueryRow(ctx, latestSupersededDeployment, appID)
	var i LatestSupersededDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Coalesce,
		&i.ImageDigest,
		&i.Kind,
		&i.SourcePath,
		&i.SourceBytes,
		&i.Handler,
		&i.LogPath,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
select id, account_id, key_sha256, coalesce(label, ''), scopes, created_at, coalesce(last_used_at, 'epoch'::timestamptz)
from api_keys where account_id = $1 order by created_at desc
`

type ListAPIKeysRow struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	KeySha256  []byte
	Label      string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

// scopes is the auth permission set surfaced to the dashboard and the
// /v1/keys listing. See ADR-034 rev2.
func (q *Queries) ListAPIKeys(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListAPIKeysRow, error) {
	rows, err := db.Query(ctx, listAPIKeys, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.KeySha256,
			&i.Label,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApps = `-- name: ListApps :many
select id, account_id, slug, type, coalesce(runtime, ''), ram_mb, coalesce(idle_timeout_s, 0),
       max_concurrency, status, manifest, created_at
from apps where account_id = $1 order by created_at desc
`

type ListAppsRow struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	Slug           string
	Type           string
	Runtime        string
	RamMb          int32
	IdleTimeoutS   int32
	MaxConcurrency int32
	Status         string
	Manifest       []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListApps(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListAppsRow, error) {
	rows, err := db.Query(ctx, listApps, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsRow{}
	for rows.Next() {
		var i ListAppsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Slug,
			&i.Type,
			&i.Runtime,
			&i.RamMb,
			&i.IdleTimeoutS,
			&i.MaxConcurrency,
			&i.Status,
			&i.Manifest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComputeNodeHeartbeats = `-- name: ListComputeNodeHeartbeats :many
select id, node_id, received_at, last_heartbeat_at, source
from compute_node_heartbeats
where node_id = $1
  and ($2::timestamptz is null or received_at >= $2)
order by received_at desc
limit $3
`

type ListComputeNodeHeartbeatsParams struct {
	NodeID  pgtype.UUID
	Column2 pgtype.Timestamptz
	Limit   int32
}

// CP-1: read heartbeat history for one node, newest first. The
// $2 parameter is nullable: passing pgtype.Timestamptz{} (the Go
// zero value, mapped to SQL NULL by sqlc) means "no lower bound,
// return most-recent N"; passing a populated timestamptz means
// "history since t". The composite index
// compute_node_heartbeats_node_at_idx (node_id, received_at desc)
// matches this read shape.
//
// The endpoint passes a hard-cap limit (default 200, max 2000). The
// composite index is enough for the routine 30s × 60 nodes × 24h
// steady-state workload; a 7-day retention sweep is a follow-on.
func (q *Queries) ListComputeNodeHeartbeats(ctx context.Context, db DBTX, arg ListComputeNodeHeartbeatsParams) ([]ComputeNodeHeartbeat, error) {
	rows, err := db.Query(ctx, listComputeNodeHeartbeats, arg.NodeID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComputeNodeHeartbeat{}
	for rows.Next() {
		var i ComputeNodeHeartbeat
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ReceivedAt,
			&i.LastHeartbeatAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronsForApp = `-- name: ListCronsForApp :many
select id, app_id, schedule, path, enabled, created_at
from crons where app_id = $1 order by created_at desc
`

type ListCronsForAppRow struct {
	ID        pgtype.UUID
	AppID     pgtype.UUID
	Schedule  string
	Path      string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListCronsForApp(ctx context.Context, db DBTX, appID pgtype.UUID) ([]ListCronsForAppRow, error) {
	rows, err := db.Query(ctx, listCronsForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCronsForAppRow{}
	for rows.Next() {
		var i ListCronsForAppRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Schedule,
			&i.Path,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsForApp = `-- name: ListDeploymentsForApp :many
select id, app_id, coalesce(build_id::text, ''), image_digest, kind,
       coalesce(source_path, ''), coalesce(source_bytes, 0),
       coalesce(handler, ''), coalesce(log_path, ''),
       status, coalesce(error, ''), created_at
from deployments where app_id = $1 order by created_at desc limit $2 offset $3
`

type ListDeploymentsForAppParams struct {
	AppID  pgtype.UUID
	Limit  int32
	Offset int32
}

type ListDeploymentsForAppRow struct {
	ID          pgtype.UUID
	AppID       pgtype.UUID
	Coalesce    interface{}
	ImageDigest string
	Kind        string
	SourcePath  string
	SourceBytes int64
	Handler     string
	LogPath     string
	Status      string
	Error       string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListDeploymentsForApp(ctx context.Context, db DBTX, arg ListDeploymentsForAppParams) ([]ListDeploymentsForAppRow, error) {
	rows, err := db.Query(ctx, listDeploymentsForApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsForAppRow{}
	for rows.Next() {
		var i ListDeploymentsForAppRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Coalesce,
			&i.ImageDigest,
			&i.Kind,
			&i.SourcePath,
			&i.SourceBytes,
			&i.Handler,
			&i.LogPath,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsForAccount = `-- name: ListDomainsForAccount :many
select d.domain, d.app_id, d.challenge_token, d.verified_at
from custom_domains d join apps a on a.id = d.app_id
where a.account_id = $1 order by d.domain
`

type ListDomainsForAccountRow struct {
	Domain         interface{}
	AppID          pgtype.UUID
	ChallengeToken string
	VerifiedAt     pgtype.Timestamptz
}

func (q *Queries) ListDomainsForAccount(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListDomainsForAccountRow, error) {
	rows, err := db.Query(ctx, listDomainsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainsForAccountRow{}
	for rows.Next() {
		var i ListDomainsForAccountRow
		if err := rows.Scan(
			&i.Domain,
			&i.AppID,
			&i.ChallengeToken,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsForApp = `-- name: ListDomainsForApp :many
select domain, app_id, challenge_token, verified_at
from custom_domains where app_id = $1 order by domain
`

type ListDomainsForAppRow struct {
	Domain         interface{}
	AppID          pgtype.UUID
	ChallengeToken string
	VerifiedAt     pgtype.Timestamptz
}

func (q *Queries) ListDomainsForApp(ctx context.Context, db DBTX, appID pgtype.UUID) ([]ListDomainsForAppRow, error) {
	rows, err := db.Query(ctx, listDomainsForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainsForAppRow{}
	for rows.Next() {
		var i ListDomainsForAppRow
		if err := rows.Scan(
			&i.Domain,
			&i.AppID,
			&i.ChallengeToken,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCrons = `-- name: ListEnabledCrons :many
select id, app_id, schedule, path, enabled, created_at
from crons where enabled = true
`

type ListEnabledCronsRow struct {
	ID        pgtype.UUID
	AppID     pgtype.UUID
	Schedule  string
	Path      string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListEnabledCrons(ctx context.Context, db DBTX) ([]ListEnabledCronsRow, error) {
	rows, err := db.Query(ctx, listEnabledCrons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledCronsRow{}
	for rows.Next() {
		var i ListEnabledCronsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Schedule,
			&i.Path,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
select id, at, actor, kind, subject, data
from events where subject = $1 order by at desc limit $2
`

type ListEventsParams struct {
	Subject pgtype.UUID
	Limit   int32
}

func (q *Queries) ListEvents(ctx context.Context, db DBTX, arg ListEventsParams) ([]Event, error) {
	rows, err := db.Query(ctx, listEvents, arg.Subject, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.Kind,
			&i.Subject,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesForApp = `-- name: ListInstancesForApp :many
select id, app_id, deployment_id, state, coalesce(netns, ''), coalesce(guest_uid, 0),
       coalesce(host_ip::text, ''), ram_mb, started_at, last_request_at, parked_at
from instances where app_id = $1 order by started_at desc
`

type ListInstancesForAppRow struct {
	ID            pgtype.UUID
	AppID         pgtype.UUID
	DeploymentID  pgtype.UUID
	State         string
	Netns         string
	GuestUid      int32
	Coalesce      interface{}
	RamMb         int32
	StartedAt     pgtype.Timestamptz
	LastRequestAt pgtype.Timestamptz
	ParkedAt      pgtype.Timestamptz
}

func (q *Queries) ListInstancesForApp(ctx context.Context, db DBTX, appID pgtype.UUID) ([]ListInstancesForAppRow, error) {
	rows, err := db.Query(ctx, listInstancesForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstancesForAppRow{}
	for rows.Next() {
		var i ListInstancesForAppRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.DeploymentID,
			&i.State,
			&i.Netns,
			&i.GuestUid,
			&i.Coalesce,
			&i.RamMb,
			&i.StartedAt,
			&i.LastRequestAt,
			&i.ParkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
select id, account_id,
       coalesce(host(issued_ip), '') as issued_ip,
       coalesce(issued_ua, '') as issued_ua,
       issued_at, last_seen_at, revoked_at
from sessions where account_id = $1 and revoked_at is null
order by issued_at desc
`

type ListSessionsRow struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	IssuedIp   interface{}
	IssuedUa   string
	IssuedAt   pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

// Active rows only, newest first. Partial index keeps the scan tight.
func (q *Queries) ListSessions(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListSessionsRow, error) {
	rows, err := db.Query(ctx, listSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.IssuedIp,
			&i.IssuedUa,
			&i.IssuedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentLive = `-- name: MarkDeploymentLive :exec
update deployments set status = 'live' where id = $1
`

func (q *Queries) MarkDeploymentLive(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, markDeploymentLive, id)
	return err
}

const markDeploymentSuperseded = `-- name: MarkDeploymentSuperseded :exec
update deployments set status = 'superseded' where id = $1
`

func (q *Queries) MarkDeploymentSuperseded(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, markDeploymentSuperseded, id)
	return err
}

const markDomainVerified = `-- name: MarkDomainVerified :exec
update custom_domains set verified_at = now() where domain = $1
`

func (q *Queries) MarkDomainVerified(ctx context.Context, db DBTX, domain interface{}) error {
	_, err := db.Exec(ctx, markDomainVerified, domain)
	return err
}

const revokeAllSessions = `-- name: RevokeAllSessions :many
update sessions set revoked_at = now()
where account_id = $1 and id <> $2 and revoked_at is null
returning id
`

type RevokeAllSessionsParams struct {
	AccountID pgtype.UUID
	ID        pgtype.UUID
}

// Revokes every active row for accountID except the supplied sid
// (the calling session). Returns the revoked ids for audit.
func (q *Queries) RevokeAllSessions(ctx context.Context, db DBTX, arg RevokeAllSessionsParams) ([]pgtype.UUID, error) {
	rows, err := db.Query(ctx, revokeAllSessions, arg.AccountID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
update sessions set revoked_at = coalesce(revoked_at, now())
where id = $1 and account_id = $2 and revoked_at is null
returning id
`

type RevokeSessionParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

// Account-scoped atomic stamp. WHERE includes account_id so a
// cross-account DELETE returns 0 rows (handler maps false → 404) —
// IDOR is a persistence invariant, not a handler check.
// coalesce(revoked_at, now()) makes the call idempotent on already
// revoked rows (returns 0 rows).
func (q *Queries) RevokeSession(ctx context.Context, db DBTX, arg RevokeSessionParams) (pgtype.UUID, error) {
	row := db.QueryRow(ctx, revokeSession, arg.ID, arg.AccountID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setAppManifest = `-- name: SetAppManifest :exec
update apps set manifest = $2 where id = $1
`

type SetAppManifestParams struct {
	ID       pgtype.UUID
	Manifest []byte
}

func (q *Queries) SetAppManifest(ctx context.Context, db DBTX, arg SetAppManifestParams) error {
	_, err := db.Exec(ctx, setAppManifest, arg.ID, arg.Manifest)
	return err
}

const setDeploymentFailed = `-- name: SetDeploymentFailed :one
update deployments
   set status = 'failed', error = $2, error_code = $3
 where id = $1
returning id, app_id, coalesce(build_id::text, ''), image_digest, kind,
          coalesce(source_path, ''), coalesce(source_bytes, 0),
          coalesce(handler, ''), coalesce(log_path, ''),
          coalesce(rootfs_path, ''), coalesce(rootfs_key, ''), coalesce(rootfs_bytes, 0),
          status, coalesce(error, ''), coalesce(error_code, ''), created_at
`

type SetDeploymentFailedParams struct {
	ID        pgtype.UUID
	Error     pgtype.Text
	ErrorCode pgtype.Text
}

type SetDeploymentFailedRow struct {
	ID          pgtype.UUID
	AppID       pgtype.UUID
	Coalesce    interface{}
	ImageDigest string
	Kind        string
	SourcePath  string
	SourceBytes int64
	Handler     string
	LogPath     string
	RootfsPath  string
	RootfsKey   string
	RootfsBytes int64
	Status      string
	Error       string
	ErrorCode   string
	CreatedAt   pgtype.Timestamptz
}

// ADR-021 (G1, image digest enforcement hardening): durable
// carrier for the RFC 7807 failure code that imaged writes when a
// deployment transitions to `failed`. pkg/api.SentinelToCode maps
// the three puller-side sentinels to the codes pkg/api.CodeImage*
// (image_not_found / image_egress_denied / image_manifest_invalid)
// and imaged passes the resulting code as $3 here. The free-text
// error column ($2) is preserved for debugging. Status is pinned
// to 'failed' (caller's status argument is ignored — this is a
// failure-specific helper, not a generic update).
//
// errcode is omitted in the scan (empty string on success means
// "no code mapped"; null in the column means "not yet stamped" —
// both render as "" on the Go side via the coalesce in the SELECT).
func (q *Queries) SetDeploymentFailed(ctx context.Context, db DBTX, arg SetDeploymentFailedParams) (SetDeploymentFailedRow, error) {
	row := db.QueryRow(ctx, setDeploymentFailed, arg.ID, arg.Error, arg.ErrorCode)
	var i SetDeploymentFailedRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Coalesce,
		&i.ImageDigest,
		&i.Kind,
		&i.SourcePath,
		&i.SourceBytes,
		&i.Handler,
		&i.LogPath,
		&i.RootfsPath,
		&i.RootfsKey,
		&i.RootfsBytes,
		&i.Status,
		&i.Error,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const touchKeyLastUsed = `-- name: TouchKeyLastUsed :exec
update api_keys set last_used_at = now() where id = $1
`

func (q *Queries) TouchKeyLastUsed(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, touchKeyLastUsed, id)
	return err
}

const touchSessionLastSeen = `-- name: TouchSessionLastSeen :exec
update sessions set last_seen_at = now() where id = $1
`

// Best-effort, fire-and-forget. Allowed on revoked rows (observability
// signal only; not authorization). pgx interface returns nothing.
func (q *Queries) TouchSessionLastSeen(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, touchSessionLastSeen, id)
	return err
}

const updateAccountPlan = `-- name: UpdateAccountPlan :exec
update accounts set plan = $2 where id = $1
`

type UpdateAccountPlanParams struct {
	ID   pgtype.UUID
	Plan string
}

func (q *Queries) UpdateAccountPlan(ctx context.Context, db DBTX, arg UpdateAccountPlanParams) error {
	_, err := db.Exec(ctx, updateAccountPlan, arg.ID, arg.Plan)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
update accounts set status = $2 where id = $1
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, db DBTX, arg UpdateAccountStatusParams) error {
	_, err := db.Exec(ctx, updateAccountStatus, arg.ID, arg.Status)
	return err
}

const updateApp = `-- name: UpdateApp :one
update apps set
  ram_mb = coalesce($2, ram_mb),
  idle_timeout_s = case when $3::boolean then $4 else idle_timeout_s end,
  max_concurrency = coalesce($5, max_concurrency),
  status = coalesce($6, status)
where id = $1
returning id, account_id, slug, type, coalesce(runtime, ''), ram_mb, coalesce(idle_timeout_s, 0),
          max_concurrency, status, manifest, created_at
`

type UpdateAppParams struct {
	ID             pgtype.UUID
	RamMb          int32
	Column3        bool
	IdleTimeoutS   pgtype.Int4
	MaxConcurrency int32
	Status         string
}

type UpdateAppRow struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	Slug           string
	Type           string
	Runtime        string
	RamMb          int32
	IdleTimeoutS   int32
	MaxConcurrency int32
	Status         string
	Manifest       []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateApp(ctx context.Context, db DBTX, arg UpdateAppParams) (UpdateAppRow, error) {
	row := db.QueryRow(ctx, updateApp,
		arg.ID,
		arg.RamMb,
		arg.Column3,
		arg.IdleTimeoutS,
		arg.MaxConcurrency,
		arg.Status,
	)
	var i UpdateAppRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Type,
		&i.Runtime,
		&i.RamMb,
		&i.IdleTimeoutS,
		&i.MaxConcurrency,
		&i.Status,
		&i.Manifest,
		&i.CreatedAt,
	)
	return i, err
}

const updateBuildStatus = `-- name: UpdateBuildStatus :exec
update builds set
  status = $2,
  failure_class = $3,
  started_at = case when $4::boolean then now() else started_at end,
  finished_at = case when $5::boolean then now() else finished_at end
where id = $1
`

type UpdateBuildStatusParams struct {
	ID           pgtype.UUID
	Status       string
	FailureClass pgtype.Text
	Column4      bool
	Column5      bool
}

func (q *Queries) UpdateBuildStatus(ctx context.Context, db DBTX, arg UpdateBuildStatusParams) error {
	_, err := db.Exec(ctx, updateBuildStatus,
		arg.ID,
		arg.Status,
		arg.FailureClass,
		arg.Column4,
		arg.Column5,
	)
	return err
}

const updateCron = `-- name: UpdateCron :one
update crons set
  schedule = coalesce($2, schedule),
  path = coalesce($3, path),
  enabled = coalesce($4, enabled)
where id = $1
returning id, app_id, schedule, path, enabled, created_at
`

type UpdateCronParams struct {
	ID       pgtype.UUID
	Schedule string
	Path     string
	Enabled  bool
}

type UpdateCronRow struct {
	ID        pgtype.UUID
	AppID     pgtype.UUID
	Schedule  string
	Path      string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateCron(ctx context.Context, db DBTX, arg UpdateCronParams) (UpdateCronRow, error) {
	row := db.QueryRow(ctx, updateCron,
		arg.ID,
		arg.Schedule,
		arg.Path,
		arg.Enabled,
	)
	var i UpdateCronRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Schedule,
		&i.Path,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
update deployments set status = $2, error = $3 where id = $1
`

type UpdateDeploymentStatusParams struct {
	ID     pgtype.UUID
	Status string
	Error  pgtype.Text
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, db DBTX, arg UpdateDeploymentStatusParams) error {
	_, err := db.Exec(ctx, updateDeploymentStatus, arg.ID, arg.Status, arg.Error)
	return err
}

const updateInstanceState = `-- name: UpdateInstanceState :exec
update instances set state = $2 where id = $1
`

type UpdateInstanceStateParams struct {
	ID    pgtype.UUID
	State string
}

func (q *Queries) UpdateInstanceState(ctx context.Context, db DBTX, arg UpdateInstanceStateParams) error {
	_, err := db.Exec(ctx, updateInstanceState, arg.ID, arg.State)
	return err
}

const usageByMonth = `-- name: UsageByMonth :many
select account_id, app_id, month, mb_seconds, cpu_usec, requests, tx_bytes, net_tx_bytes
from usage_monthly
where account_id = $1 and month = $2
order by app_id, month
`

type UsageByMonthParams struct {
	AccountID pgtype.UUID
	Month     pgtype.Interval
}

type UsageByMonthRow struct {
	AccountID pgtype.UUID
	AppID     pgtype.UUID
	Month     pgtype.Interval
	MbSeconds int64
	Requests  int64
}

func (q *Queries) UsageByMonth(ctx context.Context, db DBTX, arg UsageByMonthParams) ([]UsageByMonthRow, error) {
	rows, err := db.Query(ctx, usageByMonth, arg.AccountID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageByMonthRow{}
	for rows.Next() {
		var i UsageByMonthRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AppID,
			&i.Month,
			&i.MbSeconds,
			&i.CpuUsec,
			&i.Requests,
			&i.TxBytes,
			&i.NetTxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
