// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Used by handlers_auth.go so an operator investigating "who signed in
	// as alice?" can identify the key that authenticated. See ADR-034 rev2.
	APIKeyByHash(ctx context.Context, db DBTX, keySha256 []byte) (APIKeyByHashRow, error)
	AccountByEmail(ctx context.Context, db DBTX, email interface{}) (AccountByEmailRow, error)
	AccountByID(ctx context.Context, db DBTX, id pgtype.UUID) (AccountByIDRow, error)
	AccountByKeyHash(ctx context.Context, db DBTX, keySha256 []byte) (AccountByKeyHashRow, error)
	AppByID(ctx context.Context, db DBTX, id pgtype.UUID) (AppByIDRow, error)
	AppBySlug(ctx context.Context, db DBTX, slug string) (AppBySlugRow, error)
	AppendEvent(ctx context.Context, db DBTX, arg AppendEventParams) error
	// Idempotent on (instance_id, minute) for mb_seconds / requests
	// (M7 hardening, PR feat/m7-beta-hardening): a redelivered
	// minute is a no-op for the billing-floor columns so a meterd
	// restart / network blip / two meterd instances cannot inflate
	// billing. cpu_usec, tx_bytes, and net_tx_bytes are ADDITIVE on
	// the same conflict key — the schedd / meterd accumulators can
	// each call AppendUsage many times within the same minute; the
	// columns are the sum of all per-tick deltas.
	//   cpu_usec     — issue #279 / PR-B / ADR-039
	//   tx_bytes     — ADR-046 (gateway HTTP response body bytes)
	//   net_tx_bytes — ADR-046 (root-side vethHost.rx_bytes delta)
	AppendUsage(ctx context.Context, db DBTX, arg AppendUsageParams) error
	BuildByDeployment(ctx context.Context, db DBTX, deploymentID pgtype.UUID) (Build, error)
	BuildByID(ctx context.Context, db DBTX, id pgtype.UUID) (Build, error)
	CountDeployedApps(ctx context.Context, db DBTX, accountID pgtype.UUID) (int64, error)
	// scopes is $4 (text[]). The handler is responsible for validating the
	// scope vocabulary; the store does not. See ADR-034 rev2.
	CreateAPIKey(ctx context.Context, db DBTX, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) (CreateAccountRow, error)
	CreateApp(ctx context.Context, db DBTX, arg CreateAppParams) (CreateAppRow, error)
	CreateBuild(ctx context.Context, db DBTX, arg CreateBuildParams) (Build, error)
	CreateCron(ctx context.Context, db DBTX, arg CreateCronParams) (CreateCronRow, error)
	CreateCustomDomain(ctx context.Context, db DBTX, arg CreateCustomDomainParams) (CreateCustomDomainRow, error)
	CreateDeployment(ctx context.Context, db DBTX, arg CreateDeploymentParams) (CreateDeploymentRow, error)
	CreateInstance(ctx context.Context, db DBTX, arg CreateInstanceParams) (CreateInstanceRow, error)
	// --- Organizations (ADR-061, IAM-6, PR 2) -------------------------------
	//
	// PR 2's sqlc queries cover the deterministic reads + simple writes. The
	// tx-heavy methods (CreateOrg with initial owner membership; RemoveOrgMember
	// with last-owner FOR UPDATE; ConsumeOrgInvitation with cap check + email
	// equality + membership insert + invitation UPDATE in one tx) stay as
	// inline SQL in pgstore.go — they don't fit the :one / :many / :exec
	// sqlc surface cleanly and the existing precedent (CreateAppIfUnderQuota,
	// ConsumeRecoveryCode, ApplyProjectPlan) renders those inline.
	CreateOrg(ctx context.Context, db DBTX, arg CreateOrgParams) (CreateOrgRow, error)
	// IAM-3 (ADR-039, issue #187 + #244 merged). One row per dashboard login.
	// Caller has already generated the uuid (the envelope seal needs the same
	// value). issued_ip is an inet ('' cast to NULL means "RemoteAddr
	// unparseable" — surfaced as "" on read by coalesce(host(...))).
	CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (CreateSessionRow, error)
	CronByID(ctx context.Context, db DBTX, id pgtype.UUID) (CronByIDRow, error)
	DeleteAPIKey(ctx context.Context, db DBTX, arg DeleteAPIKeyParams) error
	// IAM-1 (ADR-034 rev2): delete a key and return the row in one
	// statement so the handler can emit `key.deleted` audit with the
	// dismissed scopes. list_secrets-shaped variant of DeleteAPIKey.
	DeleteAPIKeyReturning(ctx context.Context, db DBTX, arg DeleteAPIKeyReturningParams) (DeleteAPIKeyReturningRow, error)
	DeleteApp(ctx context.Context, db DBTX, id pgtype.UUID) error
	DeleteCron(ctx context.Context, db DBTX, arg DeleteCronParams) error
	DeleteCustomDomain(ctx context.Context, db DBTX, domain interface{}) error
	DeploymentByID(ctx context.Context, db DBTX, id pgtype.UUID) (DeploymentByIDRow, error)
	DomainByName(ctx context.Context, db DBTX, domain interface{}) (DomainByNameRow, error)
	ExpireOrgInvitations(ctx context.Context, db DBTX, expiresAt pgtype.Timestamptz) (int64, error)
	// Primary-key lookup; called on every authenticated dashboard request.
	// sql.ErrNoRows from pgx maps to state.ErrNotFound in pgstore.
	GetSession(ctx context.Context, db DBTX, id pgtype.UUID) (GetSessionRow, error)
	// CP-1 (operator observability): append one row to the heartbeat
	// history. The schedd Heartbeat.Tick goroutine is the only writer.
	// We deliberately do NOT use ON CONFLICT DO NOTHING — a duplicate
	// (node_id, received_at) is observable as a SQLSTATE 23505 unique-
	// violation, which the writer logs as a warning. A silently-deduped
	// stamp would mask a future bug where the scheduler tick fires twice.
	// received_at and last_heartbeat_at are passed by the caller; the
	// column default now() is intentionally NOT used so the writer
	// controls the wall-clock pair (the property test depends on
	// caller-supplied timestamps for deterministic gap classification).
	InsertComputeNodeHeartbeat(ctx context.Context, db DBTX, arg InsertComputeNodeHeartbeatParams) error
	InstanceByID(ctx context.Context, db DBTX, id pgtype.UUID) (InstanceByIDRow, error)
	LatestDeployment(ctx context.Context, db DBTX, appID pgtype.UUID) (LatestDeploymentRow, error)
	LatestSupersededDeployment(ctx context.Context, db DBTX, appID pgtype.UUID) (LatestSupersededDeploymentRow, error)
	// scopes is the auth permission set surfaced to the dashboard and the
	// /v1/keys listing. See ADR-034 rev2.
	ListAPIKeys(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListAPIKeysRow, error)
	ListApps(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListAppsRow, error)
	// CP-1: read heartbeat history for one node, newest first. The
	// $2 parameter is nullable: passing pgtype.Timestamptz{} (the Go
	// zero value, mapped to SQL NULL by sqlc) means "no lower bound,
	// return most-recent N"; passing a populated timestamptz means
	// "history since t". The composite index
	// compute_node_heartbeats_node_at_idx (node_id, received_at desc)
	// matches this read shape.
	//
	// The endpoint passes a hard-cap limit (default 200, max 2000). The
	// composite index is enough for the routine 30s × 60 nodes × 24h
	// steady-state workload; a 7-day retention sweep is a follow-on.
	ListComputeNodeHeartbeats(ctx context.Context, db DBTX, arg ListComputeNodeHeartbeatsParams) ([]ComputeNodeHeartbeat, error)
	ListCronsForApp(ctx context.Context, db DBTX, appID pgtype.UUID) ([]ListCronsForAppRow, error)
	ListDeploymentsForApp(ctx context.Context, db DBTX, arg ListDeploymentsForAppParams) ([]ListDeploymentsForAppRow, error)
	ListDomainsForAccount(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListDomainsForAccountRow, error)
	ListDomainsForApp(ctx context.Context, db DBTX, appID pgtype.UUID) ([]ListDomainsForAppRow, error)
	ListEnabledCrons(ctx context.Context, db DBTX) ([]ListEnabledCronsRow, error)
	ListEvents(ctx context.Context, db DBTX, arg ListEventsParams) ([]ListEventsRow, error)
	// issue #517 / PR-C / ADR-064 — wake-timeline read-side query.
	// Filters on the jsonb expression index events_wake_id_idx
	// (migrations/00114_events_wake_id_idx.sql) and orders by at ASC
	// so the customer-facing timeline endpoint surfaces a forward
	// narrative. The $2 lower bound is the `since` RFC 3339 cursor
	// from the endpoint query string; the $3 limit is bounded to
	// 1000 by the handler. Index path: partial index on
	// (data->>'wake_id') WHERE data->>'wake_id' IS NOT NULL means
	// only rows with a wake_id tag (i.e. the 13 wake.* kinds) are
	// indexed — legacy audit rows are not in scope of PR-C, see
	// ADR-064 §"Compatibility".
	ListEventsByWakeID(ctx context.Context, db DBTX, arg ListEventsByWakeIDParams) ([]ListEventsByWakeIDRow, error)
	ListInstancesForApp(ctx context.Context, db DBTX, appID pgtype.UUID) ([]ListInstancesForAppRow, error)
	ListOrgInvitationsForOrg(ctx context.Context, db DBTX, orgID pgtype.UUID) ([]ListOrgInvitationsForOrgRow, error)
	ListOrgMembers(ctx context.Context, db DBTX, orgID pgtype.UUID) ([]ListOrgMembersRow, error)
	ListOrgsForAccount(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListOrgsForAccountRow, error)
	// Active rows only, newest first. Partial index keeps the scan tight.
	ListSessions(ctx context.Context, db DBTX, accountID pgtype.UUID) ([]ListSessionsRow, error)
	MarkDeploymentLive(ctx context.Context, db DBTX, id pgtype.UUID) error
	MarkDeploymentSuperseded(ctx context.Context, db DBTX, id pgtype.UUID) error
	MarkDomainVerified(ctx context.Context, db DBTX, domain interface{}) error
	OrgByID(ctx context.Context, db DBTX, id pgtype.UUID) (OrgByIDRow, error)
	OrgByPersonalAccount(ctx context.Context, db DBTX, personalOwnerAccountID pgtype.UUID) (OrgByPersonalAccountRow, error)
	OrgBySlug(ctx context.Context, db DBTX, lower string) (OrgBySlugRow, error)
	OrgInvitationByTokenHash(ctx context.Context, db DBTX, tokenHash []byte) (OrgInvitationByTokenHashRow, error)
	OrgMemberByAccount(ctx context.Context, db DBTX, arg OrgMemberByAccountParams) (OrgMemberByAccountRow, error)
	// Revokes every active row for accountID except the supplied sid
	// (the calling session). Returns the revoked ids for audit.
	RevokeAllSessions(ctx context.Context, db DBTX, arg RevokeAllSessionsParams) ([]pgtype.UUID, error)
	// Account-scoped atomic stamp. WHERE includes account_id so a
	// cross-account DELETE returns 0 rows (handler maps false → 404) —
	// IDOR is a persistence invariant, not a handler check.
	// coalesce(revoked_at, now()) makes the call idempotent on already
	// revoked rows (returns 0 rows).
	RevokeSession(ctx context.Context, db DBTX, arg RevokeSessionParams) (pgtype.UUID, error)
	SetAppManifest(ctx context.Context, db DBTX, arg SetAppManifestParams) error
	// ADR-021 (G1, image digest enforcement hardening): durable
	// carrier for the RFC 7807 failure code that imaged writes when a
	// deployment transitions to `failed`. pkg/api.SentinelToCode maps
	// the three puller-side sentinels to the codes pkg/api.CodeImage*
	// (image_not_found / image_egress_denied / image_manifest_invalid)
	// and imaged passes the resulting code as $3 here. The free-text
	// error column ($2) is preserved for debugging. Status is pinned
	// to 'failed' (caller's status argument is ignored — this is a
	// failure-specific helper, not a generic update).
	//
	// errcode is omitted in the scan (empty string on success means
	// "no code mapped"; null in the column means "not yet stamped" —
	// both render as "" on the Go side via the coalesce in the SELECT).
	SetDeploymentFailed(ctx context.Context, db DBTX, arg SetDeploymentFailedParams) (SetDeploymentFailedRow, error)
	SoftDeleteOrg(ctx context.Context, db DBTX, id pgtype.UUID) error
	TouchKeyLastUsed(ctx context.Context, db DBTX, id pgtype.UUID) error
	// Best-effort, fire-and-forget. Allowed on revoked rows (observability
	// signal only; not authorization). pgx interface returns nothing.
	TouchSessionLastSeen(ctx context.Context, db DBTX, id pgtype.UUID) error
	UpdateAccountPlan(ctx context.Context, db DBTX, arg UpdateAccountPlanParams) error
	UpdateAccountStatus(ctx context.Context, db DBTX, arg UpdateAccountStatusParams) error
	UpdateApp(ctx context.Context, db DBTX, arg UpdateAppParams) (UpdateAppRow, error)
	UpdateBuildStatus(ctx context.Context, db DBTX, arg UpdateBuildStatusParams) error
	UpdateCron(ctx context.Context, db DBTX, arg UpdateCronParams) (UpdateCronRow, error)
	UpdateDeploymentStatus(ctx context.Context, db DBTX, arg UpdateDeploymentStatusParams) error
	UpdateInstanceState(ctx context.Context, db DBTX, arg UpdateInstanceStateParams) error
	UpdateOrgPlan(ctx context.Context, db DBTX, arg UpdateOrgPlanParams) error
	UpdateOrgStatus(ctx context.Context, db DBTX, arg UpdateOrgStatusParams) error
	UsageByMonth(ctx context.Context, db DBTX, arg UsageByMonthParams) ([]UsageByMonthRow, error)
}

var _ Querier = (*Queries)(nil)
