-- +goose Up
-- +goose StatementBegin
--
-- 00050_crons_app_full_idx.sql — non-partial index on crons(app_id).
--
-- Background: migration 00002 created a *partial* index
--   crons_app_idx (app_id) WHERE enabled
-- to accelerate schedd's 1-minute ListEnabledCrons scan. PR #340 added
-- CreateCronIfUnderQuota, which runs
--   select count(*) from crons where app_id = $1
-- to enforce the per-app cron cap (Free 0, Hobby 5, Pro 20, Scale 100).
-- A partial index WHERE enabled doesn't help that count: a customer
-- can toggle crons off to dodge the cap, so disabled rows must count.
-- The partial index is silently bypassed when the query's WHERE doesn't
-- imply the index predicate, leaving the count(*) on a heap scan.
--
-- This migration adds a non-partial companion index. Postgres picks
-- whichever index it estimates cheaper for the count (today it's the
-- new one — at Hobby/Pro scale the partial index never matches the
-- count predicate because we count *all* rows for the app). The
-- existing partial index stays because schedd's scan still needs it.
--
-- Slot 00050 is free (last shipped: 00049_account_mfa.sql).
--
-- +goose StatementEnd
create index if not exists crons_app_full_idx on crons (app_id);

-- +goose Down
-- +goose StatementBegin
drop index if exists crons_app_full_idx;
-- +goose StatementEnd