-- +goose Up
-- +goose StatementBegin
--
-- 00056_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- PR #369 (issue #279 PR-C, credit consumption reducer) renumbered
-- to slot 58 after the cross-PR collision detector rejected slots
-- 56 (claimed by open PRs #335 and #352) and 57 (claimed by #335).
-- Without reservations at 56 and 57, the branch's embedded FS would
-- have a gap and TestMigrationsContiguous would fail at PR time.
--
-- PR #335 already carries its own 00056_reserve_slot.sql + 00057_*
-- pair with the same shape; this file and the one below are the
-- canonical pair per ADR-041 — both pairs are intentionally
-- identical and the first one to merge wins.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change. Future-proof against upstream
-- generator drift without chasing each new template revision.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd