-- +goose Up
-- +goose StatementBegin
--
-- 00060_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with no
-- gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Slot history (PR #401, issue #394): PR #401 originally had its real
-- schema at 60 but PRs #399 and #403 both also claimed 60 in the same
-- window — PR #399 with a `_reserve_slot.sql` placeholder, PR #403
-- with a real schema. To clear the cross-PR collision without consuming
-- another real slot, PR #401 renumbered its real schema to 62 then to
-- 64 (PR #399 also claimed 62), with reservation placeholders at 60,
-- 61, and 63 to keep the embedded set contiguous. The Up/Down bodies
-- remain `select 1;` per the carve-out convention.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change. Future-proof against upstream
-- generator drift without chasing each new template revision.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
