-- filename: 00081_reserve_slot.sql
-- +goose Up
-- +goose StatementBegin
--
-- 00081_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Issue #462 PR-A reserves slot 81 at branch creation. PR-A also
-- carries the real migration at 00082; the renumber step in the
-- PR-prep checklist (git ls-tree origin/main -- migrations/)
-- must move both 81 + 82 together if a sibling PR grabs either.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change. Future-proof against upstream
-- generator drift without chasing each new template revision.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
