-- +goose Up
-- +goose StatementBegin
--
-- 00088_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Slot 88 is held by open PR #525 (Tier 3 warm-snapshot) as a
-- REAL migration (apps_warm_snapshot). PR #509 renumbered its
-- 00083 → 00090 + 00084 → 00091 after the cross-PR collision
-- detector found PR #522 had also claimed slot 83. To keep the
-- embedded set contiguous from 1 through 91, slots 87, 88, 89
-- are reserved on PR #509's branch — the cross-PR slot gate hides
-- reservations, so PR #525's real 88/89 do not surface as a
-- collision against these placeholders.
--
-- Whichever PR lands first, the others drop their reservations
-- on rebase. After both PRs land, the 88/89 real schema is
-- authoritative; these reservation files are gone from main.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change. Future-proof against upstream
-- generator drift without chasing each new template revision.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
