-- +goose Up
-- +goose StatementBegin
--
-- 00095_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Slot 95 is held by open PR #529 (Tier A4 cross-node app
-- rebalance, ADR-064) as a real migration. This placeholder keeps
-- PR #526's embedded set contiguous 1..100 without leaving 95/98
-- gaps. The cross-PR slot gate hides reservation files via the
-- slots_from_paths regex carve-out, so simultaneous reservations
-- do not surface as a collision.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
