-- +goose Up
-- +goose StatementBegin
--
-- 00106_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Slot 106 is held by open PR #532 (issue #517 PR-C, ADR-064) as
-- a reservation fence. PR-C's real migration
-- `00107_events_wake_id_idx.sql` rides the +1 offset; this
-- placeholder bridges 105 (PR #536 personal-org backfill on main)
-- and 107 so the embedded set is contiguous from 1 through 108.
--
-- Whichever PR lands first (PR #532 with the 106 reservation
-- and 107 real migration, or PR-D with its own real migration
-- at 106), the other drops its reservation on rebase. The
-- cross-PR slot gate hides reservation files via the
-- slots_from_paths regex carve-out, so the simultaneous
-- reservations do not surface as a collision.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change. Future-proof against upstream
-- generator drift without chasing each new template revision.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd