-- +goose Up
-- +goose StatementBegin
--
-- 00101_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Slot 101 is held by open PR #532 (issue #517 PR-C — canonical
-- wake timeline + structured platform events). The companion real
-- migration is `00101_events_wake_id_idx.sql` on that PR. After
-- PR #532 lands, this reservation file is `git rm`d post-merge
-- per ADR-041 (the slot is then owned by the real 101 migration
-- and 103/104 carry Tier A5 cross-node live-instance migration
-- schema on this PR #533).
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
