-- +goose Up
-- +goose StatementBegin
--
-- 00121_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Slot 121 bridges the gap between PR #547's
-- 00120_warm_hint.sql and this branch's
-- 00122_instances_framework_ready_at. PR #547 jumped to 120
-- after the first rebase onto main (1768ed4b), which forced
-- the renumber chain's 112 → 120 jump to fold into a 112 →
-- 122 jump on this rebase. Whichever side lands first, the
-- other drops its reservation on rebase. The cross-PR slot
-- gate hides reservation files via the slots_from_paths regex
-- carve-out, so the simultaneous reservations do not surface
-- as a collision.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change. Future-proof against upstream
-- generator drift without chasing each new template revision.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd