-- +goose Up
-- +goose StatementBegin
--
-- 00126_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change but does occupy the slot
-- in goose's version table on apply.
--
-- Slot 126 is a partner fence for PR #547 (Tier A7 gatewayd
-- split, open). PR #547 owns the real migration at this slot
-- (00126_pg_ratelimit.sql on that branch); main has nothing at
-- 126. This fence is restored here so the embedded FS stays
-- contiguous 1..127 when PR-B lands alongside PR #547. If PR #547
-- lands first, drop this fence on PR-B's next rebase. If PR-B
-- lands first, drop the equivalent 00126_reserve_slot.sql on
-- PR #547's side.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
