-- +goose Up
-- +goose StatementBegin
--
-- 00162_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Issue #755 / PR-5 (GDPR endpoint hardening) skipped slots 159,
-- 160, 161, and 162 to land at 163 / 164. Slot 162 is held by
-- main's 00162_deployments_live_traffic_idx (issue #556 / PR-B).
-- This 162 fence exists only so PR-5's local embed passes
-- TestMigrationsContiguous before rebase; the real migration is
-- already on main. Drop on rebase: whichever sibling PR claims
-- 162 will collide with this fence and resolve on the next rebase
-- per ADR-041.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd