-- +goose Up
-- +goose StatementBegin
--
-- 00191_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #391 migration gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- Slot 00191 is reserved as a fence against the four-way slot race
-- at slot 191: PRs #797 (already merged at 174), #800
-- (00191_app_secrets_kid), #803 (00191_builds_deployment_started_idx),
-- and #799 (this PR — Edge Rules) all renumbered into the 191
-- neighbourhood. PR #799 (Edge Rules) leapfrogged past 191 to
-- 00192 because both #800 and #803 are claiming 191 for their
-- real migrations; whichever lands first wins. PR #805 already
-- fenced 174-189 on main; #799 extends that pattern with a single
-- 00191 fence to keep the embedded FS contiguous. The fence is
-- removed on the next rebase after whichever PR claiming 191
-- merges per ADR-041.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
