-- +goose Up
-- +goose StatementBegin
--
-- 00200_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / cross-PR gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path beyond goose writing a row to goose_db_version. The
-- replay-safety gate in ci.yml drops files whose basename matches
-- the reservation regex from its "added migration versions"
-- computation (see scripts/ci/check_migration_slots.sh ::
-- reserved_from_paths), so this file is carved out of the
-- cross-PR overlap check.
--
-- Context: PR-A (ADR-090 / app_envs.scope PK widening) renumbered
-- 00198 → 00199 → 00200 → 00201 because PR #819, PR #826, and
-- PR #829 each claimed the next slot up. PR #819 holds 00198
-- (webhook_event_allowlist_cron_fired_manually). PR #826 holds
-- 00199 (compute_node_heartbeats_stats) with a fence at 00198.
-- PR #829 holds 00200 (paddle_overage_pushed_mb_seconds) with
-- fences at 00198 and 00199. PR-A is senior on 00200 (opened
-- 18:46:38Z vs 18:48:55Z) but the cross-PR slot gate treats all
-- real-claim overlaps as collisions regardless of seniority, so
-- PR-A moved to 00201 to clear the gate. This 00200 fence fills
-- the slot between the 00199 fence and PR-A's 00201 real
-- migration to preserve TestMigrationsContiguous on the branch
-- tip. Once PR #829 lands first (more likely — same slot claim
-- already in flight), this fence becomes a duplicate-version
-- collision against PR #829's real migration at 00200 and must
-- be removed in a follow-up commit on this branch.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
