-- +goose Up
-- +goose StatementBegin
--
-- 00204_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / cross-PR gate carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path beyond goose writing a row to goose_db_version. The
-- replay-safety gate in ci.yml drops files whose basename matches
-- the reservation regex from its "added migration versions"
-- computation (see scripts/ci/check_migration_slots.sh ::
-- reserved_from_paths), so this file is carved out of the
-- cross-PR overlap check.
--
-- Context: PR #829 (paddle-overage dedupe pushed_mb_seconds) bumped
-- to slot 00205 because PR #819 (open since 2026-08-10T16:52:56Z,
-- the senior claim) holds slot 00204 for
-- webhook_event_allowlist_cron_fired_manually. PR #829 is junior on
-- 00204, so it carries this 00204_reserve_slot.sql fence to keep
-- TestMigrationsContiguous green on the branch tip before PR #819
-- lands. When PR #819 lands first, this fence becomes a
-- duplicate-version collision against the real migration at slot
-- 00204 and must be removed in a follow-up commit on PR #829. If
-- PR #829 lands first (it must not — PR #819 is senior), the fence
-- survives on main as a no-op until someone cleans it up.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
