-- filename: 00217_reserve_slot.sql
-- +goose Up
-- +goose StatementBegin
-- Reserve slot 217 for PR #849 (ADR-092 app_secrets_scope real
-- migration). Same fence rationale as 00211; see
-- cross-pr-slot-fence-reservation-fence-pattern for the pattern.
--
-- DO NOT bump the slot. If you are claiming this slot for a
-- different feature, fork off the latest main and write your own
-- reserve_slot at the next free number.
SELECT 1;
-- +goose StatementEnd