-- filename: 00215_reserve_slot.sql
-- +goose Up
-- +goose StatementBegin
-- Reserve slot 215 for PR #826 (ADR-092 §3.4 per-node
-- utilization obs, `00215_compute_node_heartbeats_stats.sql`).
-- ADR-092 PR-A renumbered from 00214 to 00216 to avoid the
-- 00214 collision with `00214_edge_rules_kind_validate.sql`
-- (already on origin/main at PR-A authoring time). This fence
-- preserves 00215 for the open PR-826 per-node-utilization
-- lander so the contiguity check
-- (`migrations/embed_test.go::TestMigrationsContiguous`) does
-- not flag a gap, and so PR-A's 00216 lands clean.
--
-- The fence body is `SELECT 1;` per the
-- cross-pr-slot-fence-reservation-fence-pattern.
SELECT 1;
-- +goose StatementEnd