-- filename: 00223_reserve_slot.sql
-- +goose Up
-- +goose StatementBegin
-- Reserve slot 223 as a cross-PR fence. PR #845
-- (ADR-091 D21-D23 / kind=geo) claims slot 00223 with a
-- real migration (00223_edge_rules_kind_geo.sql); this
-- fence is reservation-only per ADR-041 and
-- cross-pr-slot-gate-reservation-fence-pattern, so it does
-- NOT collide with PR #845's slot claim — the slot-check
-- excludes reservation files from the overlap scan. The
-- fence exists on THIS branch so the migrations-contiguous
-- gate passes locally; the actual slot claim lives on PR
-- #845. Once #845 merges into main, the fence here is
-- deleted via `git rm migrations/00223_reserve_slot.sql`
-- (per cross-pr-rebase-fence-deletion-hazard — restore with
-- `git checkout origin/main -- migrations/00223_reserve_slot.sql`
-- if main loses the file).
SELECT 1;
-- +goose StatementEnd