-- filename: 00226_reserve_slot.sql
-- +goose Up
-- +goose StatementBegin
-- Reserve slot 226 for the ADR-098 (connection-aware execution)
-- PR-cluster. The real migration lands as 00226_data_upstreams.sql
-- at PR-A merge base; this fence exists solely to claim the slot
-- ahead of sibling PRs per the cross-pr-slot-fence pagination
-- pattern. Body is a no-op SELECT 1.
--
-- Slot 221 was the original fence; 226 is the post-rebase next-free
-- slot after PR #863 (ADR-096 PR-A, MERGED 2026-08-13) landed
-- 00221_reserve_slot.sql + 00222_app_errors.sql on main, and PR #866
-- (CORS) added 00223 + 00224 + 00225 fences. Main is at 00225; the
-- next free contiguous slot is 00226.
SELECT 1;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
