-- +goose Up
-- +goose StatementBegin
--
-- 00265_reserve_slot.sql — slot reservation placeholder
-- (ADR-041 / PR #906 ADR-101 PR-A slot collision carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- PR #906 (ADR-101 PR-A) renumbered the OIDC tables from 00265 to
-- 00267 + 00266 → 00268 after the cross-PR collision detector
-- rejected 00265 (claimed by PR #887, merged as commit 5ba460ab
-- with `00265_edge_rules_kind_throttle.sql` while PR #906 was
-- still in flight). The branch was forked off main before
-- PR #887's merge, so the reservation is the canonical way to
-- claim the slot for the OIDC PR without rewriting history.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
