-- +goose Up
-- +goose StatementBegin
--
-- 00267_reserve_slot.sql — slot reservation placeholder
-- (ADR-101 / issue #270 PR-A second-renumber carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- PR #906 (ADR-101 PR-A) renumbered the OIDC tables from 00267 →
-- 00269 + 00268 → 00270 after PR #910 (worktree-feat-triggers-mega)
-- claimed slot 00267 with `00267_triggers.sql`. This fence bridges
-- the contiguity chain from 00266 to 00268 in both:
--   * the branch-only tree (which lacks main's 265 + #910's 267)
--   * the PR-merge tree (which has main's 265 but not #910's 267)
--
-- Whichever PR merges first (906 or 910) must drop its 00267 fence
-- in a follow-up commit — when #910 merges, drop ours; when ours
-- merges first, drop #910's 00267_triggers.sql in favour of a
-- renumber (the canonical ADR-041 carve-out is "drop the fence of
-- the merged PR, force the still-open PR to renumber past it").
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
