-- +goose Up
-- +goose StatementBegin
--
-- 00268_reserve_slot.sql — slot reservation placeholder
-- (ADR-101 / issue #270 PR-A second-renumber carve-out).
--
-- This file is a deliberate no-op kept only to satisfy the
-- migrations/embed_test.go::TestMigrationsContiguous requirement
-- that the embedded migration set is exactly {1, 2, …, N} with
-- no gaps. It carries no schema change and does not appear in any
-- apply path (the replay-safety gate in ci.yml drops files whose
-- basename matches the reservation regex from its "added
-- migration versions" computation).
--
-- PR #906 (ADR-101 PR-A) originally picked 00267 + 00268 for the
-- OIDC tables, then renumbered to 00267 → 00269 + 00268 → 00270
-- after PR #910 (worktree-feat-triggers-mega) claimed slot 00267
-- with `00267_triggers.sql`. Slot 00268 was empty so this fence
-- bridges the contiguity chain from main's 00265_edge_rules_kind_throttle.sql
-- + the 00266 fence to the OIDC tables on this branch.
--
-- Body: `select 1;` — executes against the live DB at apply time
-- but produces no schema change.
--
select 1;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- No-op: nothing to reverse (the Up body is a deliberate select 1;).
-- +goose StatementEnd
