-- +goose Up
-- +goose StatementBegin
-- filename: 00319_deployments_actor_validate_fk.sql
--
-- Companion migration to 00318_deployments_actor.sql (PR #992,
-- issue #606 / SAFE-RELEASES-E.1).
--
-- MEDIUM review #3 (PR #992): the FK to accounts(id) was added in
-- 00318 with NOT VALID so the migration didn't full-scan the
-- production deployments table while holding a SHARE ROW EXCLUSIVE
-- lock (which blocks every concurrent apid INSERT). This migration
-- runs the scan, but under SHARE UPDATE EXCLUSIVE — which permits
-- concurrent INSERTs (apid deployment writes continue) and only
-- blocks DDL on the same table.
--
-- Why a separate migration rather than VALIDATE in 00318:
--
--   1. Splitting the apply window is the standard pattern at this
--      scale (migrations/00053, 00206, 00229, 00287 — the NOT VALID
--      + VALIDATE triplet is load-bearing for any ALTER TABLE that
--      adds a constraint on a populated production table).
--
--   2. apid's deployment INSERT path (cmd/apid/handlers.go::
--      createDeployment, handlers_source_ref.go, handlers_source_tarball.go,
--      deploy_inputs.go::createDeploymentMultipart) is the
--      high-frequency writer — the deployment table is the most
--      INSERT-heavy customer-intent surface in the system.
--      Holding even a SHARE UPDATE EXCLUSIVE lock for the duration
--      of a multi-million-row scan is observable to customers
--      (deployments stall). Splitting onto a separate migration
--      lets the operator schedule the VALIDATE window during the
--      platform's quiet hours (cron-driven deploy cadence is
--      lowest at 03:00 UTC).
--
--   3. 00318's replay-safety (DROP+ADD NOT VALID) is independent
--      of 00319's replay-safety (VALIDATE on an already-valid
--      constraint is a catalog no-op). Either migration can be
--      re-applied on its own without coordination.
--
-- The scan is guaranteed safe: pre-#606 deployments never wrote
-- deployed_by_user_id (column was added by 00318 itself), so every
-- existing row is NULL — which is a valid state for an ON DELETE
-- SET NULL FK referencing accounts(id). The scan is a no-op in
-- practice; we still run it so pg_constraint.convalidated=true
-- (the bit future readers query to know the FK is fully enforced
-- against existing rows, not just new ones).

ALTER TABLE deployments
    VALIDATE CONSTRAINT deployments_deployed_by_user_id_fk;
-- +goose StatementEnd

-- +goose Down
-- Forward-only by design: re-validating the constraint after the
-- scan already returned "valid" is a no-op, but the rollback path
-- for an already-validated FK is the same as the rollback for a
-- NOT VALID FK (DROP CONSTRAINT). Both DOWNs of the 00318 + 00319
-- pair converge on dropping the column (which cascades the FK in
-- Postgres 12+). See 00318's Down block for the explicit order.
-- +goose StatementBegin
SELECT 1;
-- +goose StatementEnd