// schedd — the scheduler and instance-lifecycle owner (spec §4.3, ADR-018).
// schedd is the ONLY writer to the `instances` table and the sole owner of the
// state machine (spec §6). This gRPC surface is how gatewayd asks schedd to
// wake an app and reports request activity back; schedd itself dials vmmd
// (api/proto/onebox/faas/vmmd/v1) to drive the actual microVM lifecycle.
//
// Wire discipline mirrors vmmd (ADR-013): checked-in *.pb.go generated with
// paths=source_relative, errors enveloped through pkg/grpcerr, auth is the
// unix-socket DAC model (mode 0660 group `faas`, ADR-015) on
// /run/faas/schedd.sock.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// source: onebox/faas/schedd/v1/schedd.proto

package scheddpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WakeMethod reports whether the wake was a snapshot restore or a cold boot.
// Wire-stable: do NOT reorder; new slots go at the end. Mirrors vmmd's enum so
// the two services agree on the value set.
type WakeMethod int32

const (
	WakeMethod_WAKE_COLD_BOOT WakeMethod = 0
	WakeMethod_WAKE_RESTORE   WakeMethod = 1
)

// Enum value maps for WakeMethod.
var (
	WakeMethod_name = map[int32]string{
		0: "WAKE_COLD_BOOT",
		1: "WAKE_RESTORE",
	}
	WakeMethod_value = map[string]int32{
		"WAKE_COLD_BOOT": 0,
		"WAKE_RESTORE":   1,
	}
)

func (x WakeMethod) Enum() *WakeMethod {
	p := new(WakeMethod)
	*p = x
	return p
}

func (x WakeMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WakeMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_onebox_faas_schedd_v1_schedd_proto_enumTypes[0].Descriptor()
}

func (WakeMethod) Type() protoreflect.EnumType {
	return &file_onebox_faas_schedd_v1_schedd_proto_enumTypes[0]
}

func (x WakeMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WakeMethod.Descriptor instead.
func (WakeMethod) EnumDescriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{0}
}

type WakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// app_id is the apps.id UUID (the gateway resolves host→app before calling).
	AppId         string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeRequest) Reset() {
	*x = WakeRequest{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeRequest) ProtoMessage() {}

func (x *WakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeRequest.ProtoReflect.Descriptor instead.
func (*WakeRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{0}
}

func (x *WakeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type WakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_id is the instances.id row schedd created (or reused).
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// node_id is the compute_node.id (uuid) the instance lives on
	// (issue #98 / ADR-028). The gateway looks up the node's per-node
	// gRPC client via its routing cache and forwards the request via the
	// vmmd ForwardHTTP RPC. Empty only on the error path.
	//
	// Renamed from the legacy `addr` field (PR #116-era was host_ip:8080,
	// an inner-netns placeholder unreachable from gatewayd on a remote
	// host). Dual semantics were deliberately not preserved — leaving
	// both fields risks a caller picking the wrong one and regressing
	// the hot path silently. The new shape is the only contract.
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// method reports what actually happened (a restore that fell back to cold
	// boot per ADR-005 reads WAKE_COLD_BOOT).
	Method WakeMethod `protobuf:"varint,3,opt,name=method,proto3,enum=onebox.faas.schedd.v1.WakeMethod" json:"method,omitempty"`
	// problem carries the RFC 7807 fields on failure. The status code itself is
	// google.rpc.Status via google.golang.org/grpc/status; see pkg/grpcerr. This
	// field mirrors vmmd's WakeResponse and stays unset on success.
	Problem *structpb.Struct `protobuf:"bytes,4,opt,name=problem,proto3" json:"problem,omitempty"`
	// wake_id is the per-wake-attempt correlation handle (gaps analysis
	// 2026-07-23). UUIDv7 minted by schedd at Wake() Phase 2; the
	// gateway propagates it to the client as x-faas-wake-id and the
	// dashboard / CLI surface it. Distinct from instance_id
	// (instances.id row PK) — instance_id is per-row and stable across
	// PARKED → WAKE cycles; wake_id is per-Wake-attempt and fresh on
	// every call (one row can carry many wake_ids). Empty on the
	// Phase-1 fast-path return where the existing RUNNING instance was
	// minted by an earlier wake — gateway can resolve it via
	// PGBackend.InstanceIDForNodeID if needed.
	WakeId        string `protobuf:"bytes,5,opt,name=wake_id,json=wakeId,proto3" json:"wake_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeResponse) Reset() {
	*x = WakeResponse{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeResponse) ProtoMessage() {}

func (x *WakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeResponse.ProtoReflect.Descriptor instead.
func (*WakeResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{1}
}

func (x *WakeResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *WakeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WakeResponse) GetMethod() WakeMethod {
	if x != nil {
		return x.Method
	}
	return WakeMethod_WAKE_COLD_BOOT
}

func (x *WakeResponse) GetProblem() *structpb.Struct {
	if x != nil {
		return x.Problem
	}
	return nil
}

func (x *WakeResponse) GetWakeId() string {
	if x != nil {
		return x.WakeId
	}
	return ""
}

// AdmitInstanceRequest mirrors WakeRequest for the schedule scale-out
// RPC (issue #168). Single field today; kept as a separate message so
// future per-app target hints (placement preference, eager-warm) can
// land on the request without breaking Wake's contract.
type AdmitInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitInstanceRequest) Reset() {
	*x = AdmitInstanceRequest{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitInstanceRequest) ProtoMessage() {}

func (x *AdmitInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitInstanceRequest.ProtoReflect.Descriptor instead.
func (*AdmitInstanceRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{2}
}

func (x *AdmitInstanceRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// AdmitInstanceResponse is the typed result of Engine.AdmitInstance.
// On the admitted path it mirrors WakeResponse minus the `problem`
// field (no failure path here — admission refusal is signalled via
// at_capacity=true in the happy case, or a gRPC status carrying the
// RFC 7807 problem on real errors). On the at-capacity path
// instance_id / node_id / wake_id are unset.
type AdmitInstanceResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	NodeId     string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Method     WakeMethod             `protobuf:"varint,3,opt,name=method,proto3,enum=onebox.faas.schedd.v1.WakeMethod" json:"method,omitempty"`
	WakeId     string                 `protobuf:"bytes,4,opt,name=wake_id,json=wakeId,proto3" json:"wake_id,omitempty"`
	// at_capacity is true when the app was already at effective
	// max_concurrency and no new instance was started. The gateway
	// treats this as a benign no-op when it already has ≥1 cached
	// target. Always false on the admitted path.
	AtCapacity bool `protobuf:"varint,5,opt,name=at_capacity,json=atCapacity,proto3" json:"at_capacity,omitempty"`
	// problem carries the RFC 7807 fields on real failure (RAM
	// headroom, store error, etc). The status code itself is
	// google.rpc.Status via google.golang.org/grpc/status; see
	// pkg/grpcerr. This field mirrors WakeResponse and stays unset on
	// the admitted / at_capacity paths.
	Problem       *structpb.Struct `protobuf:"bytes,6,opt,name=problem,proto3" json:"problem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitInstanceResponse) Reset() {
	*x = AdmitInstanceResponse{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitInstanceResponse) ProtoMessage() {}

func (x *AdmitInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitInstanceResponse.ProtoReflect.Descriptor instead.
func (*AdmitInstanceResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{3}
}

func (x *AdmitInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AdmitInstanceResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AdmitInstanceResponse) GetMethod() WakeMethod {
	if x != nil {
		return x.Method
	}
	return WakeMethod_WAKE_COLD_BOOT
}

func (x *AdmitInstanceResponse) GetWakeId() string {
	if x != nil {
		return x.WakeId
	}
	return ""
}

func (x *AdmitInstanceResponse) GetAtCapacity() bool {
	if x != nil {
		return x.AtCapacity
	}
	return false
}

func (x *AdmitInstanceResponse) GetProblem() *structpb.Struct {
	if x != nil {
		return x.Problem
	}
	return nil
}

// Touch is one instance's most-recent request time.
type Touch struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// unix_ms is the request time in Unix milliseconds.
	UnixMs        int64 `protobuf:"varint,2,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Touch) Reset() {
	*x = Touch{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Touch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Touch) ProtoMessage() {}

func (x *Touch) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Touch.ProtoReflect.Descriptor instead.
func (*Touch) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{4}
}

func (x *Touch) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Touch) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type ReportActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Touches       []*Touch               `protobuf:"bytes,1,rep,name=touches,proto3" json:"touches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportActivityRequest) Reset() {
	*x = ReportActivityRequest{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportActivityRequest) ProtoMessage() {}

func (x *ReportActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportActivityRequest.ProtoReflect.Descriptor instead.
func (*ReportActivityRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{5}
}

func (x *ReportActivityRequest) GetTouches() []*Touch {
	if x != nil {
		return x.Touches
	}
	return nil
}

type ReportActivityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// applied is the number of touches schedd persisted (rows that matched a
	// known instance). Lets the gateway detect a mass mismatch in tests/metrics.
	Applied       int32 `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportActivityResponse) Reset() {
	*x = ReportActivityResponse{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportActivityResponse) ProtoMessage() {}

func (x *ReportActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportActivityResponse.ProtoReflect.Descriptor instead.
func (*ReportActivityResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{6}
}

func (x *ReportActivityResponse) GetApplied() int32 {
	if x != nil {
		return x.Applied
	}
	return 0
}

// ParkInstanceRequest asks schedd to park one instance. The reason
// string flows through to the audit log + park-reason metric.
type ParkInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkInstanceRequest) Reset() {
	*x = ParkInstanceRequest{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkInstanceRequest) ProtoMessage() {}

func (x *ParkInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkInstanceRequest.ProtoReflect.Descriptor instead.
func (*ParkInstanceRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{7}
}

func (x *ParkInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ParkInstanceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ParkInstanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok reports whether the park succeeded. False means the instance
	// was already parked (idempotent) or didn't exist.
	Ok            bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkInstanceResponse) Reset() {
	*x = ParkInstanceResponse{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkInstanceResponse) ProtoMessage() {}

func (x *ParkInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkInstanceResponse.ProtoReflect.Descriptor instead.
func (*ParkInstanceResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{8}
}

func (x *ParkInstanceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// InstanceStatsRow is the schedd-side per-instance stat row that
// meterd reads to compute the per-minute CPU delta. The schema
// mirrors pkg/sched/instancestats.InstanceStat; the wire field
// numbers follow the spec §12 wire convention (additive — new
// slots go at the end).
//
// CPUUsageUsec is cumulative host cgroup CPU-µs since the cgroup
// was created. It is monotonically increasing across the lifetime
// of one cgroup; on a cgroup recreation it resets to a smaller
// number — the caller absorbs the reset (treats the new reading
// as a fresh baseline).
type InstanceStatsRow struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AppId      string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	NodeId     string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsec    uint64                 `protobuf:"varint,4,opt,name=cpu_usec,json=cpuUsec,proto3" json:"cpu_usec,omitempty"`
	// cpu_valid mirrors instancestats.Validity (0 = Valid, 1 =
	// Unknown). Callers MUST skip rows where cpu_valid != 0.
	CpuValid      uint32 `protobuf:"varint,5,opt,name=cpu_valid,json=cpuValid,proto3" json:"cpu_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceStatsRow) Reset() {
	*x = InstanceStatsRow{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatsRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatsRow) ProtoMessage() {}

func (x *InstanceStatsRow) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatsRow.ProtoReflect.Descriptor instead.
func (*InstanceStatsRow) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{9}
}

func (x *InstanceStatsRow) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceStatsRow) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *InstanceStatsRow) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InstanceStatsRow) GetCpuUsec() uint64 {
	if x != nil {
		return x.CpuUsec
	}
	return 0
}

func (x *InstanceStatsRow) GetCpuValid() uint32 {
	if x != nil {
		return x.CpuValid
	}
	return 0
}

type ListInstanceStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstanceStatsRequest) Reset() {
	*x = ListInstanceStatsRequest{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstanceStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstanceStatsRequest) ProtoMessage() {}

func (x *ListInstanceStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstanceStatsRequest.ProtoReflect.Descriptor instead.
func (*ListInstanceStatsRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{10}
}

type ListInstanceStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*InstanceStatsRow    `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstanceStatsResponse) Reset() {
	*x = ListInstanceStatsResponse{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstanceStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstanceStatsResponse) ProtoMessage() {}

func (x *ListInstanceStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstanceStatsResponse.ProtoReflect.Descriptor instead.
func (*ListInstanceStatsResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{11}
}

func (x *ListInstanceStatsResponse) GetRows() []*InstanceStatsRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// StreamAppLogsRequest kicks off a per-app log stream. The schedd
// resolves the live instances via the Instances store table (state.ListInstancesForApp)
// and opens one vmmd Logs RPC per instance; the response carries every
// frame from those streams in arrival order.
//
// since_seq is the per-instance replay cursor: schedd forwards
// since_seq to each vmmd without translation. Each instance's ring
// is independent, so Seq scopes are per-instance, not global.
//
// Additive per ADR-016.
type StreamAppLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// app_id is apps.id (the gateway resolves host→app).
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// since_seq is the per-instance replay cursor. 0 = tail from now.
	// Negative values are treated as 0 by the schedd.
	SinceSeq      int64 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAppLogsRequest) Reset() {
	*x = StreamAppLogsRequest{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAppLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAppLogsRequest) ProtoMessage() {}

func (x *StreamAppLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAppLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamAppLogsRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{12}
}

func (x *StreamAppLogsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StreamAppLogsRequest) GetSinceSeq() int64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

// StreamAppLogsResponse is one frame of the per-app log stream.
// The instance_id is populated so a consumer can interleave
// multi-instance frames deterministically (Move 4 acceptance #5).
//
// Wire is additive: new fields go at the end. The seq/stream/line
// triple mirrors vmmd's LogsResponse; written_at is the host-side
// ingest time, never the guest clock (ADR-022 entropy hazard).
type StreamAppLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_id is the instances.id row the frame came from.
	// Empty on the synthetic "end" terminal frame.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// seq is the per-instance monotonically increasing sequence
	// (vmmd's ring assigns these; schedd does not re-number).
	Seq int64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// stream is "stdout" or "stderr".
	Stream string `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	// line is the byte-stripped log line (no trailing \n).
	Line string `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	// written_at is the host-side time the line was committed to
	// the per-instance ring (RFC 3339 nano).
	WrittenAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAppLogsResponse) Reset() {
	*x = StreamAppLogsResponse{}
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAppLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAppLogsResponse) ProtoMessage() {}

func (x *StreamAppLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_schedd_v1_schedd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAppLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamAppLogsResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP(), []int{13}
}

func (x *StreamAppLogsResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StreamAppLogsResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StreamAppLogsResponse) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *StreamAppLogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *StreamAppLogsResponse) GetWrittenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

var File_onebox_faas_schedd_v1_schedd_proto protoreflect.FileDescriptor

const file_onebox_faas_schedd_v1_schedd_proto_rawDesc = "" +
	"\n" +
	"\"onebox/faas/schedd/v1/schedd.proto\x12\x15onebox.faas.schedd.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\vWakeRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\xcf\x01\n" +
	"\fWakeResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x129\n" +
	"\x06method\x18\x03 \x01(\x0e2!.onebox.faas.schedd.v1.WakeMethodR\x06method\x121\n" +
	"\aproblem\x18\x04 \x01(\v2\x17.google.protobuf.StructR\aproblem\x12\x17\n" +
	"\awake_id\x18\x05 \x01(\tR\x06wakeId\"-\n" +
	"\x14AdmitInstanceRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\xf9\x01\n" +
	"\x15AdmitInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x129\n" +
	"\x06method\x18\x03 \x01(\x0e2!.onebox.faas.schedd.v1.WakeMethodR\x06method\x12\x17\n" +
	"\awake_id\x18\x04 \x01(\tR\x06wakeId\x12\x1f\n" +
	"\vat_capacity\x18\x05 \x01(\bR\n" +
	"atCapacity\x121\n" +
	"\aproblem\x18\x06 \x01(\v2\x17.google.protobuf.StructR\aproblem\"A\n" +
	"\x05Touch\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\aunix_ms\x18\x02 \x01(\x03R\x06unixMs\"O\n" +
	"\x15ReportActivityRequest\x126\n" +
	"\atouches\x18\x01 \x03(\v2\x1c.onebox.faas.schedd.v1.TouchR\atouches\"2\n" +
	"\x16ReportActivityResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\x05R\aapplied\"N\n" +
	"\x13ParkInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"&\n" +
	"\x14ParkInstanceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x9b\x01\n" +
	"\x10InstanceStatsRow\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bcpu_usec\x18\x04 \x01(\x04R\acpuUsec\x12\x1b\n" +
	"\tcpu_valid\x18\x05 \x01(\rR\bcpuValid\"\x1a\n" +
	"\x18ListInstanceStatsRequest\"X\n" +
	"\x19ListInstanceStatsResponse\x12;\n" +
	"\x04rows\x18\x01 \x03(\v2'.onebox.faas.schedd.v1.InstanceStatsRowR\x04rows\"J\n" +
	"\x14StreamAppLogsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x03R\bsinceSeq\"\xb1\x01\n" +
	"\x15StreamAppLogsResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12\x12\n" +
	"\x04line\x18\x04 \x01(\tR\x04line\x129\n" +
	"\n" +
	"written_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\twrittenAt*2\n" +
	"\n" +
	"WakeMethod\x12\x12\n" +
	"\x0eWAKE_COLD_BOOT\x10\x00\x12\x10\n" +
	"\fWAKE_RESTORE\x10\x012\x83\x05\n" +
	"\x06Schedd\x12O\n" +
	"\x04Wake\x12\".onebox.faas.schedd.v1.WakeRequest\x1a#.onebox.faas.schedd.v1.WakeResponse\x12j\n" +
	"\rAdmitInstance\x12+.onebox.faas.schedd.v1.AdmitInstanceRequest\x1a,.onebox.faas.schedd.v1.AdmitInstanceResponse\x12m\n" +
	"\x0eReportActivity\x12,.onebox.faas.schedd.v1.ReportActivityRequest\x1a-.onebox.faas.schedd.v1.ReportActivityResponse\x12g\n" +
	"\fParkInstance\x12*.onebox.faas.schedd.v1.ParkInstanceRequest\x1a+.onebox.faas.schedd.v1.ParkInstanceResponse\x12v\n" +
	"\x11ListInstanceStats\x12/.onebox.faas.schedd.v1.ListInstanceStatsRequest\x1a0.onebox.faas.schedd.v1.ListInstanceStatsResponse\x12l\n" +
	"\rStreamAppLogs\x12+.onebox.faas.schedd.v1.StreamAppLogsRequest\x1a,.onebox.faas.schedd.v1.StreamAppLogsResponse0\x01BFZDgithub.com/onebox-faas/faas/api/proto/onebox/faas/schedd/v1;scheddpbb\x06proto3"

var (
	file_onebox_faas_schedd_v1_schedd_proto_rawDescOnce sync.Once
	file_onebox_faas_schedd_v1_schedd_proto_rawDescData []byte
)

func file_onebox_faas_schedd_v1_schedd_proto_rawDescGZIP() []byte {
	file_onebox_faas_schedd_v1_schedd_proto_rawDescOnce.Do(func() {
		file_onebox_faas_schedd_v1_schedd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_onebox_faas_schedd_v1_schedd_proto_rawDesc), len(file_onebox_faas_schedd_v1_schedd_proto_rawDesc)))
	})
	return file_onebox_faas_schedd_v1_schedd_proto_rawDescData
}

var file_onebox_faas_schedd_v1_schedd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_onebox_faas_schedd_v1_schedd_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_onebox_faas_schedd_v1_schedd_proto_goTypes = []any{
	(WakeMethod)(0),                   // 0: onebox.faas.schedd.v1.WakeMethod
	(*WakeRequest)(nil),               // 1: onebox.faas.schedd.v1.WakeRequest
	(*WakeResponse)(nil),              // 2: onebox.faas.schedd.v1.WakeResponse
	(*AdmitInstanceRequest)(nil),      // 3: onebox.faas.schedd.v1.AdmitInstanceRequest
	(*AdmitInstanceResponse)(nil),     // 4: onebox.faas.schedd.v1.AdmitInstanceResponse
	(*Touch)(nil),                     // 5: onebox.faas.schedd.v1.Touch
	(*ReportActivityRequest)(nil),     // 6: onebox.faas.schedd.v1.ReportActivityRequest
	(*ReportActivityResponse)(nil),    // 7: onebox.faas.schedd.v1.ReportActivityResponse
	(*ParkInstanceRequest)(nil),       // 8: onebox.faas.schedd.v1.ParkInstanceRequest
	(*ParkInstanceResponse)(nil),      // 9: onebox.faas.schedd.v1.ParkInstanceResponse
	(*InstanceStatsRow)(nil),          // 10: onebox.faas.schedd.v1.InstanceStatsRow
	(*ListInstanceStatsRequest)(nil),  // 11: onebox.faas.schedd.v1.ListInstanceStatsRequest
	(*ListInstanceStatsResponse)(nil), // 12: onebox.faas.schedd.v1.ListInstanceStatsResponse
	(*StreamAppLogsRequest)(nil),      // 13: onebox.faas.schedd.v1.StreamAppLogsRequest
	(*StreamAppLogsResponse)(nil),     // 14: onebox.faas.schedd.v1.StreamAppLogsResponse
	(*structpb.Struct)(nil),           // 15: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_onebox_faas_schedd_v1_schedd_proto_depIdxs = []int32{
	0,  // 0: onebox.faas.schedd.v1.WakeResponse.method:type_name -> onebox.faas.schedd.v1.WakeMethod
	15, // 1: onebox.faas.schedd.v1.WakeResponse.problem:type_name -> google.protobuf.Struct
	0,  // 2: onebox.faas.schedd.v1.AdmitInstanceResponse.method:type_name -> onebox.faas.schedd.v1.WakeMethod
	15, // 3: onebox.faas.schedd.v1.AdmitInstanceResponse.problem:type_name -> google.protobuf.Struct
	5,  // 4: onebox.faas.schedd.v1.ReportActivityRequest.touches:type_name -> onebox.faas.schedd.v1.Touch
	10, // 5: onebox.faas.schedd.v1.ListInstanceStatsResponse.rows:type_name -> onebox.faas.schedd.v1.InstanceStatsRow
	16, // 6: onebox.faas.schedd.v1.StreamAppLogsResponse.written_at:type_name -> google.protobuf.Timestamp
	1,  // 7: onebox.faas.schedd.v1.Schedd.Wake:input_type -> onebox.faas.schedd.v1.WakeRequest
	3,  // 8: onebox.faas.schedd.v1.Schedd.AdmitInstance:input_type -> onebox.faas.schedd.v1.AdmitInstanceRequest
	6,  // 9: onebox.faas.schedd.v1.Schedd.ReportActivity:input_type -> onebox.faas.schedd.v1.ReportActivityRequest
	8,  // 10: onebox.faas.schedd.v1.Schedd.ParkInstance:input_type -> onebox.faas.schedd.v1.ParkInstanceRequest
	11, // 11: onebox.faas.schedd.v1.Schedd.ListInstanceStats:input_type -> onebox.faas.schedd.v1.ListInstanceStatsRequest
	13, // 12: onebox.faas.schedd.v1.Schedd.StreamAppLogs:input_type -> onebox.faas.schedd.v1.StreamAppLogsRequest
	2,  // 13: onebox.faas.schedd.v1.Schedd.Wake:output_type -> onebox.faas.schedd.v1.WakeResponse
	4,  // 14: onebox.faas.schedd.v1.Schedd.AdmitInstance:output_type -> onebox.faas.schedd.v1.AdmitInstanceResponse
	7,  // 15: onebox.faas.schedd.v1.Schedd.ReportActivity:output_type -> onebox.faas.schedd.v1.ReportActivityResponse
	9,  // 16: onebox.faas.schedd.v1.Schedd.ParkInstance:output_type -> onebox.faas.schedd.v1.ParkInstanceResponse
	12, // 17: onebox.faas.schedd.v1.Schedd.ListInstanceStats:output_type -> onebox.faas.schedd.v1.ListInstanceStatsResponse
	14, // 18: onebox.faas.schedd.v1.Schedd.StreamAppLogs:output_type -> onebox.faas.schedd.v1.StreamAppLogsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_onebox_faas_schedd_v1_schedd_proto_init() }
func file_onebox_faas_schedd_v1_schedd_proto_init() {
	if File_onebox_faas_schedd_v1_schedd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_onebox_faas_schedd_v1_schedd_proto_rawDesc), len(file_onebox_faas_schedd_v1_schedd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_onebox_faas_schedd_v1_schedd_proto_goTypes,
		DependencyIndexes: file_onebox_faas_schedd_v1_schedd_proto_depIdxs,
		EnumInfos:         file_onebox_faas_schedd_v1_schedd_proto_enumTypes,
		MessageInfos:      file_onebox_faas_schedd_v1_schedd_proto_msgTypes,
	}.Build()
	File_onebox_faas_schedd_v1_schedd_proto = out.File
	file_onebox_faas_schedd_v1_schedd_proto_goTypes = nil
	file_onebox_faas_schedd_v1_schedd_proto_depIdxs = nil
}
