// schedd — the scheduler and instance-lifecycle owner (spec §4.3, ADR-018).
// schedd is the ONLY writer to the `instances` table and the sole owner of the
// state machine (spec §6). This gRPC surface is how gatewayd asks schedd to
// wake an app and reports request activity back; schedd itself dials vmmd
// (api/proto/onebox/faas/vmmd/v1) to drive the actual microVM lifecycle.
//
// Wire discipline mirrors vmmd (ADR-013): checked-in *.pb.go generated with
// paths=source_relative, errors enveloped through pkg/grpcerr, auth is the
// unix-socket DAC model (mode 0660 group `faas`, ADR-015) on
// /run/faas/schedd.sock.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// source: onebox/faas/schedd/v1/schedd.proto

package scheddpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Schedd_Wake_FullMethodName              = "/onebox.faas.schedd.v1.Schedd/Wake"
	Schedd_AdmitInstance_FullMethodName     = "/onebox.faas.schedd.v1.Schedd/AdmitInstance"
	Schedd_ReportActivity_FullMethodName    = "/onebox.faas.schedd.v1.Schedd/ReportActivity"
	Schedd_ParkInstance_FullMethodName      = "/onebox.faas.schedd.v1.Schedd/ParkInstance"
	Schedd_ListInstanceStats_FullMethodName = "/onebox.faas.schedd.v1.Schedd/ListInstanceStats"
	Schedd_StreamAppLogs_FullMethodName     = "/onebox.faas.schedd.v1.Schedd/StreamAppLogs"
	Schedd_StreamWarmHints_FullMethodName   = "/onebox.faas.schedd.v1.Schedd/StreamWarmHints"
)

// ScheddClient is the client API for Schedd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Schedd is the gRPC service schedd exposes on its unix socket. Two RPCs for
// v1.0 — gatewayd is the only caller. Multi-host (Gate-A) replaces the socket
// with mTLS; this ADR-018 surface is per-host.
type ScheddClient interface {
	// Wake ensures an instance for the app is running and returns the address
	// the gateway should proxy to. Blocks for the duration of admission +
	// (restore | cold boot) + readiness. Idempotent: a request for an app that
	// already has a running instance returns that instance's address without a
	// new boot. Admission denial (RAM ceiling / plan concurrency / vCPU slots)
	// returns a ResourceExhausted status carrying the RFC 7807 problem so the
	// gateway can serve a 503 (spec §4.3).
	Wake(ctx context.Context, in *WakeRequest, opts ...grpc.CallOption) (*WakeResponse, error)
	// AdmitInstance attempts to admit ONE additional instance for the app
	// (issue #168). Unlike Wake, this RPC skips the Phase-1 fast-path
	// shortcut so a gateway can demand a new instance even when others
	// are already RUNNING. The gateway uses it to fan-out across
	// max_concurrency without hitting the WakeGate's single-flight
	// coalescing.
	//
	// Three outcomes:
	//
	//   - admitted: a new RUNNING instance was created. instance_id,
	//     node_id, method, wake_id are populated.
	//   - at_capacity: the app is already at effective max_concurrency.
	//     at_capacity=true; instance_id/node_id/wake_id are unset. The
	//     gateway treats this as a benign no-op when it already has ≥1
	//     cached target.
	//   - failure: RAM headroom / chooser / store errors. ResourceExhausted
	//     or Internal status carrying the RFC 7807 problem in `problem`.
	//
	// Stability: the wire is additive — adding at_capacity and a
	// separate request/response message is the only contract change.
	// Existing Wake callers are unaffected.
	AdmitInstance(ctx context.Context, in *AdmitInstanceRequest, opts ...grpc.CallOption) (*AdmitInstanceResponse, error)
	// ReportActivity records per-instance last_request_at touches the gateway
	// batches (spec §4.1 flushes every 15 s). schedd persists them because
	// schedd is the ONLY writer to the `instances` table (CLAUDE.md ownership);
	// the gateway keeps the batch in memory between flushes (ADR-018).
	ReportActivity(ctx context.Context, in *ReportActivityRequest, opts ...grpc.CallOption) (*ReportActivityResponse, error)
	// ParkInstance forces an instance to its parked state. Added in M7 so
	// meterd's Free-tier hard-stop can park every live instance on a
	// suspended account (spec §4.7). Reason is for audit logs ("quota_
	// exceeded_free" etc). Returns Ok on success; ResourceExhausted / NotFound
	// for the obvious error paths.
	ParkInstance(ctx context.Context, in *ParkInstanceRequest, opts ...grpc.CallOption) (*ParkInstanceResponse, error)
	// ListInstanceStats returns the per-instance CPU-µs snapshot the
	// schedd's instancestats.Poller maintains (issue #279 / PR-B).
	// meterdsamp the per-minute CPU delta from this snapshot and
	// writes it to usage_minutes.cpu_usec. Returned rows are the
	// same shape the wire rollup observes (pkg/wire.InstanceStatRow
	// is the typed mirror; the proto is wire-stable so adding a
	// field is additive).
	//
	// CPUUsageUsec is the cumulative host cgroup CPU-µs consumed
	// since the cgroup was created. On a cgroup recreation (jailer
	// restart, manual rmdir) the counter resets to a smaller
	// number — callers must treat the reset as a fresh baseline.
	// CPUValid mirrors instancestats.Validity: 0 = Valid, 1 =
	// Unknown (the vmmd cpustats.Cache has no baseline yet, or a
	// post-regression row). Callers MUST skip rows where CPUValid
	// != 0; otherwise the baseline becomes "stuck" on the pre-
	// regression counter and the per-minute delta is meaningless.
	//
	// Additive: the RPC is the only piece of new wire metadata
	// needed for PR-B. The vmmd Stats RPC already carries the per-
	// instance CPU numbers; this RPC is the schedd-side cache of
	// those numbers, refreshed by the poller every 200 ms.
	ListInstanceStats(ctx context.Context, in *ListInstanceStatsRequest, opts ...grpc.CallOption) (*ListInstanceStatsResponse, error)
	// StreamAppLogs (issue #254 / Move 4) fans out an app's per-instance
	// ring buffers back to the caller as a server-streaming response.
	// schedd is the policy owner and the only component allowed to talk
	// to vmmd directly (CLAUDE.md ownership); apid dials this RPC and
	// multiplexes the per-instance frames into a single SSE response.
	//
	// Two phases mirror vmmd's Logs RPC:
	//
	//  1. Initial page — every line with Seq > since_seq, emitted in
	//     per-instance order (then instance order), so a reconnect
	//     carries the same frame sequence the client last saw.
	//  2. Live tail — schedd subscribes to each live instance's
	//     vmmd Logs stream and emits new lines as they arrive. On
	//     instance death (park/snapshot) the per-instance stream ends
	//     and the next frame is a global "end" event.
	//
	// Wire error mapping:
	//
	//   - codes.NotFound when the app has zero live instances — apid
	//     maps this to its 404 "the app is parked; wake it first"
	//   - codes.Unavailable when the vmmd is unreachable for SOME
	//     instances — apid emits a `degraded` event and keeps the
	//     surviving streams open
	//   - codes.OK + nil on clean shutdown
	//
	// Additive per ADR-016: the field tags on existing messages are
	// untouched; new RPC + new messages append at the end.
	StreamAppLogs(ctx context.Context, in *StreamAppLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamAppLogsResponse], error)
	// StreamWarmHints (ADR-025 axis 4) is the sticky-warm affinity push.
	// schedd is the only writer to pkg/sched.WarmAffinity; every successful
	// admit stamps (app_id → node_id) and we forward the stamp as an event
	// so gatewayd's picker (PGBackend.WarmHintFunc) can bias traffic to the
	// warm node on multi-box fleets.
	//
	// Semantics:
	//   - Server-streaming; gatewayd opens one stream at startup and keeps
	//     it open for the lifetime of the connection.
	//   - "Tail from now": no replay cursor, no snapshot on connect. ADR-005
	//     guarantees an empty hint falls through to least-loaded, so a
	//     gatewayd that reconnects with no hint still routes correctly.
	//   - Events are emitted only on state change (RecordWake actually
	//     changed app_id → node_id); a periodic RecordWake to the same node
	//     is a no-op event-source-wise. The producer filters at emit time.
	//
	// Wire error mapping:
	//   - codes.OK + nil on clean shutdown (caller cancels)
	//   - codes.Canceled when the gateway cancels
	//   - codes.Unavailable for any unexpected drain failure
	//
	// Additive per ADR-016: new RPC + new messages append at the end;
	// existing field tags are untouched.
	StreamWarmHints(ctx context.Context, in *StreamWarmHintsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamWarmHintsResponse], error)
}

type scheddClient struct {
	cc grpc.ClientConnInterface
}

func NewScheddClient(cc grpc.ClientConnInterface) ScheddClient {
	return &scheddClient{cc}
}

func (c *scheddClient) Wake(ctx context.Context, in *WakeRequest, opts ...grpc.CallOption) (*WakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WakeResponse)
	err := c.cc.Invoke(ctx, Schedd_Wake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheddClient) AdmitInstance(ctx context.Context, in *AdmitInstanceRequest, opts ...grpc.CallOption) (*AdmitInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmitInstanceResponse)
	err := c.cc.Invoke(ctx, Schedd_AdmitInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheddClient) ReportActivity(ctx context.Context, in *ReportActivityRequest, opts ...grpc.CallOption) (*ReportActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportActivityResponse)
	err := c.cc.Invoke(ctx, Schedd_ReportActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheddClient) ParkInstance(ctx context.Context, in *ParkInstanceRequest, opts ...grpc.CallOption) (*ParkInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParkInstanceResponse)
	err := c.cc.Invoke(ctx, Schedd_ParkInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheddClient) ListInstanceStats(ctx context.Context, in *ListInstanceStatsRequest, opts ...grpc.CallOption) (*ListInstanceStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstanceStatsResponse)
	err := c.cc.Invoke(ctx, Schedd_ListInstanceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheddClient) StreamAppLogs(ctx context.Context, in *StreamAppLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamAppLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Schedd_ServiceDesc.Streams[0], Schedd_StreamAppLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAppLogsRequest, StreamAppLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Schedd_StreamAppLogsClient = grpc.ServerStreamingClient[StreamAppLogsResponse]

func (c *scheddClient) StreamWarmHints(ctx context.Context, in *StreamWarmHintsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamWarmHintsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Schedd_ServiceDesc.Streams[1], Schedd_StreamWarmHints_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamWarmHintsRequest, StreamWarmHintsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Schedd_StreamWarmHintsClient = grpc.ServerStreamingClient[StreamWarmHintsResponse]

// ScheddServer is the server API for Schedd service.
// All implementations must embed UnimplementedScheddServer
// for forward compatibility.
//
// Schedd is the gRPC service schedd exposes on its unix socket. Two RPCs for
// v1.0 — gatewayd is the only caller. Multi-host (Gate-A) replaces the socket
// with mTLS; this ADR-018 surface is per-host.
type ScheddServer interface {
	// Wake ensures an instance for the app is running and returns the address
	// the gateway should proxy to. Blocks for the duration of admission +
	// (restore | cold boot) + readiness. Idempotent: a request for an app that
	// already has a running instance returns that instance's address without a
	// new boot. Admission denial (RAM ceiling / plan concurrency / vCPU slots)
	// returns a ResourceExhausted status carrying the RFC 7807 problem so the
	// gateway can serve a 503 (spec §4.3).
	Wake(context.Context, *WakeRequest) (*WakeResponse, error)
	// AdmitInstance attempts to admit ONE additional instance for the app
	// (issue #168). Unlike Wake, this RPC skips the Phase-1 fast-path
	// shortcut so a gateway can demand a new instance even when others
	// are already RUNNING. The gateway uses it to fan-out across
	// max_concurrency without hitting the WakeGate's single-flight
	// coalescing.
	//
	// Three outcomes:
	//
	//   - admitted: a new RUNNING instance was created. instance_id,
	//     node_id, method, wake_id are populated.
	//   - at_capacity: the app is already at effective max_concurrency.
	//     at_capacity=true; instance_id/node_id/wake_id are unset. The
	//     gateway treats this as a benign no-op when it already has ≥1
	//     cached target.
	//   - failure: RAM headroom / chooser / store errors. ResourceExhausted
	//     or Internal status carrying the RFC 7807 problem in `problem`.
	//
	// Stability: the wire is additive — adding at_capacity and a
	// separate request/response message is the only contract change.
	// Existing Wake callers are unaffected.
	AdmitInstance(context.Context, *AdmitInstanceRequest) (*AdmitInstanceResponse, error)
	// ReportActivity records per-instance last_request_at touches the gateway
	// batches (spec §4.1 flushes every 15 s). schedd persists them because
	// schedd is the ONLY writer to the `instances` table (CLAUDE.md ownership);
	// the gateway keeps the batch in memory between flushes (ADR-018).
	ReportActivity(context.Context, *ReportActivityRequest) (*ReportActivityResponse, error)
	// ParkInstance forces an instance to its parked state. Added in M7 so
	// meterd's Free-tier hard-stop can park every live instance on a
	// suspended account (spec §4.7). Reason is for audit logs ("quota_
	// exceeded_free" etc). Returns Ok on success; ResourceExhausted / NotFound
	// for the obvious error paths.
	ParkInstance(context.Context, *ParkInstanceRequest) (*ParkInstanceResponse, error)
	// ListInstanceStats returns the per-instance CPU-µs snapshot the
	// schedd's instancestats.Poller maintains (issue #279 / PR-B).
	// meterdsamp the per-minute CPU delta from this snapshot and
	// writes it to usage_minutes.cpu_usec. Returned rows are the
	// same shape the wire rollup observes (pkg/wire.InstanceStatRow
	// is the typed mirror; the proto is wire-stable so adding a
	// field is additive).
	//
	// CPUUsageUsec is the cumulative host cgroup CPU-µs consumed
	// since the cgroup was created. On a cgroup recreation (jailer
	// restart, manual rmdir) the counter resets to a smaller
	// number — callers must treat the reset as a fresh baseline.
	// CPUValid mirrors instancestats.Validity: 0 = Valid, 1 =
	// Unknown (the vmmd cpustats.Cache has no baseline yet, or a
	// post-regression row). Callers MUST skip rows where CPUValid
	// != 0; otherwise the baseline becomes "stuck" on the pre-
	// regression counter and the per-minute delta is meaningless.
	//
	// Additive: the RPC is the only piece of new wire metadata
	// needed for PR-B. The vmmd Stats RPC already carries the per-
	// instance CPU numbers; this RPC is the schedd-side cache of
	// those numbers, refreshed by the poller every 200 ms.
	ListInstanceStats(context.Context, *ListInstanceStatsRequest) (*ListInstanceStatsResponse, error)
	// StreamAppLogs (issue #254 / Move 4) fans out an app's per-instance
	// ring buffers back to the caller as a server-streaming response.
	// schedd is the policy owner and the only component allowed to talk
	// to vmmd directly (CLAUDE.md ownership); apid dials this RPC and
	// multiplexes the per-instance frames into a single SSE response.
	//
	// Two phases mirror vmmd's Logs RPC:
	//
	//  1. Initial page — every line with Seq > since_seq, emitted in
	//     per-instance order (then instance order), so a reconnect
	//     carries the same frame sequence the client last saw.
	//  2. Live tail — schedd subscribes to each live instance's
	//     vmmd Logs stream and emits new lines as they arrive. On
	//     instance death (park/snapshot) the per-instance stream ends
	//     and the next frame is a global "end" event.
	//
	// Wire error mapping:
	//
	//   - codes.NotFound when the app has zero live instances — apid
	//     maps this to its 404 "the app is parked; wake it first"
	//   - codes.Unavailable when the vmmd is unreachable for SOME
	//     instances — apid emits a `degraded` event and keeps the
	//     surviving streams open
	//   - codes.OK + nil on clean shutdown
	//
	// Additive per ADR-016: the field tags on existing messages are
	// untouched; new RPC + new messages append at the end.
	StreamAppLogs(*StreamAppLogsRequest, grpc.ServerStreamingServer[StreamAppLogsResponse]) error
	// StreamWarmHints (ADR-025 axis 4) is the sticky-warm affinity push.
	// schedd is the only writer to pkg/sched.WarmAffinity; every successful
	// admit stamps (app_id → node_id) and we forward the stamp as an event
	// so gatewayd's picker (PGBackend.WarmHintFunc) can bias traffic to the
	// warm node on multi-box fleets.
	//
	// Semantics:
	//   - Server-streaming; gatewayd opens one stream at startup and keeps
	//     it open for the lifetime of the connection.
	//   - "Tail from now": no replay cursor, no snapshot on connect. ADR-005
	//     guarantees an empty hint falls through to least-loaded, so a
	//     gatewayd that reconnects with no hint still routes correctly.
	//   - Events are emitted only on state change (RecordWake actually
	//     changed app_id → node_id); a periodic RecordWake to the same node
	//     is a no-op event-source-wise. The producer filters at emit time.
	//
	// Wire error mapping:
	//   - codes.OK + nil on clean shutdown (caller cancels)
	//   - codes.Canceled when the gateway cancels
	//   - codes.Unavailable for any unexpected drain failure
	//
	// Additive per ADR-016: new RPC + new messages append at the end;
	// existing field tags are untouched.
	StreamWarmHints(*StreamWarmHintsRequest, grpc.ServerStreamingServer[StreamWarmHintsResponse]) error
	mustEmbedUnimplementedScheddServer()
}

// UnimplementedScheddServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheddServer struct{}

func (UnimplementedScheddServer) Wake(context.Context, *WakeRequest) (*WakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Wake not implemented")
}
func (UnimplementedScheddServer) AdmitInstance(context.Context, *AdmitInstanceRequest) (*AdmitInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdmitInstance not implemented")
}
func (UnimplementedScheddServer) ReportActivity(context.Context, *ReportActivityRequest) (*ReportActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportActivity not implemented")
}
func (UnimplementedScheddServer) ParkInstance(context.Context, *ParkInstanceRequest) (*ParkInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParkInstance not implemented")
}
func (UnimplementedScheddServer) ListInstanceStats(context.Context, *ListInstanceStatsRequest) (*ListInstanceStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstanceStats not implemented")
}
func (UnimplementedScheddServer) StreamAppLogs(*StreamAppLogsRequest, grpc.ServerStreamingServer[StreamAppLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamAppLogs not implemented")
}
func (UnimplementedScheddServer) StreamWarmHints(*StreamWarmHintsRequest, grpc.ServerStreamingServer[StreamWarmHintsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamWarmHints not implemented")
}
func (UnimplementedScheddServer) mustEmbedUnimplementedScheddServer() {}
func (UnimplementedScheddServer) testEmbeddedByValue()                {}

// UnsafeScheddServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheddServer will
// result in compilation errors.
type UnsafeScheddServer interface {
	mustEmbedUnimplementedScheddServer()
}

func RegisterScheddServer(s grpc.ServiceRegistrar, srv ScheddServer) {
	// If the following call panics, it indicates UnimplementedScheddServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Schedd_ServiceDesc, srv)
}

func _Schedd_Wake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheddServer).Wake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Schedd_Wake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheddServer).Wake(ctx, req.(*WakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedd_AdmitInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheddServer).AdmitInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Schedd_AdmitInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheddServer).AdmitInstance(ctx, req.(*AdmitInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedd_ReportActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheddServer).ReportActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Schedd_ReportActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheddServer).ReportActivity(ctx, req.(*ReportActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedd_ParkInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParkInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheddServer).ParkInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Schedd_ParkInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheddServer).ParkInstance(ctx, req.(*ParkInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedd_ListInstanceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstanceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheddServer).ListInstanceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Schedd_ListInstanceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheddServer).ListInstanceStats(ctx, req.(*ListInstanceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Schedd_StreamAppLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAppLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScheddServer).StreamAppLogs(m, &grpc.GenericServerStream[StreamAppLogsRequest, StreamAppLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Schedd_StreamAppLogsServer = grpc.ServerStreamingServer[StreamAppLogsResponse]

func _Schedd_StreamWarmHints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamWarmHintsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScheddServer).StreamWarmHints(m, &grpc.GenericServerStream[StreamWarmHintsRequest, StreamWarmHintsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Schedd_StreamWarmHintsServer = grpc.ServerStreamingServer[StreamWarmHintsResponse]

// Schedd_ServiceDesc is the grpc.ServiceDesc for Schedd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Schedd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onebox.faas.schedd.v1.Schedd",
	HandlerType: (*ScheddServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Wake",
			Handler:    _Schedd_Wake_Handler,
		},
		{
			MethodName: "AdmitInstance",
			Handler:    _Schedd_AdmitInstance_Handler,
		},
		{
			MethodName: "ReportActivity",
			Handler:    _Schedd_ReportActivity_Handler,
		},
		{
			MethodName: "ParkInstance",
			Handler:    _Schedd_ParkInstance_Handler,
		},
		{
			MethodName: "ListInstanceStats",
			Handler:    _Schedd_ListInstanceStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAppLogs",
			Handler:       _Schedd_StreamAppLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamWarmHints",
			Handler:       _Schedd_StreamWarmHints_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "onebox/faas/schedd/v1/schedd.proto",
}
