package auth

import (
	"encoding/base32"
	"strings"
	"testing"
	"time"

	"github.com/pquerna/otp"
	"github.com/pquerna/otp/totp"
)

// GenerateSecret returns a 32-char base32 string (160 bits / 5 = 32
// chars, no padding). The exact length is what otpauth:// consumers
// care about; if this drops, every authenticator app rejects the
// enrolling customer as "malformed QR".
func TestGenerateSecret_Shape(t *testing.T) {
	s, err := GenerateSecret()
	if err != nil {
		t.Fatalf("GenerateSecret: %v", err)
	}
	if len(s) != 32 {
		t.Errorf("secret length = %d, want 32", len(s))
	}
	// base32 alphabet: A-Z and 2-7. Lowercase is not legal.
	for i, r := range s {
		if (r < 'A' || r > 'Z') && (r < '2' || r > '7') {
			t.Errorf("secret[%d] = %q, not in base32 alphabet", i, r)
		}
	}
}

// Two calls in a row produce different secrets. The probability of
// collision over 160 bits is 2^-160; this is a smoke test, not a
// statistical one.
func TestGenerateSecret_Uniqueness(t *testing.T) {
	a, _ := GenerateSecret()
	b, _ := GenerateSecret()
	if a == b {
		t.Fatalf("two secrets collide: %q", a)
	}
}

// KeyFromSecret + VerifyCode round-trip: a code generated by
// pquerna/otp at the current step validates against the same
// secret. This is the load-bearing assertion the dashboard flow
// depends on — if KeyFromSecret uses parameters that disagree with
// VerifyCode, every /confirm fails.
func TestKeyFromSecret_VerifyCodeRoundTrip(t *testing.T) {
	secret, err := GenerateSecret()
	if err != nil {
		t.Fatalf("GenerateSecret: %v", err)
	}
	key, err := KeyFromSecret(secret, "alice@example.com")
	if err != nil {
		t.Fatalf("KeyFromSecret: %v", err)
	}
	if key.Issuer() != TOTPIssuer {
		t.Errorf("key.Issuer = %q, want %q", key.Issuer(), TOTPIssuer)
	}
	// Generate a code at the current step.
	now := time.Now().UTC()
	code, err := totp.GenerateCodeCustom(secret, now, totp.ValidateOpts{
		Period:    30,
		Digits:    otp.DigitsSix,
		Algorithm: otp.AlgorithmSHA1,
	})
	if err != nil {
		t.Fatalf("totp.GenerateCodeCustom: %v", err)
	}
	if !VerifyCode(secret, code) {
		t.Errorf("VerifyCode rejected the just-generated code")
	}
}

// VerifyCode rejects a wrong code. Defense-in-depth — the dashboard
// never sends a "wrong" code by construction, but the recovery
// flow does, and a silent accept would be a security regression.
func TestVerifyCode_RejectsWrongCode(t *testing.T) {
	secret, _ := GenerateSecret()
	if VerifyCode(secret, "000000") {
		// Probability of false-positive on a 6-digit code is 1/10^6;
		// a hit here is a real bug in the verify path.
		// We tolerate the case where the "000000" code happens to
		// match the current step (1 in 10^6) by retrying once.
		if VerifyCode(secret, "111111") {
			t.Errorf("VerifyCode accepted two distinct wrong codes")
		}
	}
}

// VerifyCode rejects a malformed code (length != 6). pquerna/otp
// returns an error rather than a bool here, so the verifier must
// funnel both into the same definitive false.
func TestVerifyCode_RejectsMalformed(t *testing.T) {
	secret, _ := GenerateSecret()
	for _, bad := range []string{"", "12345", "1234567", "abcdef"} {
		if VerifyCode(secret, bad) {
			t.Errorf("VerifyCode accepted malformed code %q", bad)
		}
	}
}

// NewRecoveryCodes produces n (10) unique 10-char uppercase base32
// codes. The hashes are SHA-256 of the plaintext and stand in
// opposite order from the plaintext (so an attacker reading the
// hash table can't link which entry corresponds to which code).
func TestNewRecoveryCodes_ShapeAndUniqueness(t *testing.T) {
	plain, hashes, err := NewRecoveryCodes(RecoveryCodeCount)
	if err != nil {
		t.Fatalf("NewRecoveryCodes: %v", err)
	}
	if len(plain) != RecoveryCodeCount {
		t.Errorf("len(plain) = %d, want %d", len(plain), RecoveryCodeCount)
	}
	if len(hashes) != RecoveryCodeCount {
		t.Errorf("len(hashes) = %d, want %d", len(hashes), RecoveryCodeCount)
	}
	seen := make(map[string]struct{}, len(plain))
	for i, p := range plain {
		if len(p) != 10 {
			t.Errorf("plain[%d] length = %d, want 10", i, len(p))
		}
		for _, r := range p {
			if (r < 'A' || r > 'Z') && (r < '2' || r > '7') {
				t.Errorf("plain[%d] = %q, not in uppercase base32 alphabet", i, p)
				break
			}
		}
		if len(hashes[i]) != 32 {
			t.Errorf("hashes[%d] length = %d, want 32 (SHA-256)", i, len(hashes[i]))
		}
		if _, dup := seen[p]; dup {
			t.Errorf("duplicate recovery code %q at index %d", p, i)
		}
		seen[p] = struct{}{}
	}
}

// HashRecoveryCode is case-insensitive: the customer types a code
// from a screenshot on their phone and the comparison should
// accept lowercase. The hash of the uppercase plaintext stored at
// enrollment must match the hash of the lowercase presented code.
func TestHashRecoveryCode_CaseInsensitive(t *testing.T) {
	h1 := HashRecoveryCode("ABCD2345EF")
	h2 := HashRecoveryCode("abcd2345ef")
	if string(h1) != string(h2) {
		t.Errorf("HashRecoveryCode is case-sensitive: %x vs %x", h1, h2)
	}
}

// HashRecoveryCode is the inverse of the SHA-256 step inside
// NewRecoveryCodes: hashing the same plaintext produces the same
// output. This is the property /v1/account/mfa/recover depends on.
func TestHashRecoveryCode_MatchesGenerate(t *testing.T) {
	plain, hashes, err := NewRecoveryCodes(4)
	if err != nil {
		t.Fatalf("NewRecoveryCodes: %v", err)
	}
	for i, p := range plain {
		got := HashRecoveryCode(p)
		if string(got) != string(hashes[i]) {
			t.Errorf("hash[%d] mismatch: %x vs %x", i, got, hashes[i])
		}
	}
}

// QRCode returns non-empty PNG bytes. We don't decode the PNG —
// the authenticator app's QR parsing is the load-bearing end —
// but a zero-byte return is a pretty clear "this code path didn't
// run" sentinel.
func TestQRCode_NonEmpty(t *testing.T) {
	secret, _ := GenerateSecret()
	key, err := KeyFromSecret(secret, "alice@example.com")
	if err != nil {
		t.Fatalf("KeyFromSecret: %v", err)
	}
	png, err := QRCode(key)
	if err != nil {
		t.Fatalf("QRCode: %v", err)
	}
	if len(png) == 0 {
		t.Errorf("QRCode returned 0 bytes")
	}
	// PNG signature: 89 50 4E 47 0D 0A 1A 0A.
	if len(png) >= 8 && string(png[:8]) != "\x89PNG\r\n\x1a\n" {
		t.Errorf("QRCode returned %d bytes but missing PNG signature", len(png))
	}
}

// otpauth URL the dashboard exposes in the MFAEnrollResponse must
// embed the secret + issuer so the customer's authenticator app
// can ingest the URL without scanning the QR. (Backup path for
// dashboards that can't render a PNG — copy-paste URL.)
func TestKeyFromSecret_OtpauthURLShape(t *testing.T) {
	secret, _ := GenerateSecret()
	key, err := KeyFromSecret(secret, "alice@example.com")
	if err != nil {
		t.Fatalf("KeyFromSecret: %v", err)
	}
	u := key.URL()
	if !strings.HasPrefix(u, "otpauth://totp/") {
		t.Errorf("otpauth URL prefix = %q, want otpauth://totp/", u)
	}
	if !strings.Contains(u, "issuer=FaaS") && !strings.Contains(u, "issuer=FaaS%20") {
		t.Errorf("otpauth URL missing issuer=FaaS: %s", u)
	}
	// Secret is the base32-no-pad form, lowercased; the otpauth URL
	// embeds the secret via the standard encoding the RFC defines.
	// We just verify the secret bytes round-trip through base32
	// decode to the entropy we generated.
	// (key.Secret() is the decoded pquerna/otp-internal form.)
	decoded, err := base32.StdEncoding.WithPadding(base32.NoPadding).DecodeString(strings.ToUpper(secret))
	if err != nil {
		t.Fatalf("base32 decode secret: %v", err)
	}
	if len(decoded) != 20 {
		t.Errorf("decoded secret length = %d, want 20", len(decoded))
	}
}
