// vmmd — the only root component, owns firecracker+jailer (spec §4.4, ADR-013,
// ADR-014, ADR-016). All five RPCs map 1:1 to spec §4.4 line 138. Wire shape
// stays narrow: the caller resolves `(app)` into AppSpec; vmmd never queries
// apid or postgres on its own.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// source: onebox/faas/vmmd/v1/vmmd.proto

package vmmdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WakeMethod is whether a wake was a snapshot restore or a cold boot.
// Wire-stable: do NOT reorder. New enum slots go at the end.
type WakeMethod int32

const (
	WakeMethod_WAKE_COLD_BOOT WakeMethod = 0
	WakeMethod_WAKE_RESTORE   WakeMethod = 1
)

// Enum value maps for WakeMethod.
var (
	WakeMethod_name = map[int32]string{
		0: "WAKE_COLD_BOOT",
		1: "WAKE_RESTORE",
	}
	WakeMethod_value = map[string]int32{
		"WAKE_COLD_BOOT": 0,
		"WAKE_RESTORE":   1,
	}
)

func (x WakeMethod) Enum() *WakeMethod {
	p := new(WakeMethod)
	*p = x
	return p
}

func (x WakeMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WakeMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_onebox_faas_vmmd_v1_vmmd_proto_enumTypes[0].Descriptor()
}

func (WakeMethod) Type() protoreflect.EnumType {
	return &file_onebox_faas_vmmd_v1_vmmd_proto_enumTypes[0]
}

func (x WakeMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WakeMethod.Descriptor instead.
func (WakeMethod) EnumDescriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{0}
}

// AppSpec flattens what the caller knows about an app. vmmd stores none of
// it; the proto exists so each request is self-describing and vmmd stays
// stateless about app config (ADR-014).
type AppSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Issue #96 / ADR-025 axis 2 (PR #116): drive0 base + drive1 layer
	// are referenced by StorageBackend keys, not host paths. The wire
	// carries canonical keys (e.g. "base/runtime-node22.ext4",
	// "apps/<slug>/<depID>.ext4"); vmmd resolves them locally via
	// Storage.Get before staging into the jail chroot. The local
	// StorageBackend's Get maps keys to /srv/fc/.../...ext4 the same
	// way the legacy *_path fields did, so single-box behaviour is
	// preserved. The OCI backend resolves keys over HTTP, which is what
	// unblocks multi-node cold-boot on a vmmd that doesn't share
	// /srv/fc with schedd (issue #98).
	BaseKey  string `protobuf:"bytes,1,opt,name=base_key,json=baseKey,proto3" json:"base_key,omitempty"`
	LayerKey string `protobuf:"bytes,2,opt,name=layer_key,json=layerKey,proto3" json:"layer_key,omitempty"`
	// 2 for free/hobby/pro; 4 for Scale.
	VcpuCount int32 `protobuf:"varint,3,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	// plan RAM in MiB (the slice fences at +8 per spec §1).
	MemSizeMib int32 `protobuf:"varint,4,opt,name=mem_size_mib,json=memSizeMib,proto3" json:"mem_size_mib,omitempty"`
	// per-plan egress bandwidth cap in Mbit/s (spec §7). 0 = no cap
	// (legacy callers / disabled path); vmmd applies a tbf qdisc on the
	// host-side veth to enforce Free/Hobby/Pro/Scale (10/25/100/250).
	EgressMbit int32 `protobuf:"varint,5,opt,name=egress_mbit,json=egressMbit,proto3" json:"egress_mbit,omitempty"`
	// Per-key sealed env rows the caller wants loaded into the guest's
	// env (spec §11/G2). Each entry was sealed independently by apid
	// against the host X25519 recipient; vmmd unseals each, merges into
	// a single envelope, and writes /etc/faas/secrets.env on drive1.
	// Empty list = no file written.
	SealedEnv []*SealedSecret `protobuf:"bytes,6,rep,name=sealed_env,json=sealedEnv,proto3" json:"sealed_env,omitempty"`
	// ADR-031 + ADR-032 (tier-2 of the network roadmap): per-app
	// outbound IP allowlist. Each entry is a CIDR string ("1.2.3.0/24"
	// for v4, "2001:db8::/32" for v6). Empty list = no allowlist rule
	// emitted (default behaviour preserved); non-empty → vmmd
	// translates into netns.Config.EgressAllowlist, which emits an
	//
	//	`iifname "tap0" ip daddr { … } accept`
	//
	// rule on the per-netns `ip faas forward` chain AND, for any v6
	// entries, an
	//
	//	`iifname "tap0" ip6 daddr { … } accept`
	//
	// rule on the `ip6 faas forward` chain (per-family table split,
	// ADR-023; the renderer partitions by prefix.Addr().Is4()). Both
	// partitions land after the lateral-movement deny. Non-/0 contract
	// held by the DB trigger `apps_egress_allowlist_cidr` (migration
	// 00033). Plan-gated upstream (Free/Hobby always empty); see
	// pkg/api/limits.go::EgressAllowlistAllowed.
	EgressAllowlist []string `protobuf:"bytes,7,rep,name=egress_allowlist,json=egressAllowlist,proto3" json:"egress_allowlist,omitempty"`
	// app_id (tier-2 PR-B) is the apps.id UUID the instance is being
	// woken for. vmmd stores it on the live Instance so the
	// UpdateEgressAllowlist RPC can walk its live map by app
	// instead of by instance — schedd pushes a single per-app
	// patch, vmmd fans it out to every live instance of the app.
	// Required by CreateColdBoot (the deploy pipeline always knows
	// the app); required by CreateFromSnapshot for parity (the
	// scheduler resolves app → Instance.app_id upstream, so an
	// empty field here is a contract violation surfaced as
	// InvalidArgument).
	AppId         string `protobuf:"bytes,8,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSpec) Reset() {
	*x = AppSpec{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpec) ProtoMessage() {}

func (x *AppSpec) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpec.ProtoReflect.Descriptor instead.
func (*AppSpec) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{0}
}

func (x *AppSpec) GetBaseKey() string {
	if x != nil {
		return x.BaseKey
	}
	return ""
}

func (x *AppSpec) GetLayerKey() string {
	if x != nil {
		return x.LayerKey
	}
	return ""
}

func (x *AppSpec) GetVcpuCount() int32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *AppSpec) GetMemSizeMib() int32 {
	if x != nil {
		return x.MemSizeMib
	}
	return 0
}

func (x *AppSpec) GetEgressMbit() int32 {
	if x != nil {
		return x.EgressMbit
	}
	return 0
}

func (x *AppSpec) GetSealedEnv() []*SealedSecret {
	if x != nil {
		return x.SealedEnv
	}
	return nil
}

func (x *AppSpec) GetEgressAllowlist() []string {
	if x != nil {
		return x.EgressAllowlist
	}
	return nil
}

func (x *AppSpec) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// SealedSecret is one (key, ciphertext) pair from app_secrets. The key is
// the env-var name; the ciphertext is sealed by apid via filippo.io/age
// under the host X25519 recipient. vmmd merges all entries into the
// single envelope file written to drive1.
type SealedSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealedSecret) Reset() {
	*x = SealedSecret{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealedSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealedSecret) ProtoMessage() {}

func (x *SealedSecret) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealedSecret.ProtoReflect.Descriptor instead.
func (*SealedSecret) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{1}
}

func (x *SealedSecret) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SealedSecret) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// SnapshotRef points at the snapshot a caller wants to restore from. The
// bytes live under the canonical StorageBackend key (issue #96, ADR-025
// axis 2); vmmd allocates its own staging tmp via Storage.Get before
// firing the firecracker restore. fc_version + storage_key together pin
// the artifact and the Firecracker binary that produced it (ADR-005).
type SnapshotRef struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	VmstatePath  string                 `protobuf:"bytes,3,opt,name=vmstate_path,json=vmstatePath,proto3" json:"vmstate_path,omitempty"`
	// The Firecracker version the snapshot was made with (ADR-005: pinned).
	// If empty, the daemon uses the running fcVersion (current behaviour).
	FcVersion string `protobuf:"bytes,4,opt,name=fc_version,json=fcVersion,proto3" json:"fc_version,omitempty"`
	// storage_key is the canonical StorageBackend key under which the mem
	// blob lives. The daemon resolves the bytes through the configured
	// StorageBackend and stages them into an os.TempDir() location for
	// the FC restore source.
	StorageKey string `protobuf:"bytes,5,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	// vmstate_storage_key (issue #121, ADR-025 axis 2 slice 4) is the
	// canonical StorageBackend key under which the vmstate blob lives.
	// Semantically optional: empty ⇒ the daemon uses the legacy host
	// vmstate_path; non-empty ⇒ StorageBackend is authoritative and
	// vmstate_path is logged-only metadata. Default-local single-box
	// always sends the empty value so the host-path behaviour is
	// preserved bit-for-bit. Resolution mirrors storage_key via the
	// configured backend (local at FAAS_STORAGE_ROOT/snap/<dep>/vmstate,
	// OCI at repo snap-<dep>, tag vmstate).
	VmstateStorageKey string `protobuf:"bytes,6,opt,name=vmstate_storage_key,json=vmstateStorageKey,proto3" json:"vmstate_storage_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotRef) Reset() {
	*x = SnapshotRef{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRef) ProtoMessage() {}

func (x *SnapshotRef) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRef.ProtoReflect.Descriptor instead.
func (*SnapshotRef) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotRef) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *SnapshotRef) GetVmstatePath() string {
	if x != nil {
		return x.VmstatePath
	}
	return ""
}

func (x *SnapshotRef) GetFcVersion() string {
	if x != nil {
		return x.FcVersion
	}
	return ""
}

func (x *SnapshotRef) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *SnapshotRef) GetVmstateStorageKey() string {
	if x != nil {
		return x.VmstateStorageKey
	}
	return ""
}

// WakeResponse is the common return shape of CreateFromSnapshot and
// CreateColdBoot. The caller receives the lease + netns identity but does
// NOT receive the inner guest networking — that's identical across instances
// (ADR-009) and stays implicit.
type WakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The instance name as it appears in the `instances` table; echoes the
	// request's `instance` field for request logging.
	Instance string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	LeaseUid int32  `protobuf:"varint,2,opt,name=lease_uid,json=leaseUid,proto3" json:"lease_uid,omitempty"` // 20000-29999
	// NetIP string representation; serialise/parse via netip.Addr.String().
	HostIp   string     `protobuf:"bytes,3,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	Netns    string     `protobuf:"bytes,4,opt,name=netns,proto3" json:"netns,omitempty"` // fc-<instance>
	VethHost string     `protobuf:"bytes,5,opt,name=veth_host,json=vethHost,proto3" json:"veth_host,omitempty"`
	VethPeer string     `protobuf:"bytes,6,opt,name=veth_peer,json=vethPeer,proto3" json:"veth_peer,omitempty"`
	Method   WakeMethod `protobuf:"varint,7,opt,name=method,proto3,enum=onebox.faas.vmmd.v1.WakeMethod" json:"method,omitempty"`
	// The PlanWake decision — what the *caller* expected. Method reports what
	// actually happened (e.g. a restore that fell back reads WAKE_COLD_BOOT).
	RequestedMethod WakeMethod `protobuf:"varint,8,opt,name=requested_method,json=requestedMethod,proto3,enum=onebox.faas.vmmd.v1.WakeMethod" json:"requested_method,omitempty"`
	// RFC 7807 fields, populated only on failure. The status code itself is
	// google.rpc.Status via google.golang.org/grpc/status; see pkg/grpcerr.
	Problem       *structpb.Struct `protobuf:"bytes,9,opt,name=problem,proto3" json:"problem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeResponse) Reset() {
	*x = WakeResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeResponse) ProtoMessage() {}

func (x *WakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeResponse.ProtoReflect.Descriptor instead.
func (*WakeResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{3}
}

func (x *WakeResponse) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *WakeResponse) GetLeaseUid() int32 {
	if x != nil {
		return x.LeaseUid
	}
	return 0
}

func (x *WakeResponse) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *WakeResponse) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *WakeResponse) GetVethHost() string {
	if x != nil {
		return x.VethHost
	}
	return ""
}

func (x *WakeResponse) GetVethPeer() string {
	if x != nil {
		return x.VethPeer
	}
	return ""
}

func (x *WakeResponse) GetMethod() WakeMethod {
	if x != nil {
		return x.Method
	}
	return WakeMethod_WAKE_COLD_BOOT
}

func (x *WakeResponse) GetRequestedMethod() WakeMethod {
	if x != nil {
		return x.RequestedMethod
	}
	return WakeMethod_WAKE_COLD_BOOT
}

func (x *WakeResponse) GetProblem() *structpb.Struct {
	if x != nil {
		return x.Problem
	}
	return nil
}

type CreateFromSnapshotRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Instance string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	App      *AppSpec               `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Snapshot *SnapshotRef           `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// Plan (issue #301, ADR-042) is the apps row's owning plan tier.
	// Drives the per-plan cgroup hierarchy
	// (faas-tenant.slice/<plan-slice>/<instance>) and the cpu.weight /
	// cpu.max enforcement. Empty = legacy 2-level path (pre-#301
	// callers); new callers must always populate this.
	Plan string `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	// AccountID (issue #301, ADR-042) is the apps row's owning
	// account id. Threads onto the wire so vmmd can label the
	// vmmd_cpu_throttle_seconds_total{account_id, app_id} counter
	// and the throttle top-N admission primitive (topAppSet, cap
	// 100). Empty = "anonymous" admission (matches the requestTotal
	// overflow policy).
	AccountId     string `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFromSnapshotRequest) Reset() {
	*x = CreateFromSnapshotRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFromSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFromSnapshotRequest) ProtoMessage() {}

func (x *CreateFromSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFromSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateFromSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFromSnapshotRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *CreateFromSnapshotRequest) GetApp() *AppSpec {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *CreateFromSnapshotRequest) GetSnapshot() *SnapshotRef {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *CreateFromSnapshotRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *CreateFromSnapshotRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type CreateColdBootRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Instance string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	App      *AppSpec               `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	// Build carries the builder-VM specifics. Nil for app VMs (the common case).
	// vmmd branches on presence: with Build set, the chroot is registered for
	// drive1 export during Destroy and the build manifest is left untouched on
	// drive1 (builderd's CreateBuildDrive1 wrote it). Spec §4.5, ADR-003.
	Build *BuildSpec `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	// Plan (issue #301, ADR-042) — same semantics as
	// CreateFromSnapshotRequest.plan. Empty = legacy 2-level path;
	// new callers must always populate this.
	Plan string `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	// AccountID (issue #301, ADR-042) — same semantics as
	// CreateFromSnapshotRequest.account_id.
	AccountId     string `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColdBootRequest) Reset() {
	*x = CreateColdBootRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColdBootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColdBootRequest) ProtoMessage() {}

func (x *CreateColdBootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColdBootRequest.ProtoReflect.Descriptor instead.
func (*CreateColdBootRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{5}
}

func (x *CreateColdBootRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *CreateColdBootRequest) GetApp() *AppSpec {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *CreateColdBootRequest) GetBuild() *BuildSpec {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *CreateColdBootRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *CreateColdBootRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// BuildSpec identifies an instance as a builder VM. vmmd's Destroy waits for
// the firecracker child to exit, captures its exit code, and copies
// /etc/faas/build-done.json + /build/out/* out of the chroot into ExportDir
// before removing the chroot. Builderd writes BuildManifest (BuildManifestPath)
// onto drive1 at CreateColdBoot time so guest-init can read it once the VM is up.
type BuildSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host directory vmmd populates during Destroy with:
	//
	//	<export_dir>/build-done.json
	//	<export_dir>/build/out/image.tar  (and any siblings)
	//
	// Required for builder VMs; ignored otherwise. vmmd refuses export > MaxExportedLayerBytes.
	ExportDir     string `protobuf:"bytes,1,opt,name=export_dir,json=exportDir,proto3" json:"export_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSpec) Reset() {
	*x = BuildSpec{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSpec) ProtoMessage() {}

func (x *BuildSpec) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSpec.ProtoReflect.Descriptor instead.
func (*BuildSpec) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{6}
}

func (x *BuildSpec) GetExportDir() string {
	if x != nil {
		return x.ExportDir
	}
	return ""
}

type PauseAndSnapshotRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Instance    string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	VmstatePath string                 `protobuf:"bytes,3,opt,name=vmstate_path,json=vmstatePath,proto3" json:"vmstate_path,omitempty"`
	// storage_key (issue #96, ADR-025 axis 2) is the canonical StorageBackend
	// key the mem blob is published under after the snapshot. The daemon
	// stores via the configured StorageBackend; vmmstate_path is the
	// resolved-on-host location vmmd hands the firecracker socket to
	// while pausing, then publishes under its own StorageBackend key.
	StorageKey string `protobuf:"bytes,4,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	// vmstate_storage_key (issue #121, ADR-025 axis 2 slice 4) is the
	// canonical StorageBackend key the vmstate blob is published under
	// after the snapshot. Semantically optional: empty ⇒ the daemon
	// writes the snapshot to the legacy host vmstate_path (single-box
	// / default-local behaviour, unchanged); non-empty ⇒ the daemon
	// streams the vmstate bytes through the configured StorageBackend
	// and vmstate_path is logged-only metadata. Resolution mirrors
	// storage_key (local at FAAS_STORAGE_ROOT/snap/<dep>/vmstate, OCI
	// at repo snap-<dep>, tag vmstate).
	VmstateStorageKey string `protobuf:"bytes,5,opt,name=vmstate_storage_key,json=vmstateStorageKey,proto3" json:"vmstate_storage_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PauseAndSnapshotRequest) Reset() {
	*x = PauseAndSnapshotRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseAndSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseAndSnapshotRequest) ProtoMessage() {}

func (x *PauseAndSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseAndSnapshotRequest.ProtoReflect.Descriptor instead.
func (*PauseAndSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{7}
}

func (x *PauseAndSnapshotRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *PauseAndSnapshotRequest) GetVmstatePath() string {
	if x != nil {
		return x.VmstatePath
	}
	return ""
}

func (x *PauseAndSnapshotRequest) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *PauseAndSnapshotRequest) GetVmstateStorageKey() string {
	if x != nil {
		return x.VmstateStorageKey
	}
	return ""
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemBytes      int64                  `protobuf:"varint,1,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	VmstateBytes  int64                  `protobuf:"varint,2,opt,name=vmstate_bytes,json=vmstateBytes,proto3" json:"vmstate_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotResponse) GetMemBytes() int64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *SnapshotResponse) GetVmstateBytes() int64 {
	if x != nil {
		return x.VmstateBytes
	}
	return 0
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{9}
}

func (x *DestroyRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type DestroyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoed for callers that batch destroys and want a confirmation record.
	// Successful destroys produce an empty `problem` field.
	Instance string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Populated for builder VMs from the firecracker child's exit status (the
	// build's own exit code; 137 = OOM, 124 = timeout, etc — see
	// pkg/builderd/builderd.go failure-class table). 0 for app VMs.
	ExitCode      int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyResponse) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *DestroyResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{11}
}

type StatsResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	LiveCount   int32                  `protobuf:"varint,1,opt,name=live_count,json=liveCount,proto3" json:"live_count,omitempty"`
	LeasedCount int32                  `protobuf:"varint,2,opt,name=leased_count,json=leasedCount,proto3" json:"leased_count,omitempty"`
	// Optional so unset != 0 (Int64Value = 0 vs absent differs in prom metrics).
	TotalResidentBytes *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=total_resident_bytes,json=totalResidentBytes,proto3" json:"total_resident_bytes,omitempty"`
	Instances          []*InstanceStats       `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{12}
}

func (x *StatsResponse) GetLiveCount() int32 {
	if x != nil {
		return x.LiveCount
	}
	return 0
}

func (x *StatsResponse) GetLeasedCount() int32 {
	if x != nil {
		return x.LeasedCount
	}
	return 0
}

func (x *StatsResponse) GetTotalResidentBytes() *wrapperspb.Int64Value {
	if x != nil {
		return x.TotalResidentBytes
	}
	return nil
}

func (x *StatsResponse) GetInstances() []*InstanceStats {
	if x != nil {
		return x.Instances
	}
	return nil
}

type InstanceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	LeaseUid      int32                  `protobuf:"varint,2,opt,name=lease_uid,json=leaseUid,proto3" json:"lease_uid,omitempty"`
	HostIp        string                 `protobuf:"bytes,3,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	ResidentBytes *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=resident_bytes,json=residentBytes,proto3" json:"resident_bytes,omitempty"`
	// Issue #170 (PR-A, observability slice): host cgroup CPU percent
	// (cpu.stat usage_usec delta over wall clock, * 100). Wrapper so
	// "absent" means "first sample, non-Linux, or transient cgroup
	// miss" — distinct from a real 0% reading. The schedd poller
	// treats absent as Unknown and excludes it from the
	// {app,node}-rolled-up Prometheus series until two valid samples
	// are observed. Field is additive per ADR-016 (frozen wire shape)
	// — see docs/adr/036-instance-metrics-cardinality-rollups.md.
	CpuPct *wrapperspb.DoubleValue `protobuf:"bytes,5,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	// PR-B (CPU-hour visibility, no billing): cumulative CPU-seconds
	// consumed by this instance's cgroup since the cache was last
	// reset, i.e. Σ(usage_usec delta) / 1e6 across the cpustats
	// cache's lifetime. The value resets when the cache detects a
	// cgroup recreation (usage_usec regression) — this is the
	// documented per-instance regression contract from the schedd
	// poller (pkg/sched/instancestats/poller.go). Absent on the wire
	// when the cache has no baseline for this instance. Rollup
	// semantics: schedd sums this across siblings of one (app,node)
	// into a monotonic CounterVec (cpu_seconds is cumulative work,
	// not a per-tick gauge). The field is additive and informational;
	// no billing path consumes it yet (issue #279 follow-up).
	CpuSeconds *wrapperspb.DoubleValue `protobuf:"bytes,8,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	// PR-D (issue #301, ADR-042): cumulative CPU-throttled seconds
	// consumed by this instance's cgroup since the cpustats cache
	// was last reset, i.e. Σ(throttled_usec delta) / 1e6 across
	// the cache's lifetime. Reads from the same cpu.stat file as
	// cpu_seconds (same regression contract — absents on baseline
	// or regression; resets when the cache detects a cgroup
	// recreation). Wire unit is seconds (matches the
	// vmmd_cpu_throttle_seconds_total Prometheus counter); the
	// cgroupstats.Sample carries the raw microsecond counter, the
	// cpustats cache converts. schedd's poller does NOT roll up
	// this field into the {account_id, app_id} counter — that
	// rollup lives in pkg/wire/topn_app.go's topAppSet admission
	// (capacity 100 hottest apps) so the wire shape stays
	// per-instance and the cardinality on the Prometheus side
	// stays bounded.
	CpuThrottledSeconds *wrapperspb.DoubleValue `protobuf:"bytes,9,opt,name=cpu_throttled_seconds,json=cpuThrottledSeconds,proto3" json:"cpu_throttled_seconds,omitempty"`
	// Inflight HTTP forward count from vmmd's ActivityTracker. Zero
	// is a real value ("no requests in flight right now") and is
	// distinct from the empty wire state only by reader-side
	// Validity, not the proto. Populated by PR-B.
	InflightRequests int64 `protobuf:"varint,6,opt,name=inflight_requests,json=inflightRequests,proto3" json:"inflight_requests,omitempty"`
	// Latest ForwardHTTP start time. Zero (1970-01-01) means "no
	// request observed yet on this instance" — the poller falls back
	// to state.Instance.LastRequestAt in that case.
	LastRequestAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_request_at,json=lastRequestAt,proto3" json:"last_request_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceStats) Reset() {
	*x = InstanceStats{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStats) ProtoMessage() {}

func (x *InstanceStats) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStats.ProtoReflect.Descriptor instead.
func (*InstanceStats) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{13}
}

func (x *InstanceStats) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *InstanceStats) GetLeaseUid() int32 {
	if x != nil {
		return x.LeaseUid
	}
	return 0
}

func (x *InstanceStats) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *InstanceStats) GetResidentBytes() *wrapperspb.Int64Value {
	if x != nil {
		return x.ResidentBytes
	}
	return nil
}

func (x *InstanceStats) GetCpuPct() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CpuPct
	}
	return nil
}

func (x *InstanceStats) GetCpuSeconds() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CpuSeconds
	}
	return nil
}

func (x *InstanceStats) GetCpuThrottledSeconds() *wrapperspb.DoubleValue {
	if x != nil {
		return x.CpuThrottledSeconds
	}
	return nil
}

func (x *InstanceStats) GetInflightRequests() int64 {
	if x != nil {
		return x.InflightRequests
	}
	return 0
}

func (x *InstanceStats) GetLastRequestAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRequestAt
	}
	return nil
}

// PingRequest is intentionally empty. Ping is a liveness probe; the
// request body carries nothing beyond what the gRPC method itself
// implies. Reserved for future use (operator-supplied challenge
// nonce, etc.) without bumping the wire version.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{14}
}

// PingResponse carries the Firecracker version + server-side
// timestamp. fc_version lets schedd's admin surface show "this node
// runs FC 1.10.x" without a separate Stats call; server_time is
// informational (the heartbeat loop stamps last_heartbeat_at
// against its own clock, not this field).
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FcVersion     string                 `protobuf:"bytes,1,opt,name=fc_version,json=fcVersion,proto3" json:"fc_version,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{15}
}

func (x *PingResponse) GetFcVersion() string {
	if x != nil {
		return x.FcVersion
	}
	return ""
}

func (x *PingResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// ForwardHTTPRequest is gatewayd→vmmd for one HTTP request. The wire
// shape mirrors a request line + headers + body. Headers are
// repeated for natural grpc compatibility (headers can repeat in
// HTTP/1.1). The body is bounded by ForwardMaxBodyBytes (25 MiB) —
// gatewayd refuses upstream bodies larger than that before sending.
type ForwardHTTPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The compute_node-relative instance id (instances.id, scoped to a
	// node). vmmd resolves the netns from this.
	Instance string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// HTTP method: GET, POST, HEAD, PUT, DELETE, OPTIONS, PATCH.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Request-target — path?query, e.g. "/api/v1/items?id=42".
	RequestUri string `protobuf:"bytes,3,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	// Headers, in order. Each entry is one header line. Multi-valued
	// headers are repeated (HTTP/1.1 allows). Gatewayd MUST drop
	// hop-by-hop headers (Connection, Transfer-Encoding, etc.) before
	// sending — see pkg/gateway/forwardproxy.go's stripHopByHop.
	Headers []*Header `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	// Request body. Capped at ForwardMaxBodyBytes. vmmd treats an empty
	// body as zero-length, not missing.
	Body          []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardHTTPRequest) Reset() {
	*x = ForwardHTTPRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardHTTPRequest) ProtoMessage() {}

func (x *ForwardHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardHTTPRequest.ProtoReflect.Descriptor instead.
func (*ForwardHTTPRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{16}
}

func (x *ForwardHTTPRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ForwardHTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ForwardHTTPRequest) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *ForwardHTTPRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardHTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Header is one (name, value) HTTP header line. Both fields are
// bytes-rather-than-string so non-ASCII values survive the round
// trip without proto-text round-trip surprises.
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{17}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ForwardHTTPResponse is what vmmd returns. Status carries the
// numeric HTTP status code; headers are the upstream response
// headers; body is the response body (also capped). On a vmmd-side
// failure (cannot reach guest, guest 500, nsenter EIO) the handler
// returns a gRPC status instead — the proto envelope here is the
// success path only.
type ForwardHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*Header              `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardHTTPResponse) Reset() {
	*x = ForwardHTTPResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardHTTPResponse) ProtoMessage() {}

func (x *ForwardHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardHTTPResponse.ProtoReflect.Descriptor instead.
func (*ForwardHTTPResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{18}
}

func (x *ForwardHTTPResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ForwardHTTPResponse) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardHTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HeartbeatRequest and HeartbeatResponse are intentionally empty:
// the heartbeat is a presence-only ping. Schedd measures the round
// trip itself; vmmd reports nothing. We keep the envelopes
// (vs. reusing google.protobuf.Empty) so future fields — e.g. a
// "what's your RAM headroom right now" piggyback — can be added
// without a wire version bump on a hot path.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{19}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{20}
}

// UpdateEgressAllowlistRequest is the input to UpdateEgressAllowlist.
// app_id is the instances.app_id (the app whose live instances
// need the new ruleset). egress_allowlist is the new per-app
// outbound IP allowlist in the same shape as AppSpec.egress_allowlist
// (a comma-free repeated string of CIDRs; v4 + v6 mixed allowed;
// the renderer partitions by prefix.Addr().Is4()). Empty list
// = clear the allowlist (the chain-policy flips back to accept).
//
// The wire does not include an `egress_allowlist_version` field —
// the in-place patch is the only contract; cold boot on snapshot
// restore re-reads the column on every Wake, so any drift between
// the snapshot age and the column is repaired by the next Wake
// without a version handshake on the hot path.
type UpdateEgressAllowlistRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppId           string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	EgressAllowlist []string               `protobuf:"bytes,2,rep,name=egress_allowlist,json=egressAllowlist,proto3" json:"egress_allowlist,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateEgressAllowlistRequest) Reset() {
	*x = UpdateEgressAllowlistRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEgressAllowlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEgressAllowlistRequest) ProtoMessage() {}

func (x *UpdateEgressAllowlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEgressAllowlistRequest.ProtoReflect.Descriptor instead.
func (*UpdateEgressAllowlistRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateEgressAllowlistRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateEgressAllowlistRequest) GetEgressAllowlist() []string {
	if x != nil {
		return x.EgressAllowlist
	}
	return nil
}

// UpdateEgressAllowlistAck is the empty success response. On
// failure vmmd returns a gRPC status (Unavailable when no live
// instances match app_id; Internal when the in-place nft patch
// failed AND the revert to the prior argv snapshot also failed —
// the live netns is then in an undefined state and the caller
// is expected to Park + ColdBoot the affected instances, which
// the schedd watchdog does on its next tick).
type UpdateEgressAllowlistAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEgressAllowlistAck) Reset() {
	*x = UpdateEgressAllowlistAck{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEgressAllowlistAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEgressAllowlistAck) ProtoMessage() {}

func (x *UpdateEgressAllowlistAck) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEgressAllowlistAck.ProtoReflect.Descriptor instead.
func (*UpdateEgressAllowlistAck) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{22}
}

// SeccompStatusRequest is the input to SeccompStatus. Instance is
// the compute_node-relative instance id (instances.id). vmmd
// resolves the running jailer child PID from its live map; an
// unknown instance returns NotFound (not InvalidArgument — the
// handler distinguishes "missing from the wire" from "missing on
// the host" so the e2e can diagnose the wrong row vs the wrong
// box).
type SeccompStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeccompStatusRequest) Reset() {
	*x = SeccompStatusRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeccompStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeccompStatusRequest) ProtoMessage() {}

func (x *SeccompStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeccompStatusRequest.ProtoReflect.Descriptor instead.
func (*SeccompStatusRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{23}
}

func (x *SeccompStatusRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

// SeccompStatusResponse mirrors /proc/<pid>/status. Mode is the
// human-readable equivalent of the kernel's Seccomp integer
// ("disabled" for 0, "strict" for 1, "filter" for 2). FilterLen is
// the Seccomp_filters count from the same procfs line — the
// kernel-reported number of distinct BPF filter programs
// attached to the process. For a freshly-installed jailer default
// filter this is 1; 0 means "filter mode but no program" and is
// the failure mode the e2e asserts against. Pid is the host PID
// of the jailer child (the only firecracker parent), surfaced so
// operators can `cat /proc/<pid>/status` themselves from the
// dashboard. Error is non-empty only when the handler could not
// read /proc — the wire is well-defined and the gRPC status is
// also set, but the e2e prefers the message to a non-OK code
// because the absence of a filter is the assertion target, not
// the gRPC envelope.
type SeccompStatusResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Instance string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Pid      int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// disabled | strict | filter
	Mode      string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	FilterLen int32  `protobuf:"varint,4,opt,name=filter_len,json=filterLen,proto3" json:"filter_len,omitempty"`
	// Empty on success. Non-empty on read failure (e.g. process
	// already reaped) — distinguishes "no seccomp filter installed"
	// (Mode="filter", FilterLen=0) from "can't tell" (Error set).
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeccompStatusResponse) Reset() {
	*x = SeccompStatusResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeccompStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeccompStatusResponse) ProtoMessage() {}

func (x *SeccompStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeccompStatusResponse.ProtoReflect.Descriptor instead.
func (*SeccompStatusResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{24}
}

func (x *SeccompStatusResponse) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *SeccompStatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SeccompStatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SeccompStatusResponse) GetFilterLen() int32 {
	if x != nil {
		return x.FilterLen
	}
	return 0
}

func (x *SeccompStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LogsRequest (issue #254 / Move 4) is the input to Logs. instance is
// the compute_node-relative instance id (instances.id, scoped to a node).
// since_seq replays from a sequence number; 0 = tail from now (skip the
// initial page and only stream new lines). The producer's ring is keyed
// per instance so each instance carries its own monotonic Seq.
type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	SinceSeq      int64                  `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{25}
}

func (x *LogsRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *LogsRequest) GetSinceSeq() int64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

// LogsResponse is one streamed log line. seq is the per-instance
// monotonic identifier the ring assigns at intake; consumers dedupe
// on (instance, seq) across reconnects. stream is "stdout" or "stderr"
// (the producer tags each Line at Write time). line is the payload
// BEFORE the newline terminator (the splitter consumes the '\n').
// written_at is the host-side ingest time, not the guest clock —
// we don't trust the guest clock (ADR-022 entropy hazard).
type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Line          string                 `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	WrittenAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP(), []int{26}
}

func (x *LogsResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogsResponse) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogsResponse) GetWrittenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

var File_onebox_faas_vmmd_v1_vmmd_proto protoreflect.FileDescriptor

const file_onebox_faas_vmmd_v1_vmmd_proto_rawDesc = "" +
	"\n" +
	"\x1eonebox/faas/vmmd/v1/vmmd.proto\x12\x13onebox.faas.vmmd.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa7\x02\n" +
	"\aAppSpec\x12\x19\n" +
	"\bbase_key\x18\x01 \x01(\tR\abaseKey\x12\x1b\n" +
	"\tlayer_key\x18\x02 \x01(\tR\blayerKey\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x03 \x01(\x05R\tvcpuCount\x12 \n" +
	"\fmem_size_mib\x18\x04 \x01(\x05R\n" +
	"memSizeMib\x12\x1f\n" +
	"\vegress_mbit\x18\x05 \x01(\x05R\n" +
	"egressMbit\x12@\n" +
	"\n" +
	"sealed_env\x18\x06 \x03(\v2!.onebox.faas.vmmd.v1.SealedSecretR\tsealedEnv\x12)\n" +
	"\x10egress_allowlist\x18\a \x03(\tR\x0fegressAllowlist\x12\x15\n" +
	"\x06app_id\x18\b \x01(\tR\x05appId\"@\n" +
	"\fSealedSecret\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\"\xcb\x01\n" +
	"\vSnapshotRef\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12!\n" +
	"\fvmstate_path\x18\x03 \x01(\tR\vvmstatePath\x12\x1d\n" +
	"\n" +
	"fc_version\x18\x04 \x01(\tR\tfcVersion\x12\x1f\n" +
	"\vstorage_key\x18\x05 \x01(\tR\n" +
	"storageKey\x12.\n" +
	"\x13vmstate_storage_key\x18\x06 \x01(\tR\x11vmstateStorageKeyJ\x04\b\x02\x10\x03\"\xe8\x02\n" +
	"\fWakeResponse\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x1b\n" +
	"\tlease_uid\x18\x02 \x01(\x05R\bleaseUid\x12\x17\n" +
	"\ahost_ip\x18\x03 \x01(\tR\x06hostIp\x12\x14\n" +
	"\x05netns\x18\x04 \x01(\tR\x05netns\x12\x1b\n" +
	"\tveth_host\x18\x05 \x01(\tR\bvethHost\x12\x1b\n" +
	"\tveth_peer\x18\x06 \x01(\tR\bvethPeer\x127\n" +
	"\x06method\x18\a \x01(\x0e2\x1f.onebox.faas.vmmd.v1.WakeMethodR\x06method\x12J\n" +
	"\x10requested_method\x18\b \x01(\x0e2\x1f.onebox.faas.vmmd.v1.WakeMethodR\x0frequestedMethod\x121\n" +
	"\aproblem\x18\t \x01(\v2\x17.google.protobuf.StructR\aproblem\"\xd8\x01\n" +
	"\x19CreateFromSnapshotRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12.\n" +
	"\x03app\x18\x02 \x01(\v2\x1c.onebox.faas.vmmd.v1.AppSpecR\x03app\x12<\n" +
	"\bsnapshot\x18\x03 \x01(\v2 .onebox.faas.vmmd.v1.SnapshotRefR\bsnapshot\x12\x12\n" +
	"\x04plan\x18\x04 \x01(\tR\x04plan\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\tR\taccountId\"\xcc\x01\n" +
	"\x15CreateColdBootRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12.\n" +
	"\x03app\x18\x02 \x01(\v2\x1c.onebox.faas.vmmd.v1.AppSpecR\x03app\x124\n" +
	"\x05build\x18\x03 \x01(\v2\x1e.onebox.faas.vmmd.v1.BuildSpecR\x05build\x12\x12\n" +
	"\x04plan\x18\x04 \x01(\tR\x04plan\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\tR\taccountId\"*\n" +
	"\tBuildSpec\x12\x1d\n" +
	"\n" +
	"export_dir\x18\x01 \x01(\tR\texportDir\"\xaf\x01\n" +
	"\x17PauseAndSnapshotRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12!\n" +
	"\fvmstate_path\x18\x03 \x01(\tR\vvmstatePath\x12\x1f\n" +
	"\vstorage_key\x18\x04 \x01(\tR\n" +
	"storageKey\x12.\n" +
	"\x13vmstate_storage_key\x18\x05 \x01(\tR\x11vmstateStorageKeyJ\x04\b\x02\x10\x03\"T\n" +
	"\x10SnapshotResponse\x12\x1b\n" +
	"\tmem_bytes\x18\x01 \x01(\x03R\bmemBytes\x12#\n" +
	"\rvmstate_bytes\x18\x02 \x01(\x03R\fvmstateBytes\",\n" +
	"\x0eDestroyRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\"J\n" +
	"\x0fDestroyResponse\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"\x0e\n" +
	"\fStatsRequest\"\xe2\x01\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"live_count\x18\x01 \x01(\x05R\tliveCount\x12!\n" +
	"\fleased_count\x18\x02 \x01(\x05R\vleasedCount\x12M\n" +
	"\x14total_resident_bytes\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x12totalResidentBytes\x12@\n" +
	"\tinstances\x18\x04 \x03(\v2\".onebox.faas.vmmd.v1.InstanceStatsR\tinstances\"\xde\x03\n" +
	"\rInstanceStats\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x1b\n" +
	"\tlease_uid\x18\x02 \x01(\x05R\bleaseUid\x12\x17\n" +
	"\ahost_ip\x18\x03 \x01(\tR\x06hostIp\x12B\n" +
	"\x0eresident_bytes\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\rresidentBytes\x125\n" +
	"\acpu_pct\x18\x05 \x01(\v2\x1c.google.protobuf.DoubleValueR\x06cpuPct\x12=\n" +
	"\vcpu_seconds\x18\b \x01(\v2\x1c.google.protobuf.DoubleValueR\n" +
	"cpuSeconds\x12P\n" +
	"\x15cpu_throttled_seconds\x18\t \x01(\v2\x1c.google.protobuf.DoubleValueR\x13cpuThrottledSeconds\x12+\n" +
	"\x11inflight_requests\x18\x06 \x01(\x03R\x10inflightRequests\x12B\n" +
	"\x0flast_request_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastRequestAt\"\r\n" +
	"\vPingRequest\"j\n" +
	"\fPingResponse\x12\x1d\n" +
	"\n" +
	"fc_version\x18\x01 \x01(\tR\tfcVersion\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xb4\x01\n" +
	"\x12ForwardHTTPRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1f\n" +
	"\vrequest_uri\x18\x03 \x01(\tR\n" +
	"requestUri\x125\n" +
	"\aheaders\x18\x04 \x03(\v2\x1b.onebox.faas.vmmd.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\"2\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"x\n" +
	"\x13ForwardHTTPResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x125\n" +
	"\aheaders\x18\x02 \x03(\v2\x1b.onebox.faas.vmmd.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"\x12\n" +
	"\x10HeartbeatRequest\"\x13\n" +
	"\x11HeartbeatResponse\"`\n" +
	"\x1cUpdateEgressAllowlistRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12)\n" +
	"\x10egress_allowlist\x18\x02 \x03(\tR\x0fegressAllowlist\"\x1a\n" +
	"\x18UpdateEgressAllowlistAck\"2\n" +
	"\x14SeccompStatusRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\"\x8e\x01\n" +
	"\x15SeccompStatusResponse\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"filter_len\x18\x04 \x01(\x05R\tfilterLen\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"F\n" +
	"\vLogsRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x03R\bsinceSeq\"\x87\x01\n" +
	"\fLogsResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line\x129\n" +
	"\n" +
	"written_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\twrittenAt*2\n" +
	"\n" +
	"WakeMethod\x12\x12\n" +
	"\x0eWAKE_COLD_BOOT\x10\x00\x12\x10\n" +
	"\fWAKE_RESTORE\x10\x012\x9c\b\n" +
	"\x04Vmmd\x12g\n" +
	"\x12CreateFromSnapshot\x12..onebox.faas.vmmd.v1.CreateFromSnapshotRequest\x1a!.onebox.faas.vmmd.v1.WakeResponse\x12_\n" +
	"\x0eCreateColdBoot\x12*.onebox.faas.vmmd.v1.CreateColdBootRequest\x1a!.onebox.faas.vmmd.v1.WakeResponse\x12g\n" +
	"\x10PauseAndSnapshot\x12,.onebox.faas.vmmd.v1.PauseAndSnapshotRequest\x1a%.onebox.faas.vmmd.v1.SnapshotResponse\x12T\n" +
	"\aDestroy\x12#.onebox.faas.vmmd.v1.DestroyRequest\x1a$.onebox.faas.vmmd.v1.DestroyResponse\x12N\n" +
	"\x05Stats\x12!.onebox.faas.vmmd.v1.StatsRequest\x1a\".onebox.faas.vmmd.v1.StatsResponse\x12K\n" +
	"\x04Ping\x12 .onebox.faas.vmmd.v1.PingRequest\x1a!.onebox.faas.vmmd.v1.PingResponse\x12`\n" +
	"\vForwardHTTP\x12'.onebox.faas.vmmd.v1.ForwardHTTPRequest\x1a(.onebox.faas.vmmd.v1.ForwardHTTPResponse\x12Z\n" +
	"\tHeartbeat\x12%.onebox.faas.vmmd.v1.HeartbeatRequest\x1a&.onebox.faas.vmmd.v1.HeartbeatResponse\x12y\n" +
	"\x15UpdateEgressAllowlist\x121.onebox.faas.vmmd.v1.UpdateEgressAllowlistRequest\x1a-.onebox.faas.vmmd.v1.UpdateEgressAllowlistAck\x12f\n" +
	"\rSeccompStatus\x12).onebox.faas.vmmd.v1.SeccompStatusRequest\x1a*.onebox.faas.vmmd.v1.SeccompStatusResponse\x12M\n" +
	"\x04Logs\x12 .onebox.faas.vmmd.v1.LogsRequest\x1a!.onebox.faas.vmmd.v1.LogsResponse0\x01BBZ@github.com/onebox-faas/faas/api/proto/onebox/faas/vmmd/v1;vmmdpbb\x06proto3"

var (
	file_onebox_faas_vmmd_v1_vmmd_proto_rawDescOnce sync.Once
	file_onebox_faas_vmmd_v1_vmmd_proto_rawDescData []byte
)

func file_onebox_faas_vmmd_v1_vmmd_proto_rawDescGZIP() []byte {
	file_onebox_faas_vmmd_v1_vmmd_proto_rawDescOnce.Do(func() {
		file_onebox_faas_vmmd_v1_vmmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_onebox_faas_vmmd_v1_vmmd_proto_rawDesc), len(file_onebox_faas_vmmd_v1_vmmd_proto_rawDesc)))
	})
	return file_onebox_faas_vmmd_v1_vmmd_proto_rawDescData
}

var file_onebox_faas_vmmd_v1_vmmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_onebox_faas_vmmd_v1_vmmd_proto_goTypes = []any{
	(WakeMethod)(0),                      // 0: onebox.faas.vmmd.v1.WakeMethod
	(*AppSpec)(nil),                      // 1: onebox.faas.vmmd.v1.AppSpec
	(*SealedSecret)(nil),                 // 2: onebox.faas.vmmd.v1.SealedSecret
	(*SnapshotRef)(nil),                  // 3: onebox.faas.vmmd.v1.SnapshotRef
	(*WakeResponse)(nil),                 // 4: onebox.faas.vmmd.v1.WakeResponse
	(*CreateFromSnapshotRequest)(nil),    // 5: onebox.faas.vmmd.v1.CreateFromSnapshotRequest
	(*CreateColdBootRequest)(nil),        // 6: onebox.faas.vmmd.v1.CreateColdBootRequest
	(*BuildSpec)(nil),                    // 7: onebox.faas.vmmd.v1.BuildSpec
	(*PauseAndSnapshotRequest)(nil),      // 8: onebox.faas.vmmd.v1.PauseAndSnapshotRequest
	(*SnapshotResponse)(nil),             // 9: onebox.faas.vmmd.v1.SnapshotResponse
	(*DestroyRequest)(nil),               // 10: onebox.faas.vmmd.v1.DestroyRequest
	(*DestroyResponse)(nil),              // 11: onebox.faas.vmmd.v1.DestroyResponse
	(*StatsRequest)(nil),                 // 12: onebox.faas.vmmd.v1.StatsRequest
	(*StatsResponse)(nil),                // 13: onebox.faas.vmmd.v1.StatsResponse
	(*InstanceStats)(nil),                // 14: onebox.faas.vmmd.v1.InstanceStats
	(*PingRequest)(nil),                  // 15: onebox.faas.vmmd.v1.PingRequest
	(*PingResponse)(nil),                 // 16: onebox.faas.vmmd.v1.PingResponse
	(*ForwardHTTPRequest)(nil),           // 17: onebox.faas.vmmd.v1.ForwardHTTPRequest
	(*Header)(nil),                       // 18: onebox.faas.vmmd.v1.Header
	(*ForwardHTTPResponse)(nil),          // 19: onebox.faas.vmmd.v1.ForwardHTTPResponse
	(*HeartbeatRequest)(nil),             // 20: onebox.faas.vmmd.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 21: onebox.faas.vmmd.v1.HeartbeatResponse
	(*UpdateEgressAllowlistRequest)(nil), // 22: onebox.faas.vmmd.v1.UpdateEgressAllowlistRequest
	(*UpdateEgressAllowlistAck)(nil),     // 23: onebox.faas.vmmd.v1.UpdateEgressAllowlistAck
	(*SeccompStatusRequest)(nil),         // 24: onebox.faas.vmmd.v1.SeccompStatusRequest
	(*SeccompStatusResponse)(nil),        // 25: onebox.faas.vmmd.v1.SeccompStatusResponse
	(*LogsRequest)(nil),                  // 26: onebox.faas.vmmd.v1.LogsRequest
	(*LogsResponse)(nil),                 // 27: onebox.faas.vmmd.v1.LogsResponse
	(*structpb.Struct)(nil),              // 28: google.protobuf.Struct
	(*wrapperspb.Int64Value)(nil),        // 29: google.protobuf.Int64Value
	(*wrapperspb.DoubleValue)(nil),       // 30: google.protobuf.DoubleValue
	(*timestamppb.Timestamp)(nil),        // 31: google.protobuf.Timestamp
}
var file_onebox_faas_vmmd_v1_vmmd_proto_depIdxs = []int32{
	2,  // 0: onebox.faas.vmmd.v1.AppSpec.sealed_env:type_name -> onebox.faas.vmmd.v1.SealedSecret
	0,  // 1: onebox.faas.vmmd.v1.WakeResponse.method:type_name -> onebox.faas.vmmd.v1.WakeMethod
	0,  // 2: onebox.faas.vmmd.v1.WakeResponse.requested_method:type_name -> onebox.faas.vmmd.v1.WakeMethod
	28, // 3: onebox.faas.vmmd.v1.WakeResponse.problem:type_name -> google.protobuf.Struct
	1,  // 4: onebox.faas.vmmd.v1.CreateFromSnapshotRequest.app:type_name -> onebox.faas.vmmd.v1.AppSpec
	3,  // 5: onebox.faas.vmmd.v1.CreateFromSnapshotRequest.snapshot:type_name -> onebox.faas.vmmd.v1.SnapshotRef
	1,  // 6: onebox.faas.vmmd.v1.CreateColdBootRequest.app:type_name -> onebox.faas.vmmd.v1.AppSpec
	7,  // 7: onebox.faas.vmmd.v1.CreateColdBootRequest.build:type_name -> onebox.faas.vmmd.v1.BuildSpec
	29, // 8: onebox.faas.vmmd.v1.StatsResponse.total_resident_bytes:type_name -> google.protobuf.Int64Value
	14, // 9: onebox.faas.vmmd.v1.StatsResponse.instances:type_name -> onebox.faas.vmmd.v1.InstanceStats
	29, // 10: onebox.faas.vmmd.v1.InstanceStats.resident_bytes:type_name -> google.protobuf.Int64Value
	30, // 11: onebox.faas.vmmd.v1.InstanceStats.cpu_pct:type_name -> google.protobuf.DoubleValue
	30, // 12: onebox.faas.vmmd.v1.InstanceStats.cpu_seconds:type_name -> google.protobuf.DoubleValue
	30, // 13: onebox.faas.vmmd.v1.InstanceStats.cpu_throttled_seconds:type_name -> google.protobuf.DoubleValue
	31, // 14: onebox.faas.vmmd.v1.InstanceStats.last_request_at:type_name -> google.protobuf.Timestamp
	31, // 15: onebox.faas.vmmd.v1.PingResponse.server_time:type_name -> google.protobuf.Timestamp
	18, // 16: onebox.faas.vmmd.v1.ForwardHTTPRequest.headers:type_name -> onebox.faas.vmmd.v1.Header
	18, // 17: onebox.faas.vmmd.v1.ForwardHTTPResponse.headers:type_name -> onebox.faas.vmmd.v1.Header
	31, // 18: onebox.faas.vmmd.v1.LogsResponse.written_at:type_name -> google.protobuf.Timestamp
	5,  // 19: onebox.faas.vmmd.v1.Vmmd.CreateFromSnapshot:input_type -> onebox.faas.vmmd.v1.CreateFromSnapshotRequest
	6,  // 20: onebox.faas.vmmd.v1.Vmmd.CreateColdBoot:input_type -> onebox.faas.vmmd.v1.CreateColdBootRequest
	8,  // 21: onebox.faas.vmmd.v1.Vmmd.PauseAndSnapshot:input_type -> onebox.faas.vmmd.v1.PauseAndSnapshotRequest
	10, // 22: onebox.faas.vmmd.v1.Vmmd.Destroy:input_type -> onebox.faas.vmmd.v1.DestroyRequest
	12, // 23: onebox.faas.vmmd.v1.Vmmd.Stats:input_type -> onebox.faas.vmmd.v1.StatsRequest
	15, // 24: onebox.faas.vmmd.v1.Vmmd.Ping:input_type -> onebox.faas.vmmd.v1.PingRequest
	17, // 25: onebox.faas.vmmd.v1.Vmmd.ForwardHTTP:input_type -> onebox.faas.vmmd.v1.ForwardHTTPRequest
	20, // 26: onebox.faas.vmmd.v1.Vmmd.Heartbeat:input_type -> onebox.faas.vmmd.v1.HeartbeatRequest
	22, // 27: onebox.faas.vmmd.v1.Vmmd.UpdateEgressAllowlist:input_type -> onebox.faas.vmmd.v1.UpdateEgressAllowlistRequest
	24, // 28: onebox.faas.vmmd.v1.Vmmd.SeccompStatus:input_type -> onebox.faas.vmmd.v1.SeccompStatusRequest
	26, // 29: onebox.faas.vmmd.v1.Vmmd.Logs:input_type -> onebox.faas.vmmd.v1.LogsRequest
	4,  // 30: onebox.faas.vmmd.v1.Vmmd.CreateFromSnapshot:output_type -> onebox.faas.vmmd.v1.WakeResponse
	4,  // 31: onebox.faas.vmmd.v1.Vmmd.CreateColdBoot:output_type -> onebox.faas.vmmd.v1.WakeResponse
	9,  // 32: onebox.faas.vmmd.v1.Vmmd.PauseAndSnapshot:output_type -> onebox.faas.vmmd.v1.SnapshotResponse
	11, // 33: onebox.faas.vmmd.v1.Vmmd.Destroy:output_type -> onebox.faas.vmmd.v1.DestroyResponse
	13, // 34: onebox.faas.vmmd.v1.Vmmd.Stats:output_type -> onebox.faas.vmmd.v1.StatsResponse
	16, // 35: onebox.faas.vmmd.v1.Vmmd.Ping:output_type -> onebox.faas.vmmd.v1.PingResponse
	19, // 36: onebox.faas.vmmd.v1.Vmmd.ForwardHTTP:output_type -> onebox.faas.vmmd.v1.ForwardHTTPResponse
	21, // 37: onebox.faas.vmmd.v1.Vmmd.Heartbeat:output_type -> onebox.faas.vmmd.v1.HeartbeatResponse
	23, // 38: onebox.faas.vmmd.v1.Vmmd.UpdateEgressAllowlist:output_type -> onebox.faas.vmmd.v1.UpdateEgressAllowlistAck
	25, // 39: onebox.faas.vmmd.v1.Vmmd.SeccompStatus:output_type -> onebox.faas.vmmd.v1.SeccompStatusResponse
	27, // 40: onebox.faas.vmmd.v1.Vmmd.Logs:output_type -> onebox.faas.vmmd.v1.LogsResponse
	30, // [30:41] is the sub-list for method output_type
	19, // [19:30] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_onebox_faas_vmmd_v1_vmmd_proto_init() }
func file_onebox_faas_vmmd_v1_vmmd_proto_init() {
	if File_onebox_faas_vmmd_v1_vmmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_onebox_faas_vmmd_v1_vmmd_proto_rawDesc), len(file_onebox_faas_vmmd_v1_vmmd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_onebox_faas_vmmd_v1_vmmd_proto_goTypes,
		DependencyIndexes: file_onebox_faas_vmmd_v1_vmmd_proto_depIdxs,
		EnumInfos:         file_onebox_faas_vmmd_v1_vmmd_proto_enumTypes,
		MessageInfos:      file_onebox_faas_vmmd_v1_vmmd_proto_msgTypes,
	}.Build()
	File_onebox_faas_vmmd_v1_vmmd_proto = out.File
	file_onebox_faas_vmmd_v1_vmmd_proto_goTypes = nil
	file_onebox_faas_vmmd_v1_vmmd_proto_depIdxs = nil
}
