from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.get_build_sbom_response_200 import GetBuildSbomResponse200
from ...models.problem import Problem
from ...types import Response


def _get_kwargs(
    id: str,
) -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/v1/builds/{id}/sbom".format(
            id=quote(str(id), safe=""),
        ),
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> GetBuildSbomResponse200 | Problem | None:
    if response.status_code == 200:
        response_200 = GetBuildSbomResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 503:
        response_503 = Problem.from_dict(response.json())

        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[GetBuildSbomResponse200 | Problem]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    id: str,
    *,
    client: AuthenticatedClient | Client,
) -> Response[GetBuildSbomResponse200 | Problem]:
    r"""Get build SBOM (CycloneDX JSON).

     Streams the CycloneDX 1.5 SBOM JSON generated by `imaged`'s
    post-build syft pass (issue #299). The body is the raw SBOM
    document; the response content-type is
    `application/vnd.cyclonedx+json` so external tooling
    (cyclonedx-cli validate, jq with `@cyclonedx-json`, Grype's
    `--from-file=cyclonedx-json`) can dispatch on header alone.

    Three failure modes, each with its own code so the SDK and
    `faas build sbom <id>` can branch:

      - `404 not_found` — the build id does not exist, OR the build
        belongs to another account (the handler returns the same
        surface on both so account-existence isn't probeable).
      - `503 build_sbom_unavailable` — the build row exists for this
        account but imaged's syft populator did not persist a
        CycloneDX document (pre-PR build, or best-effort WARN).
        The CLI prints \"no SBOM for this build\" and exits 1; the
        operator's job is to re-deploy imaged with Phase 3 active.
      - `503 capacity_unavailable` — the SBOM exists but the file
        was unreadable from disk (storage backend returned a
        transient error). The customer retries once.

    Args:
        id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[GetBuildSbomResponse200 | Problem]
    """

    kwargs = _get_kwargs(
        id=id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    id: str,
    *,
    client: AuthenticatedClient | Client,
) -> GetBuildSbomResponse200 | Problem | None:
    r"""Get build SBOM (CycloneDX JSON).

     Streams the CycloneDX 1.5 SBOM JSON generated by `imaged`'s
    post-build syft pass (issue #299). The body is the raw SBOM
    document; the response content-type is
    `application/vnd.cyclonedx+json` so external tooling
    (cyclonedx-cli validate, jq with `@cyclonedx-json`, Grype's
    `--from-file=cyclonedx-json`) can dispatch on header alone.

    Three failure modes, each with its own code so the SDK and
    `faas build sbom <id>` can branch:

      - `404 not_found` — the build id does not exist, OR the build
        belongs to another account (the handler returns the same
        surface on both so account-existence isn't probeable).
      - `503 build_sbom_unavailable` — the build row exists for this
        account but imaged's syft populator did not persist a
        CycloneDX document (pre-PR build, or best-effort WARN).
        The CLI prints \"no SBOM for this build\" and exits 1; the
        operator's job is to re-deploy imaged with Phase 3 active.
      - `503 capacity_unavailable` — the SBOM exists but the file
        was unreadable from disk (storage backend returned a
        transient error). The customer retries once.

    Args:
        id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        GetBuildSbomResponse200 | Problem
    """

    return sync_detailed(
        id=id,
        client=client,
    ).parsed


async def asyncio_detailed(
    id: str,
    *,
    client: AuthenticatedClient | Client,
) -> Response[GetBuildSbomResponse200 | Problem]:
    r"""Get build SBOM (CycloneDX JSON).

     Streams the CycloneDX 1.5 SBOM JSON generated by `imaged`'s
    post-build syft pass (issue #299). The body is the raw SBOM
    document; the response content-type is
    `application/vnd.cyclonedx+json` so external tooling
    (cyclonedx-cli validate, jq with `@cyclonedx-json`, Grype's
    `--from-file=cyclonedx-json`) can dispatch on header alone.

    Three failure modes, each with its own code so the SDK and
    `faas build sbom <id>` can branch:

      - `404 not_found` — the build id does not exist, OR the build
        belongs to another account (the handler returns the same
        surface on both so account-existence isn't probeable).
      - `503 build_sbom_unavailable` — the build row exists for this
        account but imaged's syft populator did not persist a
        CycloneDX document (pre-PR build, or best-effort WARN).
        The CLI prints \"no SBOM for this build\" and exits 1; the
        operator's job is to re-deploy imaged with Phase 3 active.
      - `503 capacity_unavailable` — the SBOM exists but the file
        was unreadable from disk (storage backend returned a
        transient error). The customer retries once.

    Args:
        id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[GetBuildSbomResponse200 | Problem]
    """

    kwargs = _get_kwargs(
        id=id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    id: str,
    *,
    client: AuthenticatedClient | Client,
) -> GetBuildSbomResponse200 | Problem | None:
    r"""Get build SBOM (CycloneDX JSON).

     Streams the CycloneDX 1.5 SBOM JSON generated by `imaged`'s
    post-build syft pass (issue #299). The body is the raw SBOM
    document; the response content-type is
    `application/vnd.cyclonedx+json` so external tooling
    (cyclonedx-cli validate, jq with `@cyclonedx-json`, Grype's
    `--from-file=cyclonedx-json`) can dispatch on header alone.

    Three failure modes, each with its own code so the SDK and
    `faas build sbom <id>` can branch:

      - `404 not_found` — the build id does not exist, OR the build
        belongs to another account (the handler returns the same
        surface on both so account-existence isn't probeable).
      - `503 build_sbom_unavailable` — the build row exists for this
        account but imaged's syft populator did not persist a
        CycloneDX document (pre-PR build, or best-effort WARN).
        The CLI prints \"no SBOM for this build\" and exits 1; the
        operator's job is to re-deploy imaged with Phase 3 active.
      - `503 capacity_unavailable` — the SBOM exists but the file
        was unreadable from disk (storage backend returned a
        transient error). The customer retries once.

    Args:
        id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        GetBuildSbomResponse200 | Problem
    """

    return (
        await asyncio_detailed(
            id=id,
            client=client,
        )
    ).parsed
