// spans_writer — production debugger spans_summary writer RPC
// (ADR-127 PR-D). gatewayd-public flushes its per-trace coalesce
// accumulator (Stage 3) to apid over a unix socket so the
// request_telemetry.spans_summary jsonb column gets populated
// for PR-C's prose synthesis to read.
//
// Wire discipline mirrors the sibling apid/v1/auth.proto service:
// checked-in *.pb.go generated with paths=source_relative,
// auth is the unix-socket DAC model (mode 0660 group `faas`,
// ADR-015) on /run/faas/otel_spans_writer.sock.
//
// The RPC is unary (not streaming) because the gateway's flush
// loop drives the call cadence — one RPC per accumulated trace_id
// every 30s. A streaming RPC would require matching the
// accumulator drain to the stream boundary; the simpler 1:1
// shape avoids that bookkeeping at the cost of one RPC per
// trace_id per flush window. Production traffic is one customer
// with maybe 10-20 trace_ids in flight at a time — the RPC
// volume is bounded.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// source: onebox/faas/apid/v1/spans_writer.proto

package apidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WriteSpansSummaryRequest is one coalesced spans_summary
// payload. The trace_id is the W3C hex form the request_telemetry
// CHECK constraint enforces; account_id is the UUID of the
// matching customer.
type WriteSpansSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trace_id — W3C 32-char lowercase hex. Validated server-side
	// before the UPDATE; mismatch → InvalidArgument.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// summary_json — already-coalesced + truncated spans array
	// as a JSON object the gateway hands back to apid. Validated
	// server-side as parseable JSON; mismatch → InvalidArgument.
	SummaryJson []byte `protobuf:"bytes,2,opt,name=summary_json,json=summaryJson,proto3" json:"summary_json,omitempty"`
	// account_id — UUID of the matching customer. Used for the
	// per-account rate-cap (Stage 4 takes one token per flush
	// window, not per request; PR-B's caps cache carries across).
	AccountId     string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSpansSummaryRequest) Reset() {
	*x = WriteSpansSummaryRequest{}
	mi := &file_onebox_faas_apid_v1_spans_writer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSpansSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSpansSummaryRequest) ProtoMessage() {}

func (x *WriteSpansSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_apid_v1_spans_writer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSpansSummaryRequest.ProtoReflect.Descriptor instead.
func (*WriteSpansSummaryRequest) Descriptor() ([]byte, []int) {
	return file_onebox_faas_apid_v1_spans_writer_proto_rawDescGZIP(), []int{0}
}

func (x *WriteSpansSummaryRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WriteSpansSummaryRequest) GetSummaryJson() []byte {
	if x != nil {
		return x.SummaryJson
	}
	return nil
}

func (x *WriteSpansSummaryRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// WriteSpansSummaryResponse is the per-flush outcome. outcome ∈
// {inserted, rate_limited, db_error}. `inserted` is a successful
// UPDATE; `rate_limited` means the per-account token bucket was
// empty (gateway should drop this entry, log, retry next window);
// `db_error` is a transient Postgres failure (gateway retries
// the entry at the next flush).
type WriteSpansSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outcome — see comment above for the closed enum.
	Outcome string `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// retry_after_ms — populated when outcome == "rate_limited".
	// Mirrors the IncrementRequestTelemetryResponse retry_after_ms
	// shape so the gateway can apply the same back-off logic.
	RetryAfterMs  int64 `protobuf:"varint,2,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSpansSummaryResponse) Reset() {
	*x = WriteSpansSummaryResponse{}
	mi := &file_onebox_faas_apid_v1_spans_writer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSpansSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSpansSummaryResponse) ProtoMessage() {}

func (x *WriteSpansSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onebox_faas_apid_v1_spans_writer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSpansSummaryResponse.ProtoReflect.Descriptor instead.
func (*WriteSpansSummaryResponse) Descriptor() ([]byte, []int) {
	return file_onebox_faas_apid_v1_spans_writer_proto_rawDescGZIP(), []int{1}
}

func (x *WriteSpansSummaryResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *WriteSpansSummaryResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_onebox_faas_apid_v1_spans_writer_proto protoreflect.FileDescriptor

const file_onebox_faas_apid_v1_spans_writer_proto_rawDesc = "" +
	"\n" +
	"&onebox/faas/apid/v1/spans_writer.proto\x12\x13onebox.faas.apid.v1\"w\n" +
	"\x18WriteSpansSummaryRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12!\n" +
	"\fsummary_json\x18\x02 \x01(\fR\vsummaryJson\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"[\n" +
	"\x19WriteSpansSummaryResponse\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\x12$\n" +
	"\x0eretry_after_ms\x18\x02 \x01(\x03R\fretryAfterMs2\x81\x01\n" +
	"\vSpansWriter\x12r\n" +
	"\x11WriteSpansSummary\x12-.onebox.faas.apid.v1.WriteSpansSummaryRequest\x1a..onebox.faas.apid.v1.WriteSpansSummaryResponseBBZ@github.com/onebox-faas/faas/api/proto/onebox/faas/apid/v1;apidpbb\x06proto3"

var (
	file_onebox_faas_apid_v1_spans_writer_proto_rawDescOnce sync.Once
	file_onebox_faas_apid_v1_spans_writer_proto_rawDescData []byte
)

func file_onebox_faas_apid_v1_spans_writer_proto_rawDescGZIP() []byte {
	file_onebox_faas_apid_v1_spans_writer_proto_rawDescOnce.Do(func() {
		file_onebox_faas_apid_v1_spans_writer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_onebox_faas_apid_v1_spans_writer_proto_rawDesc), len(file_onebox_faas_apid_v1_spans_writer_proto_rawDesc)))
	})
	return file_onebox_faas_apid_v1_spans_writer_proto_rawDescData
}

var file_onebox_faas_apid_v1_spans_writer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_onebox_faas_apid_v1_spans_writer_proto_goTypes = []any{
	(*WriteSpansSummaryRequest)(nil),  // 0: onebox.faas.apid.v1.WriteSpansSummaryRequest
	(*WriteSpansSummaryResponse)(nil), // 1: onebox.faas.apid.v1.WriteSpansSummaryResponse
}
var file_onebox_faas_apid_v1_spans_writer_proto_depIdxs = []int32{
	0, // 0: onebox.faas.apid.v1.SpansWriter.WriteSpansSummary:input_type -> onebox.faas.apid.v1.WriteSpansSummaryRequest
	1, // 1: onebox.faas.apid.v1.SpansWriter.WriteSpansSummary:output_type -> onebox.faas.apid.v1.WriteSpansSummaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_onebox_faas_apid_v1_spans_writer_proto_init() }
func file_onebox_faas_apid_v1_spans_writer_proto_init() {
	if File_onebox_faas_apid_v1_spans_writer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_onebox_faas_apid_v1_spans_writer_proto_rawDesc), len(file_onebox_faas_apid_v1_spans_writer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_onebox_faas_apid_v1_spans_writer_proto_goTypes,
		DependencyIndexes: file_onebox_faas_apid_v1_spans_writer_proto_depIdxs,
		MessageInfos:      file_onebox_faas_apid_v1_spans_writer_proto_msgTypes,
	}.Build()
	File_onebox_faas_apid_v1_spans_writer_proto = out.File
	file_onebox_faas_apid_v1_spans_writer_proto_goTypes = nil
	file_onebox_faas_apid_v1_spans_writer_proto_depIdxs = nil
}
