// Storage layer for the cluster-shipped release bundle. Talks
// directly to PostgreSQL via pgxpool — does not go through
// pkg/state.PgStore because the release_bundles table has no
// existing consumers there, and pulling the methods into pgstore
// would force a spurious sqlc regeneration round.
//
// The CHECK constraints baked into migration 00272
// (git_sha ~ '^[a-f0-9]{40}$', manifest_hash ~ '^sha256:[a-f0-9]{64}$')
// are enforced by the database; the Go-side calls rely on those
// constraints to refuse malformed input.
package releaseinstall

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Store is the abstract interface for the release_bundles +
// compute_nodes tables. Defined here so package consumers
// (cmd/gregalectl doctor in PR-4 + the customer-side
// gregalectl release commands) can inject a fake in tests
// without a real Postgres.
type Store interface {
	// Insert records a new bundle. Returns the row id (uuid)
	// generated by gen_random_uuid().
	Insert(ctx context.Context, b Bundle) (string, error)
	// MarkApplied stamps applied_at = now() on the row whose
	// git_sha matches. The UPDATE is conditional on applied_at
	// IS NULL so the first node to install wins (idempotent
	// for concurrent installs).
	//
	// Returns true if this call set applied_at (the first install),
	// false if applied_at was already set (a re-install).
	MarkApplied(ctx context.Context, gitSHA string) (firstApplied bool, err error)
	// GetByGitSHA loads the row. Returns ErrNotFound if no row
	// exists for the given git_sha.
	GetByGitSHA(ctx context.Context, gitSHA string) (BundleRow, error)
	// ListApplied returns every bundle whose applied_at IS NOT NULL
	// (the partial-uniq index release_bundles_applied_at_idx keeps
	// this fast). Used by the operator dashboard.
	ListApplied(ctx context.Context) ([]BundleRow, error)
	// ListAllBundles returns every row in release_bundles ordered
	// by created_at desc (newest first). PR-4 doctor uses this for
	// the bundle-orphans check (an unapplied bundle whose on-disk
	// directory has been removed is a recoverable warning).
	ListAllBundles(ctx context.Context) ([]BundleRow, error)
	// UpsertComputeNode writes the per-node release membership on
	// the compute_nodes table (PR-6 / issue #911). Stamps
	// release_id + manifest_hash keyed by name (the host's
	// --node flag or hostname). Idempotent via ON CONFLICT (name)
	// DO UPDATE. generation stays at 0 — PR-4 doctor bumps it on
	// detected drift.
	//
	// Returns the row id (uuid) so the caller can include it in
	// the JSON report. host_certificate / cert_fingerprint /
	// role columns are intentionally NOT written here (PR-X secrets
	// init owns host_certificate/cert_fingerprint; PR-2 renderer
	// owns role).
	UpsertComputeNode(ctx context.Context, name, gitSHA, manifestHash string) (string, error)
	// GetComputeNode reads the per-node release membership. Returns
	// ErrComputeNodeNotFound if no row exists for the given name.
	// Used by PR-4 doctor + e2e tests to assert post-install state.
	GetComputeNode(ctx context.Context, name string) (ComputeNodeRow, error)
	// ListComputeNodes returns every row in compute_nodes ordered
	// by name (PQ-stable). PR-4 doctor uses this to walk per-node
	// release membership and detect drift against the on-disk
	// bundle + the release_bundles table.
	ListComputeNodes(ctx context.Context) ([]ComputeNodeRow, error)
}

// ErrNotFound is returned by GetByGitSHA when no row matches.
var ErrNotFound = errors.New("releaseinstall: bundle not found")

// ErrComputeNodeNotFound is returned by GetComputeNode when no
// compute_nodes row matches the given name. Distinct error var
// from ErrNotFound so callers can distinguish "no bundle row" from
// "no compute node row" without parsing the message.
var ErrComputeNodeNotFound = errors.New("releaseinstall: compute node not found")

// ComputeNodeRow mirrors the columns PR-6 reads from compute_nodes
// after UpsertComputeNode. The original four fields (id, name,
// release_id, manifest_hash) are populated by PR-6's UPSERT. The
// remaining PR-3a columns (host_certificate, cert_fingerprint,
// role, generation) are populated by their respective writers
// (PR-X secrets init, PR-2 renderer) and exposed as nullable
// pointers so a NULL column is explicit instead of an empty
// string / zero.
//
// PR-4 doctor reads release_id + manifest_hash + generation; the
// cert columns stay nil when nil-on-the-wire. The widening is
// non-breaking — callers that only knew about the original four
// fields (PR-6's commands_release.go:312 and release_install_test.go:192)
// keep working unchanged.
type ComputeNodeRow struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	ReleaseID       string  `json:"release_id"`
	ManifestHash    string  `json:"manifest_hash"`
	HostCertificate *string `json:"host_certificate,omitempty"`
	CertFingerprint *string `json:"cert_fingerprint,omitempty"`
	Role            *string `json:"role,omitempty"`
	Generation      *int    `json:"generation,omitempty"`
}

// pgStore is the production Store, backed by pgxpool. Construct
// it via NewStore passing a pool.
type pgStore struct {
	pool *pgxpool.Pool
}

// NewStore returns a Store backed by the given pool. The pool is
// not owned by the store — the caller is responsible for Close.
func NewStore(pool *pgxpool.Pool) Store {
	return pgStore{pool: pool}
}

// Insert implements Store.
func (s pgStore) Insert(ctx context.Context, b Bundle) (string, error) {
	if b.GitSHA == "" || b.ManifestHash == "" || len(b.DaemonHashes) == 0 {
		return "", fmt.Errorf("releaseinstall: insert requires git_sha, manifest_hash, and non-empty daemon_hashes")
	}
	hashes, err := EncodeDaemonHashes(b.DaemonHashes)
	if err != nil {
		return "", fmt.Errorf("releaseinstall: encode daemon_hashes: %w", err)
	}
	var id string
	err = s.pool.QueryRow(ctx, `
		insert into release_bundles (git_sha, manifest_hash, daemon_hashes)
		values ($1, $2, $3::jsonb)
		returning id
	`, b.GitSHA, b.ManifestHash, string(hashes)).Scan(&id)
	if err != nil {
		return "", fmt.Errorf("releaseinstall: insert bundle: %w", err)
	}
	return id, nil
}

// MarkApplied implements Store.
//
// The query is the load-bearing first-write-wins contract: the
// conditional UPDATE only runs if applied_at IS NULL, so two
// concurrent node installs on the same release both succeed but
// only the first one sets applied_at. The RETURNING clause tells
// the caller which side of the race they were on.
func (s pgStore) MarkApplied(ctx context.Context, gitSHA string) (bool, error) {
	if gitSHA == "" {
		return false, fmt.Errorf("releaseinstall: empty git_sha")
	}
	var appliedAt *time.Time
	err := s.pool.QueryRow(ctx, `
		update release_bundles
		   set applied_at = now()
		 where git_sha = $1
		   and applied_at IS NULL
		returning applied_at
	`, gitSHA).Scan(&appliedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Two options: (a) the git_sha doesn't exist, or
			// (b) applied_at was already set. Distinguish by
			// a follow-up lookup.
			_, gerr := s.GetByGitSHA(ctx, gitSHA)
			if gerr != nil {
				return false, gerr
			}
			return false, nil
		}
		return false, fmt.Errorf("releaseinstall: mark applied: %w", err)
	}
	return appliedAt != nil, nil
}

// GetByGitSHA implements Store.
func (s pgStore) GetByGitSHA(ctx context.Context, gitSHA string) (BundleRow, error) {
	if gitSHA == "" {
		return BundleRow{}, fmt.Errorf("releaseinstall: empty git_sha")
	}
	var (
		row        BundleRow
		daemonJSON []byte
	)
	err := s.pool.QueryRow(ctx, `
		select id,
		       git_sha,
		       manifest_hash,
		       daemon_hashes::text,
		       created_at,
		       applied_at
		  from release_bundles
		 where git_sha = $1
	`, gitSHA).Scan(
		&row.ID,
		&row.GitSHA,
		&row.ManifestHash,
		&daemonJSON,
		&row.CreatedAt,
		&row.AppliedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return BundleRow{}, ErrNotFound
		}
		return BundleRow{}, fmt.Errorf("releaseinstall: get bundle: %w", err)
	}
	hashes, err := DecodeDaemonHashes(daemonJSON)
	if err != nil {
		return BundleRow{}, fmt.Errorf("releaseinstall: decode daemon_hashes: %w", err)
	}
	row.DaemonHashes = hashes
	return row, nil
}

// ListApplied implements Store.
func (s pgStore) ListApplied(ctx context.Context) ([]BundleRow, error) {
	rows, err := s.pool.Query(ctx, `
		select id,
		       git_sha,
		       manifest_hash,
		       daemon_hashes::text,
		       created_at,
		       applied_at
		  from release_bundles
		 where applied_at IS NOT NULL
		 order by applied_at desc
	`)
	if err != nil {
		return nil, fmt.Errorf("releaseinstall: list applied: %w", err)
	}
	defer rows.Close()
	var out []BundleRow
	for rows.Next() {
		var (
			row        BundleRow
			daemonJSON []byte
		)
		if err := rows.Scan(
			&row.ID,
			&row.GitSHA,
			&row.ManifestHash,
			&daemonJSON,
			&row.CreatedAt,
			&row.AppliedAt,
		); err != nil {
			return nil, fmt.Errorf("releaseinstall: scan: %w", err)
		}
		hashes, err := DecodeDaemonHashes(daemonJSON)
		if err != nil {
			return nil, fmt.Errorf("releaseinstall: decode daemon_hashes: %w", err)
		}
		row.DaemonHashes = hashes
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("releaseinstall: iterate: %w", err)
	}
	return out, nil
}

// ListAllBundles implements Store. Identical to ListApplied but
// drops the applied_at IS NOT NULL filter so PR-4 doctor can spot
// bundles that were INSERTed but never installed (an unapplied
// bundle whose on-disk tree has been removed is a warning, not
// an error — the install path is just incomplete).
//
// Ordered by created_at desc (newest first) so the doctor report
// highlights the most recent bundle.
func (s pgStore) ListAllBundles(ctx context.Context) ([]BundleRow, error) {
	rows, err := s.pool.Query(ctx, `
		select id,
		       git_sha,
		       manifest_hash,
		       daemon_hashes::text,
		       created_at,
		       applied_at
		  from release_bundles
		 order by created_at desc
	`)
	if err != nil {
		return nil, fmt.Errorf("releaseinstall: list all bundles: %w", err)
	}
	defer rows.Close()
	var out []BundleRow
	for rows.Next() {
		var (
			row        BundleRow
			daemonJSON []byte
		)
		if err := rows.Scan(
			&row.ID,
			&row.GitSHA,
			&row.ManifestHash,
			&daemonJSON,
			&row.CreatedAt,
			&row.AppliedAt,
		); err != nil {
			return nil, fmt.Errorf("releaseinstall: scan: %w", err)
		}
		hashes, err := DecodeDaemonHashes(daemonJSON)
		if err != nil {
			return nil, fmt.Errorf("releaseinstall: decode daemon_hashes: %w", err)
		}
		row.DaemonHashes = hashes
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("releaseinstall: iterate: %w", err)
	}
	return out, nil
}

// UpsertComputeNode implements Store.
//
// Writes the per-node release membership on compute_nodes. The
// conflict target is compute_nodes_name_key (UNIQUE on name) per
// migrations/00024_compute_nodes.sql. The migration 00271 columns
// (release_id, manifest_hash) are plain text with no DB CHECK, so
// Go-side validation (validGitSHA + validManifestHash) is the gate.
//
// generation is intentionally set to 0 on every write — the doctor
// (PR-4) bumps it on detected drift; PR-6 does not pre-empt that
// signal. host_certificate, cert_fingerprint, and role are NOT
// touched (PR-X / PR-2 own those columns).
func (s pgStore) UpsertComputeNode(ctx context.Context, name, gitSHA, manifestHash string) (string, error) {
	if name == "" {
		return "", fmt.Errorf("releaseinstall: empty compute_nodes name")
	}
	if !validGitSHA(gitSHA) {
		return "", fmt.Errorf("releaseinstall: git_sha %q is not 40-char lowercase hex", gitSHA)
	}
	if !validManifestHash(manifestHash) {
		return "", fmt.Errorf("releaseinstall: manifest_hash %q is not sha256:<64hex>", manifestHash)
	}
	var id string
	err := s.pool.QueryRow(ctx, `
		insert into compute_nodes (name, release_id, manifest_hash, generation)
		values ($1, $2, $3, 0)
		on conflict (name) do update
		set    release_id    = excluded.release_id,
		       manifest_hash = excluded.manifest_hash
		returning id
	`, name, gitSHA, manifestHash).Scan(&id)
	if err != nil {
		return "", fmt.Errorf("releaseinstall: upsert compute_nodes: %w", err)
	}
	return id, nil
}

// GetComputeNode implements Store.
func (s pgStore) GetComputeNode(ctx context.Context, name string) (ComputeNodeRow, error) {
	if name == "" {
		return ComputeNodeRow{}, fmt.Errorf("releaseinstall: empty compute_nodes name")
	}
	var row ComputeNodeRow
	err := s.pool.QueryRow(ctx, `
		select id, name, release_id, manifest_hash,
		       host_certificate, cert_fingerprint, role, generation
		  from compute_nodes
		 where name = $1
	`, name).Scan(
		&row.ID, &row.Name, &row.ReleaseID, &row.ManifestHash,
		&row.HostCertificate, &row.CertFingerprint, &row.Role, &row.Generation,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ComputeNodeRow{}, ErrComputeNodeNotFound
		}
		return ComputeNodeRow{}, fmt.Errorf("releaseinstall: get compute node: %w", err)
	}
	return row, nil
}

// ListComputeNodes implements Store. Returns every row in
// compute_nodes ordered by name (PQ-stable). PR-4 doctor walks
// the result to detect per-node drift against the on-disk
// bundle + the release_bundles table. The widening to eight
// columns mirrors GetComputeNode — nullable pointers stay nil
// on NULL.
func (s pgStore) ListComputeNodes(ctx context.Context) ([]ComputeNodeRow, error) {
	rows, err := s.pool.Query(ctx, `
		select id, name, release_id, manifest_hash,
		       host_certificate, cert_fingerprint, role, generation
		  from compute_nodes
		 order by name
	`)
	if err != nil {
		return nil, fmt.Errorf("releaseinstall: list compute nodes: %w", err)
	}
	defer rows.Close()
	var out []ComputeNodeRow
	for rows.Next() {
		var row ComputeNodeRow
		if err := rows.Scan(
			&row.ID, &row.Name, &row.ReleaseID, &row.ManifestHash,
			&row.HostCertificate, &row.CertFingerprint, &row.Role, &row.Generation,
		); err != nil {
			return nil, fmt.Errorf("releaseinstall: scan compute_nodes: %w", err)
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("releaseinstall: iterate compute_nodes: %w", err)
	}
	return out, nil
}
