// Storage layer for the cluster-shipped release bundle. Talks
// directly to PostgreSQL via pgxpool — does not go through
// pkg/state.PgStore because the release_bundles table has no
// existing consumers there, and pulling the methods into pgstore
// would force a spurious sqlc regeneration round.
//
// The CHECK constraints baked into migration 00272
// (git_sha ~ '^[a-f0-9]{40}$', manifest_hash ~ '^sha256:[a-f0-9]{64}$')
// are enforced by the database; the Go-side calls rely on those
// constraints to refuse malformed input.
package releaseinstall

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Store is the abstract interface for the release_bundles table.
// Defined here so package consumers (cmd/gregale + PR-4 doctor)
// can inject a fake in tests without a real Postgres.
type Store interface {
	// Insert records a new bundle. Returns the row id (uuid)
	// generated by gen_random_uuid().
	Insert(ctx context.Context, b Bundle) (string, error)
	// MarkApplied stamps applied_at = now() on the row whose
	// git_sha matches. The UPDATE is conditional on applied_at
	// IS NULL so the first node to install wins (idempotent
	// for concurrent installs).
	//
	// Returns true if this call set applied_at (the first install),
	// false if applied_at was already set (a re-install).
	MarkApplied(ctx context.Context, gitSHA string) (firstApplied bool, err error)
	// GetByGitSHA loads the row. Returns ErrNotFound if no row
	// exists for the given git_sha.
	GetByGitSHA(ctx context.Context, gitSHA string) (BundleRow, error)
	// ListApplied returns every bundle whose applied_at IS NOT NULL
	// (the partial-uniq index release_bundles_applied_at_idx keeps
	// this fast). Used by the operator dashboard.
	ListApplied(ctx context.Context) ([]BundleRow, error)
}

// ErrNotFound is returned by GetByGitSHA when no row matches.
var ErrNotFound = errors.New("releaseinstall: bundle not found")

// pgStore is the production Store, backed by pgxpool. Construct
// it via NewStore passing a pool.
type pgStore struct {
	pool *pgxpool.Pool
}

// NewStore returns a Store backed by the given pool. The pool is
// not owned by the store — the caller is responsible for Close.
func NewStore(pool *pgxpool.Pool) Store {
	return pgStore{pool: pool}
}

// Insert implements Store.
func (s pgStore) Insert(ctx context.Context, b Bundle) (string, error) {
	if b.GitSHA == "" || b.ManifestHash == "" || len(b.DaemonHashes) == 0 {
		return "", fmt.Errorf("releaseinstall: insert requires git_sha, manifest_hash, and non-empty daemon_hashes")
	}
	hashes, err := EncodeDaemonHashes(b.DaemonHashes)
	if err != nil {
		return "", fmt.Errorf("releaseinstall: encode daemon_hashes: %w", err)
	}
	var id string
	err = s.pool.QueryRow(ctx, `
		insert into release_bundles (git_sha, manifest_hash, daemon_hashes)
		values ($1, $2, $3::jsonb)
		returning id
	`, b.GitSHA, b.ManifestHash, string(hashes)).Scan(&id)
	if err != nil {
		return "", fmt.Errorf("releaseinstall: insert bundle: %w", err)
	}
	return id, nil
}

// MarkApplied implements Store.
//
// The query is the load-bearing first-write-wins contract: the
// conditional UPDATE only runs if applied_at IS NULL, so two
// concurrent node installs on the same release both succeed but
// only the first one sets applied_at. The RETURNING clause tells
// the caller which side of the race they were on.
func (s pgStore) MarkApplied(ctx context.Context, gitSHA string) (bool, error) {
	if gitSHA == "" {
		return false, fmt.Errorf("releaseinstall: empty git_sha")
	}
	var appliedAt *time.Time
	err := s.pool.QueryRow(ctx, `
		update release_bundles
		   set applied_at = now()
		 where git_sha = $1
		   and applied_at IS NULL
		returning applied_at
	`, gitSHA).Scan(&appliedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Two options: (a) the git_sha doesn't exist, or
			// (b) applied_at was already set. Distinguish by
			// a follow-up lookup.
			_, gerr := s.GetByGitSHA(ctx, gitSHA)
			if gerr != nil {
				return false, gerr
			}
			return false, nil
		}
		return false, fmt.Errorf("releaseinstall: mark applied: %w", err)
	}
	return appliedAt != nil, nil
}

// GetByGitSHA implements Store.
func (s pgStore) GetByGitSHA(ctx context.Context, gitSHA string) (BundleRow, error) {
	if gitSHA == "" {
		return BundleRow{}, fmt.Errorf("releaseinstall: empty git_sha")
	}
	var (
		row         BundleRow
		daemonJSON  []byte
	)
	err := s.pool.QueryRow(ctx, `
		select id,
		       git_sha,
		       manifest_hash,
		       daemon_hashes::text,
		       created_at,
		       applied_at
		  from release_bundles
		 where git_sha = $1
	`, gitSHA).Scan(
		&row.ID,
		&row.GitSHA,
		&row.ManifestHash,
		&daemonJSON,
		&row.CreatedAt,
		&row.AppliedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return BundleRow{}, ErrNotFound
		}
		return BundleRow{}, fmt.Errorf("releaseinstall: get bundle: %w", err)
	}
	hashes, err := DecodeDaemonHashes(daemonJSON)
	if err != nil {
		return BundleRow{}, fmt.Errorf("releaseinstall: decode daemon_hashes: %w", err)
	}
	row.DaemonHashes = hashes
	return row, nil
}

// ListApplied implements Store.
func (s pgStore) ListApplied(ctx context.Context) ([]BundleRow, error) {
	rows, err := s.pool.Query(ctx, `
		select id,
		       git_sha,
		       manifest_hash,
		       daemon_hashes::text,
		       created_at,
		       applied_at
		  from release_bundles
		 where applied_at IS NOT NULL
		 order by applied_at desc
	`)
	if err != nil {
		return nil, fmt.Errorf("releaseinstall: list applied: %w", err)
	}
	defer rows.Close()
	var out []BundleRow
	for rows.Next() {
		var (
			row        BundleRow
			daemonJSON []byte
		)
		if err := rows.Scan(
			&row.ID,
			&row.GitSHA,
			&row.ManifestHash,
			&daemonJSON,
			&row.CreatedAt,
			&row.AppliedAt,
		); err != nil {
			return nil, fmt.Errorf("releaseinstall: scan: %w", err)
		}
		hashes, err := DecodeDaemonHashes(daemonJSON)
		if err != nil {
			return nil, fmt.Errorf("releaseinstall: decode daemon_hashes: %w", err)
		}
		row.DaemonHashes = hashes
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("releaseinstall: iterate: %w", err)
	}
	return out, nil
}
