// cmd_deploy_github.go — `gregale deploy --github` snippet generator
// (issue #270, faas-deploy-action). Companion to the customer-facing
// composite Action at poyrazK/faas-deploy-action. Emits a copy-paste
// GitHub Actions workflow snippet to stdout and exits 0 with no auth
// and no side effects. Mirrors the `cmdBillingPortal --print` shape
// (cmd/gregale/commands_billing.go:104-157) — just print, no auth.
//
// Detection: when GITHUB_REPOSITORY and GITHUB_SHA are set (i.e. the
// process is itself running inside an Actions runner), the snippet
// hard-codes those values so a customer running `gregale deploy
// --github` from inside their own workflow gets a concrete, ready-to-run
// file. When neither env var is set, the snippet emits the
// `${{ github.repository }}` / `${{ github.sha }}` expressions so the
// file is portable across repos.
//
// The user-facing helper is cmdDeployGithubSnippet(args []string) int —
// the --github flag short-circuit in cmdDeployTarball (commands2.go)
// calls it. The pure builder is renderGithubSnippet(env, app, pinnedSHA)
// so the test can drive it without flag-parsing gymnastics.

package main

import (
	"flag"
	"fmt"
	"os"
)

// githubActionVersion is the Action tag the snippet pins to. Bump on
// every release of poyrazK/faas-deploy-action. The snippet also emits a
// `# pin:` comment line pointing at the immutable SHA so customers who
// want hard reproducibility can copy-paste it; v1.0.0 is the first
// tagged release. Per the plan §User-confirmed scope decisions: pinned-
// major @v1 with the bundled CLI version surfaced as `cli-version` is
// the recommended shape; the SHA pin is the optional reproducibility
// escape hatch.
const githubActionVersion = "v1"

// githubActionHeadRef is the canonical-when-pinned, ${{ github.* }}-
// when-not comment the snippet surfaces. The single source of truth
// (this file) drives the rendered YAML so a release can update both
// with one commit.
const (
	githubActionRepo = "poyrazK/faas-deploy-action"
)

// githubSnippetEnv captures the env vars the snippet generator reads.
// Pulled into a struct so the test can drive both the "running inside
// a runner" and "running from a local checkout" cases without env
// mutation across parallel sub-tests.
type githubSnippetEnv struct {
	// Repository is OWNER/NAME; default `github.repository` expression.
	Repository string
	// SHA is the 40-char commit ref; default `github.sha` expression.
	SHA string
	// Runner is true when both env vars are present; controls whether
	// the snippet emits concrete values or `${{ github.* }}` expressions.
	Runner bool
}

// detectGithubSnippetEnv reads the runner env. The two GITHUB_REPOSITORY
// / GITHUB_SHA env vars are set by every Actions runner, on every step,
// in every job — they're the canonical "are we inside a runner" signal.
// We never trust the values (the snippet is just shape, not runtime
// config), but their presence is the discriminator.
func detectGithubSnippetEnv() githubSnippetEnv {
	repo := os.Getenv("GITHUB_REPOSITORY")
	sha := os.Getenv("GITHUB_SHA")
	return githubSnippetEnv{
		Repository: repo,
		SHA:        sha,
		Runner:     repo != "" && sha != "",
	}
}

// renderGithubSnippet builds the workflow YAML body. Inputs:
//   - env: the runtime env (renderer branch selector + concrete values).
//   - app: the app slug; required. Empty -> caller's responsibility to
//     validate before calling (the snippet generator does so at the
//     CLI boundary).
//   - pinnedSHA: the immutable commit SHA for the @v1 tag. Pass "" for
//     the "first release" case where the tag exists but the SHA pin
//     comment is omitted (the snippet still pins `@v1` and the bundled
//     `cli-version` output surfaces the actual CLI version).
//
// The output is a multi-line YAML string, ready to `> workflow.yml`.
// The leading `# Gregale deploy · generated` line is the snippet's
// sentinel: parseable by a CI bot that wants to detect "this workflow
// was generated by our CLI" without parsing the whole file.
func renderGithubSnippet(env githubSnippetEnv, app, pinnedSHA string) string {
	// repo / ref pick: concrete values when running inside a runner,
	// `${{ github.* }}` expressions otherwise. The expressions are the
	// portable default; the concrete form is opt-in for the "run from
	// inside a workflow" scenario.
	repoExpr := "${{ github.repository }}"
	refExpr := "${{ github.sha }}"
	if env.Runner {
		repoExpr = env.Repository
		refExpr = env.SHA
	}

	// Action reference + pin comment. The `uses:` line picks `@v1` by
	// default (per the user-confirmed scope decision); the `# pin:`
	// comment shows the immutable SHA for customers who want repro.
	usesRef := "poyrazK/faas-deploy-action@v1"
	pinLine := ""
	if pinnedSHA != "" {
		pinLine = fmt.Sprintf("# pin this Action for reproducibility: %s@%s\n", githubActionRepo, pinnedSHA)
	} else {
		// No SHA → drop the pin line; the README covers the
		// "first release, no SHA yet" case explicitly.
		pinLine = ""
	}

	// API base placeholder. The customer fills in their actual host
	// (different for Hobby/Pro/Scale deployments). The README's
	// "Before you commit" section explains the substitution.
	apiBase := "https://api.faas.example"

	// The heredoc body uses tab-indented YAML, sandwiched between the
	// two header-line fences. We keep the secret reference as
	// `${{ secrets.GREGALE_API_KEY }}` (never a literal) so customers
	// can paste the snippet into a public repo without leaking the
	// token. The plan R7 mitigation documents this.
	return fmt.Sprintf(`# Gregale deploy · generated by `+"`gregale deploy --github`"+`
# App: %s · Repo: %s · Ref: %s
# Action: %s@%s
%s# For production safety, see docs/source-ref.md "GitHub Actions" section.
name: deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production             # opt-in; remove if not using GitHub Environments
    permissions:
      contents: read
      id-token: none                    # OIDC is out of scope for the first action
    steps:
      - uses: %s
        with:
          api-key: ${{ secrets.GREGALE_API_KEY }}
          api-base: %s
          app: %s
          # repo / ref default to ${{ github.repository }} / ${{ github.sha }}
          wait: "true"
`,
		app, repoExpr, refExpr,
		githubActionRepo, githubActionVersion,
		pinLine,
		usesRef,
		apiBase,
		app,
	)
}

// cmdDeployGithubSnippet is the CLI entry point. Parses the deploy
// subcommand's --app / --repo / --ref overrides, then renders and
// prints the snippet. Exits 0 on success; 1 on flag-parse failure or
// when --app is missing (the deploy subcommand already resolves the
// slug from --name or cwd before the short-circuit fires, so a
// missing --app is a programmer error — the CLI boundary defence).
func cmdDeployGithubSnippet(args []string) int {
	fs := flag.NewFlagSet("deploy --github", flag.ContinueOnError)
	app := fs.String("app", "", "app slug (required)")
	repo := fs.String("repo", "", "override snippet repo (default: ${{ github.repository }} or GITHUB_REPOSITORY)")
	ref := fs.String("ref", "", "override snippet ref (default: ${{ github.sha }} or GITHUB_SHA)")
	pinnedSHA := fs.String("pinned-sha", "", "optional @v1 commit SHA for the `# pin:` comment line")
	if err := fs.Parse(args); err != nil {
		PrintUsage(osStderr, "usage: gregale deploy --github [--app SLUG] [--repo OWNER/NAME] [--ref REF] [--pinned-sha SHA]", "deploy")
		return 1
	}
	if *app == "" {
		PrintFail(osStderr, "missing --app (the snippet generator needs a slug to embed)")
		return 1
	}
	env := detectGithubSnippetEnv()
	if *repo != "" || *ref != "" {
		// CLI overrides beat env detection. Mirror the field-by-field
		// shape so a customer can override one without the other.
		if *repo != "" {
			env.Repository = *repo
		}
		if *ref != "" {
			env.SHA = *ref
		}
		// Disable the `${{ github.* }}` fallback so the concrete
		// values win. The customer said "use these"; honor it.
		env.Runner = true
	}
	_, _ = fmt.Fprint(osStdout, renderGithubSnippet(env, *app, *pinnedSHA))
	return 0
}
