// commands/completion_zsh.go — Tier A8 / ADR-083.
//
// `gregale completion zsh` emits a zsh completion script. The
// script uses #compdef gregale (the autoload directive zsh
// recognises on $fpath) and a single _gregale function that
// walks COMP_WORDS to figure out which position the cursor is
// at, then dispatches to a per-command _gregale_<cmd> helper.
//
// Zsh's _arguments is the most concise of the four backends —
// it lets us declare the spec inline and zsh handles the
// per-position completion dispatch. The downside is that the
// _arguments form for 50+ commands is verbose; we emit it anyway
// because it matches user expectations (every zsh completion
// looks like this) and the size cost is a one-time file write.

package main

import (
	"fmt"
	"io"
	"strings"
)

func cmdCompletionZsh() int {
	w := osStdout
	renderZshHeader(w)
	for _, c := range cliCommands {
		renderZshCommand(w, c)
	}
	renderZshFooter(w)
	return 0
}

func renderZshHeader(w io.Writer) {
	_, _ = fmt.Fprintln(w, "#compdef gregale")
	_, _ = fmt.Fprintln(w, "# zsh completion for gregale — generated by `gregale completion zsh`.")
	_, _ = fmt.Fprintln(w, "# Install: gregale completion zsh > \"${fpath[1]}/_gregale\"")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "_gregale_cache_slugs() {")
	_, _ = fmt.Fprintln(w, "  local kind=\"$1\"")
	_, _ = fmt.Fprintln(w, "  local path=\"$(gregale completion-cache-path 2>/dev/null)\"")
	_, _ = fmt.Fprintln(w, "  [[ -z \"$path\" || ! -r \"$path\" ]] && return 1")
	// sed slice rather than grep -E with literal braces — grep
	// treats '{' as a quantifier metacharacter and rejects it.
	_, _ = fmt.Fprintln(w, "  sed -n \"/\\\"$kind\\\":\\[/,/]/p\" \"$path\" 2>/dev/null \\")
	_, _ = fmt.Fprintln(w, "    | grep -oE '\"slug\":\"[^\"]+\"' \\")
	_, _ = fmt.Fprintln(w, "    | sed -E 's/.*\"slug\":\"([^\"]+)\".*/\\1/'")
	_, _ = fmt.Fprintln(w, "}")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "_gregale() {")
	_, _ = fmt.Fprintln(w, "  local -a commands")
	_, _ = fmt.Fprintln(w, "  commands=(")
	for _, c := range cliCommands {
		_, _ = fmt.Fprintf(w, "    '%s:%s'\n", c.Name, escapeZsh(c.Short))
	}
	_, _ = fmt.Fprintln(w, "  )")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "  if (( CURRENT == 2 )); then")
	_, _ = fmt.Fprintln(w, "    _describe 'command' commands")
	_, _ = fmt.Fprintln(w, "    return 0")
	_, _ = fmt.Fprintln(w, "  fi")
	_, _ = fmt.Fprintln(w)
}

// renderZshCommand emits one _gregale_<cmd> function per cliCommand.
// The function declares _arguments with the verb list, the flag
// list, and (where applicable) the closed-set positional list.
// Slug cache completion is offered for the first positional when
// the command takes one and the name matches the cache keys.
func renderZshCommand(w io.Writer, c cliCommand) {
	_, _ = fmt.Fprintf(w, "  _gregale_%s() {\n", c.Name)
	verbList := make([]string, 0, len(c.Subcommands))
	for _, s := range c.Subcommands {
		verbList = append(verbList, s.Name+":"+escapeZsh(s.Short))
	}
	flagList := make([]string, 0, len(c.Flags))
	for _, f := range c.Flags {
		flagList = append(flagList, "--"+f.Name+"["+escapeZsh(f.Short)+"]")
	}
	args := append([]string{}, verbList...)
	args = append(args, flagList...)
	if len(c.ClosedSet) > 0 {
		args = append(args, "1:plan:("+strings.Join(c.ClosedSet, " ")+")")
	} else if c.hasSlugFirst() {
		args = append(args, "1:slug:($(_gregale_cache_slugs apps))")
	}
	if len(args) == 0 {
		_, _ = fmt.Fprintln(w, "    _arguments && return 0")
	} else {
		_, _ = fmt.Fprintf(w, "    _arguments %s && return 0\n", strings.Join(args, " "))
	}
	_, _ = fmt.Fprintln(w, "  }")
}

// renderZshFooter closes the _gregale function and dispatches to
// the per-command helper. The dispatch is a case statement on
// $words[2] (the first arg after `gregale`).
func renderZshFooter(w io.Writer) {
	_, _ = fmt.Fprintln(w, "  case \"$words[2]\" in")
	for _, c := range cliCommands {
		_, _ = fmt.Fprintf(w, "    %s) _gregale_%s ;;\n", c.Name, c.Name)
	}
	_, _ = fmt.Fprintln(w, "  esac")
	_, _ = fmt.Fprintln(w, "}")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "_gregale \"$@\"")
}

// escapeZsh backslash-escapes the single-quote characters in a
// description so the zsh _describe format stays parseable. zsh's
// single-quote strings can't contain a literal single quote; the
// workaround is to close the quote, emit \\', and reopen.
func escapeZsh(s string) string {
	return strings.ReplaceAll(s, "'", `'\''`)
}
