#!/usr/bin/env node
// scripts/gen.mjs — runs the pinned openapi-typescript-codegen against
// the canonical spec at api/openapi.yaml. Output goes into
// sdk/node/src/generated/ and is committed per ADR-013.
//
// The script is cwd-independent: paths are resolved from this file via
// import.meta.url. CI invokes it through `npm run gen`, local developers
// through `make sdk-gen-node`.

import { generate } from 'openapi-typescript-codegen';
import { fileURLToPath } from 'node:url';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..', '..');
const specPath = resolve(repoRoot, 'api', 'openapi.yaml');
const outDir = resolve(here, '..', 'src', 'generated');

await generate({
  input: specPath,
  output: outDir,
  httpClient: 'fetch',
  useOptions: true,
  useUnionTypes: true,
  exportCore: true,
  exportServices: true,
  exportModels: true,
  exportSchemas: false,
  indent: '2',
});

// Post-process pass 1: rewrite extensionless relative imports to
// .js. openapi-typescript-codegen@0.31.0 emits `from './Foo'`, but
// NodeNext module resolution requires explicit `.js`. The regex
// matches `from '(\.{1,2}/[^']+)'` and appends `.js`. We skip the
// generated barrel we just wrote (it already has `.js`).
//
// Idempotent: re-running with `.js` already present matches nothing
// because `\.js` is not part of the captured group.
async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full);
    } else if (entry.name.endsWith('.ts')) {
      const src = await readFile(full, 'utf8');
      const fixed = src.replace(
        /from\s+'((?:\.{1,2}\/)[^']+)'/g,
        (m, p1) => (p1.endsWith('.js') ? m : `from '${p1}.js'`),
      );
      if (fixed !== src) {
        await writeFile(full, fixed, 'utf8');
      }
    }
  }
}
await walk(outDir);

// Post-process pass 2: write the models barrel. The generator
// emits one file per model but no barrel; `src/index.ts` re-exports
// the models via `export type * from './generated/models/index.js'`
// so customers can also do
//   `import type { AppResponse } from 'gregale/skd-node'`.
const modelsDir = resolve(outDir, 'models');
const modelFiles = (await readdir(modelsDir))
  .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
  .sort();
const barrel = [
  '/* generated by sdk/node/scripts/gen.mjs — do not edit */',
  '/* istanbul ignore file */',
  '',
  ...modelFiles.map((f) => {
    const name = f.replace(/\.ts$/, '');
    return `export type { ${name} } from './${name}.js';`;
  }),
  '',
].join('\n');
await writeFile(resolve(modelsDir, 'index.ts'), barrel, 'utf8');

console.log(`sdk/node: generated clients from ${specPath} -> ${outDir}`);
console.log(`sdk/node: post-processed relative imports to .js`);
console.log(`sdk/node: wrote models barrel (${modelFiles.length} entries)`);